--[[
    init.lua
    Created: 08/21/2025 19:12:16
    Description: Autogenerated script file for the map berry_grove.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local berry_grove = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---berry_grove.Init(zone)
--Engine callback function
function berry_grove.Init(zone)
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    PrintInfo("=>> Init_berry_grove")
end

---berry_grove.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function berry_grove.EnterSegment(zone, rescuing, segmentID, mapID)
    if rescuing ~= true then
        COMMON.BeginDungeon(zone.ID, segmentID, mapID)
    end
end

---berry_grove.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function berry_grove.ExitSegment(zone, result, rescue, segmentID, mapID)
  --first check for rescue flag; if we're in rescue mode then take a different path
  local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID) --check if we cleared while doing a rescue
  if exited then
        --do nothing; this is a dummy branch to stop us from going through the other branches
   elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then -- resolves true if the dungeon was not cleared
        --end the dungeon day by sending the player back to their last checkpoint, since they didn't clear the dungeon
         COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
   else -- we didn't resolve true for being in rescue or losing the dungeon, so we must have cleared the dungeon
         -- now we will check what segment we took, so we can make the game do what we want to depending on the segment
         if segmentID == 0 then
            COMMON.EndDungeonDay(result, 'guildmaster_island', -1, 1, 3)
         else -- this is a fallback branch, in case we went through all of the branches and hit nothing (which should not happen!)
                 PrintInfo("No exit procedure found!")
                 -- just send the player to their last checkpoint
	             COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
         end
   end

end

---berry_grove.Rescued(zone, name, mail)
--Engine callback function
function berry_grove.Rescued(zone, name, mail)
    COMMON.Rescued(zone, name, mail)
end

return berry_grove

