-- PMU Ground Controller for pmu_s4 (Poké Town Housing District)
-- Generated by PMU Pipeline (New Era)
local pmu_s4 = {}

function pmu_s4.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s4.Enter(map)
  local music = 'PMD) Rescue Team Base.mp3'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s4.Update(map, time)
end

function pmu_s4.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s202', 'Entrance', false)
end

function pmu_s4.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s645', 'Entrance', false)
end

function pmu_s4.Warp_3_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1490', 'Entrance', false)
end

function pmu_s4.Warp_4_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s998', 'Entrance', false)
end

function pmu_s4.Warp_5_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s663', 'Entrance', false)
end

function pmu_s4.Sign_1_Action(obj, activator)
  UI:WaitShowDialogue('Azura\'s House')
end

function pmu_s4.Sign_2_Action(obj, activator)
  UI:WaitShowDialogue('Flare\'s House')
end

function pmu_s4.Sign_3_Action(obj, activator)
  UI:WaitShowDialogue('Luminare\'s House')
end

function pmu_s4.Sign_4_Action(obj, activator)
  UI:WaitShowDialogue('chomp\'s house')
end

function pmu_s4.Sign_5_Action(obj, activator)
  UI:WaitShowDialogue('pokemonmaster2437\'s house')
end

function pmu_s4.Sign_6_Action(obj, activator)
  UI:WaitShowDialogue('Max222\'s House')
end

function pmu_s4.Sign_7_Action(obj, activator)
  UI:WaitShowDialogue('Team Spark Base')
end

function pmu_s4.Sign_8_Action(obj, activator)
  UI:WaitShowDialogue('Sladhe\'s House')
end

function pmu_s4.Sign_9_Action(obj, activator)
  UI:WaitShowDialogue('Sonamus\' Nest')
end

function pmu_s4.Sign_10_Action(obj, activator)
  UI:WaitShowDialogue('Pedro sa\'s House')
end

return pmu_s4
