<<<<<<< HEAD
"""PixelLab API Client & Cache Engine for PMDO Town Generator.

Integrates with PixelLab (https://api.pixellab.ai) for pixel-art tilesets,
building stamps, and map object generation with automatic caching, SHA-256 provenance,
and offline synthesis fallback.
"""
=======
"""PixelLab API client and persistent asset cache manager."""
>>>>>>> fab534f9 (feat(skytemple): Pipeline de creation et validation de maps PMD/PMDO conformes SkyTemple)
from __future__ import annotations

import hashlib
import json
<<<<<<< HEAD
import os
import time
import urllib.error
import urllib.request
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from PIL import Image, ImageColor, ImageDraw, ImageFilter


DEFAULT_PIXELLAB_TOKEN = "4ac820d2-3d4c-4aff-a287-49246dc961ec"
PIXELLAB_API_BASE = "https://api.pixellab.ai"
=======
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional
from PIL import Image, ImageDraw

DEFAULT_PIXELLAB_TOKEN = "4ac820d2-3d4c-4aff-a287-49246dc961ec"
>>>>>>> fab534f9 (feat(skytemple): Pipeline de creation et validation de maps PMD/PMDO conformes SkyTemple)


@dataclass
class PixelLabAsset:
<<<<<<< HEAD
    """Represents an asset generated or cached via PixelLab."""
    asset_id: str
    asset_type: str  # "tileset", "structure", "object", "tile"
    prompt: str
    parameters: Dict[str, Any]
    image_path: str
    sha256: str
    created_at: float
    source: str  # "pixellab_api" or "pixellab_synthetic_fallback"


@dataclass
class PixelLabWangTileset:
    """Represents a 16-tile Wang tileset generated by PixelLab."""
    tileset_id: str
    lower_terrain: str
    upper_terrain: str
    tile_size: int
    image_path: str
    tiles: List[str]  # 16 sub-tile identifiers or coords
    sha256: str
    source: str


class PixelLabClient:
    """Client for PixelLab AI pixel art generation platform."""

    def __init__(
        self,
        api_token: Optional[str] = None,
        cache_dir: Optional[Path] = None,
        project_root: Optional[Path] = None,
        timeout: int = 15,
    ):
        self.project_root = project_root or Path(__file__).resolve().parents[2]
        self.api_token = api_token or os.environ.get("PIXELLAB_API_KEY") or DEFAULT_PIXELLAB_TOKEN
        self.cache_dir = cache_dir or (self.project_root / "data/pixellab_cache")
        self.timeout = timeout

        # Ensure cache directories exist
        (self.cache_dir / "tilesets").mkdir(parents=True, exist_ok=True)
        (self.cache_dir / "structures").mkdir(parents=True, exist_ok=True)
        (self.cache_dir / "decorations").mkdir(parents=True, exist_ok=True)
        (self.cache_dir / "objects").mkdir(parents=True, exist_ok=True)

        self.manifest_path = self.cache_dir / "manifest.json"
        self.manifest: Dict[str, Any] = self._load_manifest()
=======
    asset_id: str
    asset_type: str  # "tileset", "building", "animation"
    prompt: str
    image_path: Path
    sha256: str
    source: str  # "api" or "cache" or "synthesized"


class PixelLabClient:
    """Client for PixelLab API with offline fallback synthesizer and caching."""

    def __init__(self, api_token: str = DEFAULT_PIXELLAB_TOKEN, project_root: Optional[Path] = None):
        self.api_token = api_token
        self.project_root = project_root or Path(__file__).resolve().parents[2]
        self.cache_dir = self.project_root / "data/pixellab_cache"
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.manifest_path = self.cache_dir / "manifest.json"
        self.manifest = self._load_manifest()
>>>>>>> fab534f9 (feat(skytemple): Pipeline de creation et validation de maps PMD/PMDO conformes SkyTemple)

    def _load_manifest(self) -> Dict[str, Any]:
        if self.manifest_path.exists():
            try:
                with open(self.manifest_path, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception:
<<<<<<< HEAD
                pass
        return {"version": "1.0", "assets": {}, "updated_at": time.time()}

    def _save_manifest(self) -> None:
        self.manifest["updated_at"] = time.time()
        with open(self.manifest_path, "w", encoding="utf-8") as f:
            json.dump(self.manifest, f, indent=2)

    def _compute_key(self, prefix: str, params: Dict[str, Any]) -> str:
        serialized = json.dumps(params, sort_keys=True)
        hash_val = hashlib.sha256(serialized.encode("utf-8")).hexdigest()[:16]
        return f"{prefix}_{hash_val}"

    def create_topdown_tileset(
        self,
        lower_description: str,
        upper_description: str,
        transition_description: Optional[str] = None,
        tile_size: int = 24,
        base_tile_id: Optional[str] = None,
        palette_hint: Optional[Dict[str, Tuple[int, int, int]]] = None,
    ) -> PixelLabWangTileset:
        """Generates a 16-tile top-down Wang tileset using PixelLab."""
        params = {
            "lower": lower_description,
            "upper": upper_description,
            "transition": transition_description,
            "tile_size": tile_size,
            "base_tile_id": base_tile_id,
        }
        key = self._compute_key("tileset", params)
        cached_img_path = self.cache_dir / "tilesets" / f"{key}.png"
        cached_meta_path = self.cache_dir / "tilesets" / f"{key}.json"

        # Check Cache
        if cached_img_path.exists() and cached_meta_path.exists():
            with open(cached_meta_path, "r", encoding="utf-8") as f:
                meta = json.load(f)
            return PixelLabWangTileset(
                tileset_id=key,
                lower_terrain=lower_description,
                upper_terrain=upper_description,
                tile_size=tile_size,
                image_path=str(cached_img_path),
                tiles=meta.get("tiles", []),
                sha256=meta.get("sha256", ""),
                source=meta.get("source", "cache"),
            )

        # Attempt API Call
        img, source = self._request_tileset_api(params)
        if img is None:
            # Fallback to deterministic PixelLab-compliant synthesizer
            img = self._synthesize_wang_tileset(
                lower_description=lower_description,
                upper_description=upper_description,
                tile_size=tile_size,
                palette_hint=palette_hint,
            )
            source = "pixellab_synthetic_fallback"

        img.save(cached_img_path, "PNG")

        # Compute SHA256
        with open(cached_img_path, "rb") as f:
            sha256_hash = hashlib.sha256(f.read()).hexdigest()

        tiles_indices = [f"tile_{i}" for i in range(16)]
        metadata = {
            "tileset_id": key,
            "lower": lower_description,
            "upper": upper_description,
            "tile_size": tile_size,
            "tiles": tiles_indices,
            "sha256": sha256_hash,
            "source": source,
            "created_at": time.time(),
        }
        with open(cached_meta_path, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2)

        self.manifest["assets"][key] = metadata
        self._save_manifest()

        return PixelLabWangTileset(
            tileset_id=key,
            lower_terrain=lower_description,
            upper_terrain=upper_description,
            tile_size=tile_size,
            image_path=str(cached_img_path),
            tiles=tiles_indices,
            sha256=sha256_hash,
            source=source,
        )

    def create_structure_stamp(
        self,
        description: str,
        category: str,
        width: int = 64,
        height: int = 64,
        style_image_path: Optional[str] = None,
        no_background: bool = True,
        palette_hint: Optional[Dict[str, Tuple[int, int, int]]] = None,
    ) -> PixelLabAsset:
        """Generates a structure/building pixel art stamp via PixelLab."""
        params = {
            "description": description,
            "category": category,
            "width": width,
            "height": height,
            "style_image_path": style_image_path,
            "no_background": no_background,
        }
        key = self._compute_key(f"struct_{category}", params)
        cached_img_path = self.cache_dir / "structures" / f"{key}.png"
        cached_meta_path = self.cache_dir / "structures" / f"{key}.json"

        if cached_img_path.exists() and cached_meta_path.exists():
            with open(cached_meta_path, "r", encoding="utf-8") as f:
                meta = json.load(f)
            return PixelLabAsset(
                asset_id=key,
                asset_type="structure",
                prompt=description,
                parameters=params,
                image_path=str(cached_img_path),
                sha256=meta.get("sha256", ""),
                created_at=meta.get("created_at", 0),
                source=meta.get("source", "cache"),
            )

        # Attempt API Call
        img, source = self._request_image_api(params)
        if img is None:
            img = self._synthesize_structure_sprite(
                category=category,
                description=description,
                width=width,
                height=height,
                style_image_path=style_image_path,
                palette_hint=palette_hint,
            )
            source = "pixellab_synthetic_fallback"

        img.save(cached_img_path, "PNG")

        with open(cached_img_path, "rb") as f:
            sha256_hash = hashlib.sha256(f.read()).hexdigest()

        metadata = {
            "asset_id": key,
            "asset_type": "structure",
            "prompt": description,
            "parameters": params,
            "sha256": sha256_hash,
            "source": source,
            "created_at": time.time(),
        }
        with open(cached_meta_path, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2)

        self.manifest["assets"][key] = metadata
        self._save_manifest()

        return PixelLabAsset(
            asset_id=key,
            asset_type="structure",
            prompt=description,
            parameters=params,
            image_path=str(cached_img_path),
            sha256=sha256_hash,
            created_at=metadata["created_at"],
            source=source,
        )

    def _request_tileset_api(self, params: Dict[str, Any]) -> Tuple[Optional[Image.Image], str]:
        """Attempts live PixelLab API call for top-down tileset."""
        url = f"{PIXELLAB_API_BASE}/v2/create-tileset"
        headers = {
            "Authorization": f"Bearer {self.api_token}",
            "Content-Type": "application/json",
            "User-Agent": "PMDO-PixelLab-Generator/1.0",
        }
        payload = json.dumps(params).encode("utf-8")
        try:
            req = urllib.request.Request(url, data=payload, headers=headers, method="POST")
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                if resp.status == 200:
                    data = resp.read()
                    # Might return JSON with download url or direct PNG
                    content_type = resp.headers.get("Content-Type", "")
                    if "json" in content_type:
                        res_json = json.loads(data.decode("utf-8"))
                        if "image_url" in res_json:
                            img_req = urllib.request.Request(res_json["image_url"])
                            with urllib.request.urlopen(img_req, timeout=self.timeout) as img_resp:
                                import io
                                return Image.open(io.BytesIO(img_resp.read())).convert("RGBA"), "pixellab_api"
                    else:
                        import io
                        return Image.open(io.BytesIO(data)).convert("RGBA"), "pixellab_api"
        except Exception:
            pass
        return None, ""

    def _request_image_api(self, params: Dict[str, Any]) -> Tuple[Optional[Image.Image], str]:
        """Attempts live PixelLab API call for image / map object generation."""
        url = f"{PIXELLAB_API_BASE}/v2/create-image-bitforge"
        headers = {
            "Authorization": f"Bearer {self.api_token}",
            "Content-Type": "application/json",
            "User-Agent": "PMDO-PixelLab-Generator/1.0",
        }
        payload = json.dumps(params).encode("utf-8")
        try:
            req = urllib.request.Request(url, data=payload, headers=headers, method="POST")
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                if resp.status == 200:
                    data = resp.read()
                    content_type = resp.headers.get("Content-Type", "")
                    if "json" in content_type:
                        res_json = json.loads(data.decode("utf-8"))
                        if "image_url" in res_json:
                            img_req = urllib.request.Request(res_json["image_url"])
                            with urllib.request.urlopen(img_req, timeout=self.timeout) as img_resp:
                                import io
                                return Image.open(io.BytesIO(img_resp.read())).convert("RGBA"), "pixellab_api"
                    else:
                        import io
                        return Image.open(io.BytesIO(data)).convert("RGBA"), "pixellab_api"
        except Exception:
            pass
        return None, ""

    # ------------------------------------------------------------------
    # PixelLab High-Fidelity Synthesizer Fallback (Deterministic Pixel Art)
    # ------------------------------------------------------------------

    def _synthesize_wang_tileset(
        self,
        lower_description: str,
        upper_description: str,
        tile_size: int = 24,
        palette_hint: Optional[Dict[str, Tuple[int, int, int]]] = None,
    ) -> Image.Image:
        """Synthesizes a 4x4 (16 tiles) Wang top-down terrain atlas matching PixelLab standards."""
        ts = tile_size
        atlas_img = Image.new("RGBA", (ts * 4, ts * 4), (0, 0, 0, 0))

        # Determine palettes based on terrain descriptions
        c_lower, c_upper, c_edge = self._resolve_terrain_colors(
            lower_description, upper_description, palette_hint
        )

        # 16 Wang configurations (4x4 layout):
        # Row 0: Solid Upper, N edge, E edge, NE corner
        # Row 1: S edge, N+S bridge, SE corner, E+S inner
        # Row 2: W edge, NW corner, E+W bridge, W+S inner
        # Row 3: SW corner, N+W inner, N+E inner, Solid Lower
        for row in range(4):
            for col in range(4):
                idx = row * 4 + col
                tile_im = self._render_wang_tile(
                    idx, ts, c_lower, c_upper, c_edge, lower_description, upper_description
                )
                atlas_img.paste(tile_im, (col * ts, row * ts))

        return atlas_img

    def _resolve_terrain_colors(
        self,
        lower: str,
        upper: str,
        hint: Optional[Dict[str, Tuple[int, int, int]]] = None,
    ) -> Tuple[Tuple[int, int, int, int], Tuple[int, int, int, int], Tuple[int, int, int, int]]:
        hint = hint or {}

        def get_col(name: str, default: Tuple[int, int, int]) -> Tuple[int, int, int, int]:
            for k, v in hint.items():
                if k.lower() in name.lower():
                    return (v[0], v[1], v[2], 255)
            n = name.lower()
            if "water" in n or "river" in n or "ocean" in n:
                return (95, 183, 207, 255)  # PMD Turquoise
            if "grass" in n or "lawn" in n:
                return (208, 220, 80, 255)  # PMD Spring chartreuse
            if "dirt" in n or "path" in n or "road" in n:
                return (208, 184, 136, 255) # PMD Cobblestone/Dirt
            if "cliff" in n or "rock" in n or "stone" in n:
                return (144, 128, 80, 255)  # PMD Ochre rock
            if "sand" in n or "beach" in n:
                return (240, 220, 160, 255) # Sand
            if "snow" in n or "ice" in n:
                return (230, 245, 255, 255) # Snow
            return (default[0], default[1], default[2], 255)

        c_low = get_col(lower, (95, 183, 207))
        c_up = get_col(upper, (208, 220, 80))
        # Edge color: blend / darker border
        c_edge = (
            max(0, int(c_up[0] * 0.7)),
            max(0, int(c_up[1] * 0.7)),
            max(0, int(c_up[2] * 0.7)),
            255,
        )
        return c_low, c_up, c_edge

    def _render_wang_tile(
        self,
        tile_idx: int,
        ts: int,
        c_low: Tuple[int, int, int, int],
        c_up: Tuple[int, int, int, int],
        c_edge: Tuple[int, int, int, int],
        lower_desc: str,
        upper_desc: str,
    ) -> Image.Image:
        """Renders an individual Wang tile with authentic pixel texture and shading."""
        tile = Image.new("RGBA", (ts, ts), c_low)
        draw = ImageDraw.Draw(tile)

        # Micro-texture noise generator (deterministic per tile_idx)
        def add_noise(img_draw: ImageDraw.ImageDraw, box: Tuple[int, int, int, int], base_col: Tuple[int, int, int, int]):
            x0, y0, x1, y1 = box
            for py in range(y0, y1):
                for px in range(x0, x1):
                    val = (px * 37 + py * 17 + tile_idx * 13) % 19
                    if val == 0:
                        img_draw.point((px, py), fill=(min(255, base_col[0] + 12), min(255, base_col[1] + 12), min(255, base_col[2] + 12), base_col[3]))
                    elif val == 1:
                        img_draw.point((px, py), fill=(max(0, base_col[0] - 14), max(0, base_col[1] - 14), max(0, base_col[2] - 14), base_col[3]))

        half = ts // 2
        q = ts // 4

        # Wang tile geometries:
        if tile_idx == 0:  # Solid Upper
            draw.rectangle([(0, 0), (ts - 1, ts - 1)], fill=c_up)
            add_noise(draw, (0, 0, ts, ts), c_up)
        elif tile_idx == 1:  # North Edge (Upper on S, Lower on N)
            draw.rectangle([(0, 0), (ts - 1, half - 1)], fill=c_low)
            draw.rectangle([(0, half), (ts - 1, ts - 1)], fill=c_up)
            draw.line([(0, half), (ts - 1, half)], fill=c_edge)
            add_noise(draw, (0, half, ts, ts), c_up)
        elif tile_idx == 2:  # East Edge (Upper on W, Lower on E)
            draw.rectangle([(half, 0), (ts - 1, ts - 1)], fill=c_low)
            draw.rectangle([(0, 0), (half - 1, ts - 1)], fill=c_up)
            draw.line([(half - 1, 0), (half - 1, ts - 1)], fill=c_edge)
            add_noise(draw, (0, 0, half, ts), c_up)
        elif tile_idx == 3:  # NE Corner (Upper on SW quadrant)
            draw.rectangle([(0, 0), (ts - 1, ts - 1)], fill=c_low)
            draw.rectangle([(0, half), (half - 1, ts - 1)], fill=c_up)
            draw.line([(0, half), (half - 1, half), (half - 1, ts - 1)], fill=c_edge)
            add_noise(draw, (0, half, half, ts), c_up)
        elif tile_idx == 4:  # South Edge (Upper on N, Lower on S)
            draw.rectangle([(0, 0), (ts - 1, half - 1)], fill=c_up)
            draw.rectangle([(0, half), (ts - 1, ts - 1)], fill=c_low)
            draw.line([(0, half - 1), (ts - 1, half - 1)], fill=c_edge)
            add_noise(draw, (0, 0, ts, half), c_up)
        elif tile_idx == 5:  # N+S Bridge / Vertical channel
            draw.rectangle([(0, 0), (q, ts - 1)], fill=c_low)
            draw.rectangle([(q + 1, 0), (ts - q - 1, ts - 1)], fill=c_up)
            draw.rectangle([(ts - q, 0), (ts - 1, ts - 1)], fill=c_low)
            draw.line([(q, 0), (q, ts - 1)], fill=c_edge)
            draw.line([(ts - q, 0), (ts - q, ts - 1)], fill=c_edge)
        elif tile_idx == 6:  # SE Corner (Upper on NW quadrant)
            draw.rectangle([(0, 0), (ts - 1, ts - 1)], fill=c_low)
            draw.rectangle([(0, 0), (half - 1, half - 1)], fill=c_up)
            draw.line([(half - 1, 0), (half - 1, half - 1), (0, half - 1)], fill=c_edge)
            add_noise(draw, (0, 0, half, half), c_up)
        elif tile_idx == 7:  # E+S Inner Corner (Upper everywhere except SE corner)
            draw.rectangle([(0, 0), (ts - 1, ts - 1)], fill=c_up)
            draw.rectangle([(half, half), (ts - 1, ts - 1)], fill=c_low)
            draw.line([(half, ts - 1), (half, half), (ts - 1, half)], fill=c_edge)
            add_noise(draw, (0, 0, half, ts), c_up)
        elif tile_idx == 8:  # West Edge (Upper on E, Lower on W)
            draw.rectangle([(0, 0), (half - 1, ts - 1)], fill=c_low)
            draw.rectangle([(half, 0), (ts - 1, ts - 1)], fill=c_up)
            draw.line([(half, 0), (half, ts - 1)], fill=c_edge)
            add_noise(draw, (half, 0, ts, ts), c_up)
        elif tile_idx == 9:  # NW Corner (Upper on SE quadrant)
            draw.rectangle([(0, 0), (ts - 1, ts - 1)], fill=c_low)
            draw.rectangle([(half, half), (ts - 1, ts - 1)], fill=c_up)
            draw.line([(half, ts - 1), (half, half), (ts - 1, half)], fill=c_edge)
            add_noise(draw, (half, half, ts, ts), c_up)
        elif tile_idx == 10: # E+W Bridge / Horizontal channel
            draw.rectangle([(0, 0), (ts - 1, q)], fill=c_low)
            draw.rectangle([(0, q + 1), (ts - 1, ts - q - 1)], fill=c_up)
            draw.rectangle([(0, ts - q), (ts - 1, ts - 1)], fill=c_low)
            draw.line([(0, q), (ts - 1, q)], fill=c_edge)
            draw.line([(0, ts - q), (ts - 1, ts - q)], fill=c_edge)
        elif tile_idx == 11: # W+S Inner Corner (Upper everywhere except SW)
            draw.rectangle([(0, 0), (ts - 1, ts - 1)], fill=c_up)
            draw.rectangle([(0, half), (half - 1, ts - 1)], fill=c_low)
            draw.line([(half - 1, ts - 1), (half - 1, half), (0, half)], fill=c_edge)
            add_noise(draw, (half, 0, ts, ts), c_up)
        elif tile_idx == 12: # SW Corner (Upper on NE quadrant)
            draw.rectangle([(0, 0), (ts - 1, ts - 1)], fill=c_low)
            draw.rectangle([(half, 0), (ts - 1, half - 1)], fill=c_up)
            draw.line([(half, half - 1), (ts - 1, half - 1)], fill=c_edge)
            draw.line([(half, 0), (half, half - 1)], fill=c_edge)
            add_noise(draw, (half, 0, ts, half), c_up)
        elif tile_idx == 13: # N+W Inner Corner (Upper everywhere except NW)
            draw.rectangle([(0, 0), (ts - 1, ts - 1)], fill=c_up)
            draw.rectangle([(0, 0), (half - 1, half - 1)], fill=c_low)
            draw.line([(0, half - 1), (half - 1, half - 1), (half - 1, 0)], fill=c_edge)
            add_noise(draw, (half, 0, ts, ts), c_up)
        elif tile_idx == 14: # N+E Inner Corner (Upper everywhere except NE)
            draw.rectangle([(0, 0), (ts - 1, ts - 1)], fill=c_up)
            draw.rectangle([(half, 0), (ts - 1, half - 1)], fill=c_low)
            draw.line([(half, 0), (half, half - 1), (ts - 1, half - 1)], fill=c_edge)
            add_noise(draw, (0, 0, half, ts), c_up)
        else: # 15: Solid Lower
            draw.rectangle([(0, 0), (ts - 1, ts - 1)], fill=c_low)
            add_noise(draw, (0, 0, ts, ts), c_low)

        return tile

    def _synthesize_structure_sprite(
        self,
        category: str,
        description: str,
        width: int,
        height: int,
        style_image_path: Optional[str] = None,
        palette_hint: Optional[Dict[str, Tuple[int, int, int]]] = None,
    ) -> Image.Image:
        """Synthesizes high-fidelity PMDO pixel art structure sprites with authentic materials."""
        # If a style reference exists, try loading base style
        if style_image_path and Path(style_image_path).exists():
            try:
                base_img = Image.open(style_image_path).convert("RGBA")
                if base_img.size == (width, height):
                    return base_img
                return base_img.resize((width, height), Image.Resampling.NEAREST)
            except Exception:
                pass

        # Native pixel art synthesis per category
        img = Image.new("RGBA", (width, height), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)

        # Base structure palettes
        c_wood_dark = (112, 72, 40, 255)
        c_wood_light = (168, 120, 64, 255)
        c_thatch = (220, 184, 88, 255)
        c_thatch_shadow = (176, 140, 64, 255)
        c_stone = (180, 172, 160, 255)
        c_stone_shadow = (120, 112, 100, 255)
        c_door = (80, 48, 24, 255)
        c_glass = (160, 210, 240, 255)

        w, h = width, height

        if "shop" in category or "kecleon" in description.lower():
            # Kecleon Shop: Red striped awning, wooden counter, merchandise baskets
            # Roof Awning
            roof_h = int(h * 0.45)
            for y in range(roof_h):
                t = y / max(1, roof_h)
                rx0 = int((1.0 - t) * (w * 0.15))
                rx1 = int(w - 1 - (1.0 - t) * (w * 0.15))
                # Alternating red and white stripes
                for x in range(rx0, rx1 + 1):
                    stripe = ((x + y // 2) // 6) % 2
                    col = (210, 50, 50, 255) if stripe == 0 else (240, 235, 220, 255)
                    draw.point((x, y + 4), fill=col)

            # Awning shadow & scalloped fringe
            fringe_y = roof_h + 4
            for x in range(int(w * 0.05), int(w * 0.95)):
                draw.point((x, fringe_y), fill=(140, 30, 30, 255))

            # Wooden base walls & counter
            body_y0 = fringe_y + 1
            body_y1 = h - 6
            draw.rectangle([(int(w * 0.15), body_y0), (int(w * 0.85), body_y1)], fill=c_wood_light)
            draw.rectangle([(int(w * 0.15), body_y0), (int(w * 0.85), body_y1)], outline=c_wood_dark)

            # Shop Counter Opening & Mats
            draw.rectangle([(int(w * 0.25), body_y0 + 4), (int(w * 0.75), body_y0 + int(h * 0.25))], fill=(60, 40, 30, 255))
            # Green display mat
            draw.rectangle([(int(w * 0.28), body_y0 + int(h * 0.18)), (int(w * 0.72), body_y1 - 2)], fill=(80, 160, 90, 255))
            # Items (Berries / Orbs)
            draw.ellipse([(int(w * 0.35), body_y0 + int(h * 0.20)), (int(w * 0.45), body_y0 + int(h * 0.28))], fill=(60, 180, 220, 255)) # Blue orb
            draw.ellipse([(int(w * 0.55), body_y0 + int(h * 0.20)), (int(w * 0.65), body_y0 + int(h * 0.28))], fill=(240, 120, 40, 255)) # Oran berry

        elif "cafe" in category or "spinda" in description.lower() or "pokemon_center" in category:
            # Spinda Cafe / Pokemon Center: Large timber structure with stained glass & terrace
            roof_h = int(h * 0.5)
            # Spire/Peaked Roof
            for y in range(roof_h):
                slope = y / max(1, roof_h)
                rx0 = int((1.0 - slope) * (w * 0.45))
                rx1 = int(w - 1 - (1.0 - slope) * (w * 0.45))
                draw.line([(rx0, y + 2), (rx1, y + 2)], fill=(200, 110, 60, 255))
                # Shingle lines
                if y % 4 == 0:
                    draw.line([(rx0, y + 2), (rx1, y + 2)], fill=(150, 75, 40, 255))

            # Main Body (Timber + Cream Plaster)
            body_y0 = roof_h + 2
            body_y1 = h - 4
            draw.rectangle([(int(w * 0.1), body_y0), (int(w * 0.9), body_y1)], fill=(235, 225, 195, 255))
            # Timber frames
            draw.rectangle([(int(w * 0.1), body_y0), (int(w * 0.9), body_y1)], outline=c_wood_dark, width=2)
            draw.line([(int(w * 0.3), body_y0), (int(w * 0.3), body_y1)], fill=c_wood_dark)
            draw.line([(int(w * 0.7), body_y0), (int(w * 0.7), body_y1)], fill=c_wood_dark)

            # Arched Double Door
            door_x0 = int(w * 0.4)
            door_x1 = int(w * 0.6)
            draw.rectangle([(door_x0, body_y1 - int(h * 0.25)), (door_x1, body_y1)], fill=c_door)
            draw.line([(int(w * 0.5), body_y1 - int(h * 0.25)), (int(w * 0.5), body_y1)], fill=c_wood_light)

            # Windows with light
            draw.rectangle([(int(w * 0.16), body_y0 + 6), (int(w * 0.26), body_y0 + int(h * 0.18))], fill=c_glass)
            draw.rectangle([(int(w * 0.74), body_y0 + 6), (int(w * 0.84), body_y0 + int(h * 0.18))], fill=c_glass)

        elif "fountain" in category:
            # Multi-tier stone water fountain
            cx, cy = w // 2, h // 2
            # Base stone pool
            draw.ellipse([(int(w * 0.1), int(h * 0.35)), (int(w * 0.9), int(h * 0.85))], fill=c_stone)
            draw.ellipse([(int(w * 0.15), int(h * 0.4)), (int(w * 0.85), int(h * 0.8))], fill=(80, 170, 200, 255))
            # Upper Tier
            draw.ellipse([(int(w * 0.3), int(h * 0.2)), (int(w * 0.7), int(h * 0.45))], fill=c_stone)
            draw.ellipse([(int(w * 0.35), int(h * 0.23)), (int(w * 0.65), int(h * 0.42))], fill=(110, 200, 230, 255))
            # Spout & Spray
            draw.rectangle([(cx - 2, int(h * 0.1)), (cx + 2, int(h * 0.25))], fill=c_stone_shadow)
            draw.ellipse([(cx - 3, int(h * 0.08)), (cx + 3, int(h * 0.14))], fill=(240, 250, 255, 255))

        else:
            # Standard PMD Elemental Home / Cottage
            roof_h = int(h * 0.5)
            for y in range(roof_h):
                t = y / max(1, roof_h)
                rx0 = int((1.0 - t) * (w * 0.4))
                rx1 = int(w - 1 - (1.0 - t) * (w * 0.4))
                draw.line([(rx0, y + 4), (rx1, y + 4)], fill=c_thatch)
                if y % 3 == 0:
                    draw.line([(rx0, y + 4), (rx1, y + 4)], fill=c_thatch_shadow)

            # Eaves
            draw.line([(int(w * 0.05), roof_h + 4), (int(w * 0.95), roof_h + 4)], fill=c_wood_dark, width=2)

            # Walls
            body_y0 = roof_h + 5
            body_y1 = h - 4
            draw.rectangle([(int(w * 0.12), body_y0), (int(w * 0.88), body_y1)], fill=c_stone)
            draw.rectangle([(int(w * 0.12), body_y0), (int(w * 0.88), body_y1)], outline=c_stone_shadow)

            # Doorway
            door_x0 = int(w * 0.38)
            door_x1 = int(w * 0.62)
            door_y0 = body_y1 - int(h * 0.28)
            draw.rectangle([(door_x0, door_y0), (door_x1, body_y1)], fill=c_door)
            # Door handle
            draw.point((door_x1 - 3, door_y0 + (body_y1 - door_y0) // 2), fill=(240, 210, 80, 255))

            # Window
            draw.rectangle([(int(w * 0.18), body_y0 + 4), (int(w * 0.32), body_y0 + int(h * 0.16))], fill=c_glass)
            draw.rectangle([(int(w * 0.18), body_y0 + 4), (int(w * 0.32), body_y0 + int(h * 0.16))], outline=c_wood_dark)

        return img
=======
                return {}
        return {}

    def _save_manifest(self) -> None:
        with open(self.manifest_path, "w", encoding="utf-8") as f:
            json.dump(self.manifest, f, indent=2)

    def create_structure_stamp(
        self,
        description: str,
        category: str = "shop",
        width: int = 96,
        height: int = 96,
        no_background: bool = True,
    ) -> PixelLabAsset:
        """Creates or fetches cached building sprite stamp."""
        key = f"struct_{category}_{width}x{height}_{description[:20]}"
        asset_id = hashlib.md5(key.encode()).hexdigest()[:12]
        img_path = self.cache_dir / f"{asset_id}.png"

        if not img_path.exists():
            # Synthesize pixel art structure
            img = Image.new("RGBA", (width, height), (0, 0, 0, 0))
            draw = ImageDraw.Draw(img)
            draw.rectangle([4, height // 3, width - 4, height - 4], fill=(215, 190, 150, 255), outline=(90, 60, 30, 255), width=2)
            draw.polygon([(0, height // 3 + 4), (width // 2, 4), (width - 1, height // 3 + 4)], fill=(185, 75, 55, 255), outline=(110, 40, 25, 255))
            # Door
            draw.rectangle([width // 2 - 8, height - 24, width // 2 + 8, height - 4], fill=(75, 45, 25, 255))
            img.save(img_path)

        sha = hashlib.sha256(open(img_path, "rb").read()).hexdigest()
        self.manifest[asset_id] = {
            "type": "building",
            "category": category,
            "description": description,
            "path": str(img_path.relative_to(self.project_root)),
            "sha256": sha,
        }
        self._save_manifest()

        return PixelLabAsset(
            asset_id=asset_id,
            asset_type="building",
            prompt=description,
            image_path=img_path,
            sha256=sha,
            source="synthesized",
        )
>>>>>>> fab534f9 (feat(skytemple): Pipeline de creation et validation de maps PMD/PMDO conformes SkyTemple)
