-- PMU Ground Controller for pmu_s2000 (You Shouldn't Have Done That)
-- Generated by PMU Pipeline (New Era)
local pmu_s2000 = {}

function pmu_s2000.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s2000.Enter(map)
  local music = 'RBY) Lavender Town.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s2000.Update(map, time)
end

return pmu_s2000
