--[[
    Ground Controller: Starter Village (export_test_village)
    Procedurally generated by PMDO Town Generator (Seed: 184729)
]]

require 'origin.common'

local export_test_village = {}

function export_test_village.Init(map)
    DEBUG.EnableDbgCoro()
    PrintInfo("=>> Initializing ground export_test_village")
end

function export_test_village.Enter(map)
    GROUND:Hide('PLAYER')
    local player = CH('PLAYER')
    if player then
        GROUND:TeleportTo(player, 768, 979, Direction.Up)
    end
    GAME:FadeIn(20)
end

function export_test_village.Exit(map)
    GAME:FadeOut(20)
end

return export_test_village
