-- PMU Ground Controller for pmu_s412 (Milly's Grassroot Inn)
-- Generated by PMU Pipeline (New Era)
local pmu_s412 = {}

function pmu_s412.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s412.Enter(map)
  local music = 'PMD2) Goodnight.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s412.Update(map, time)
end

function pmu_s412.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s737', 'Entrance', false)
end

function pmu_s412.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s737', 'Entrance', false)
end

function pmu_s412.Sign_1_Action(obj, activator)
  UI:WaitShowDialogue('Use /sethouse in a bed!')
end

function pmu_s412.Sign_2_Action(obj, activator)
  UI:WaitShowDialogue('Use /sethouse in a bed!')
end

return pmu_s412
