-- PMU Ground Controller for pmu_s1985 (The Skitty Saloon)
-- Generated by PMU Pipeline (New Era)
local pmu_s1985 = {}

function pmu_s1985.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1985.Enter(map)
  local music = 'Anime) Shuppatsu! Koukai he!.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1985.Update(map, time)
end

function pmu_s1985.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1997', 'Entrance', false)
end

function pmu_s1985.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1997', 'Entrance', false)
end

function pmu_s1985.Sign_1_Action(obj, activator)
  UI:WaitShowDialogue('List of Beverages:')
  UI:WaitShowDialogue('Cheri Berri Punch, Chesto Wake-Up Smoothie...')
  UI:WaitShowDialogue('...Leppa Power Shake... -list continues on-.')
end

function pmu_s1985.Sign_2_Action(obj, activator)
  UI:WaitShowDialogue('Welcome to the Skitty Saloon!')
  UI:WaitShowDialogue('Feel free to help yourself to a drink.')
  UI:WaitShowDialogue('And don\'t forget to sit back and relax!')
end

function pmu_s1985.Sign_3_Action(obj, activator)
  UI:WaitShowDialogue('Welcome to the Skitty Saloon!')
  UI:WaitShowDialogue('Feel free to help yourself to a drink.')
  UI:WaitShowDialogue('And don\'t forget to sit back and relax!')
end

return pmu_s1985
