-- PMU Ground Controller for pmu_s1601 (Electrostasis Tower Entrance)
-- Generated by PMU Pipeline (New Era)
local pmu_s1601 = {}

function pmu_s1601.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1601.Enter(map)
  local music = 'PMD2) Battle With Dialga.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1601.Update(map, time)
end

function pmu_s1601.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1602', 'Entrance', false)
end

function pmu_s1601.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1602', 'Entrance', false)
end

return pmu_s1601
