#!/usr/bin/env node
/** Deterministic PMDO-native seasonal packages; no source render is map data. */
import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';import sharp from'sharp';
const ROOT=path.resolve(path.dirname(new URL(import.meta.url).pathname),'../..');
function readPkg(file){const b=fs.readFileSync(file),size=b.readUInt32LE(0),n=b.readUInt32LE(4),m=new Map();for(let i=0;i<n;i++){const p=8+i*16,key=b.readBigUInt64LE(p),off=Number(b.readBigUInt64LE(p+8)),len=Number(b.readBigInt64LE(off));m.set(key,b.subarray(off+8,off+8+len));}return{size,cells:m};}
function key(x,y){return BigInt(x)|(BigInt(y)<<32n)}
function writePkg(file,size,cells){const keys=[...cells.keys()].sort((a,b)=>Number(a>>32n)-Number(b>>32n)||Number(a&0xffffffffn)-Number(b&0xffffffffn)),uniq=new Map(),order=[];for(const k of keys){const p=cells.get(k),h=crypto.createHash('sha256').update(p).digest('hex');if(!uniq.has(h)){uniq.set(h,{p,off:0});order.push(h)}}let off=8+keys.length*16;for(const h of order){uniq.get(h).off=off;off+=8+uniq.get(h).p.length}const out=Buffer.alloc(off);out.writeUInt32LE(size,0);out.writeUInt32LE(keys.length,4);keys.forEach((k,i)=>{const h=crypto.createHash('sha256').update(cells.get(k)).digest('hex'),p=8+i*16;out.writeBigUInt64LE(k,p);out.writeBigUInt64LE(BigInt(uniq.get(h).off),p+8)});for(const h of order){const x=uniq.get(h);out.writeBigInt64LE(BigInt(x.p.length),x.off);x.p.copy(out,x.off+8)}fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,out);return{entries:keys.length,unique:order.length,bytes:out.length,sha256:crypto.createHash('sha256').update(out).digest('hex')}}
async function recolor(input,mode){const {data,info}=await sharp(input).ensureAlpha().raw().toBuffer({resolveWithObject:true});for(let i=0;i<data.length;i+=4){if(!data[i+3])continue;const l=.299*data[i]+.587*data[i+1]+.114*data[i+2];if(mode==='autumn'){data[i]=Math.min(255,l*1.05+35);data[i+1]=Math.min(255,l*.75+30);data[i+2]=Math.min(255,l*.28+12)}else if(mode==='winter'){data[i]=Math.min(255,l*.55+60);data[i+1]=Math.min(255,l*.70+75);data[i+2]=Math.min(255,l*.85+95)}}return sharp(data,{raw:info}).png({compressionLevel:9}).toBuffer()}
async function main(){const town=readPkg(path.join(ROOT,'Content/Tile/TownBase.tile')),build=new Map();for(let y=0;y<32;y++)for(let x=0;x<38;x++){const parts=[];for(let j=0;j<3;j++)for(let i=0;i<3;i++){const p=town.cells.get(key(x*3+i,y*3+j));if(p)parts.push({input:p,left:i*8,top:j*8})}build.set(key(x,y),await sharp({create:{width:24,height:24,channels:4,background:{r:0,g:0,b:0,alpha:0}}}).composite(parts).png({compressionLevel:9}).toBuffer())}
 const results={buildings:writePkg(path.join(ROOT,'Content/Tile/No_Name_Village_Buildings.tile'),24,build)};for(const mode of['autumn','winter']){const cells=new Map();for(const[k,p]of build)cells.set(k,await recolor(p,mode));const name=`No_Name_Village_Buildings_${mode[0].toUpperCase()+mode.slice(1)}`;results['buildings_'+mode]=writePkg(path.join(ROOT,`Content/Tile/${name}.tile`),24,cells)}
 const fullParts=[];for(const[k,p]of town.cells)fullParts.push({input:p,left:Number(k&0xffffffffn)*8,top:Number(k>>32n)*8});const full=await sharp({create:{width:912,height:768,channels:4,background:{r:0,g:0,b:0,alpha:0}}}).composite(fullParts).png().toBuffer();const treeRaw=await sharp(full).extract({left:256,top:248,width:120,height:144}).ensureAlpha().raw().toBuffer({resolveWithObject:true}),td=treeRaw.data,tw=treeRaw.info.width,th=treeRaw.info.height,palette=new Set();const add=(x,y)=>palette.add(`${td[(y*tw+x)*4]},${td[(y*tw+x)*4+1]},${td[(y*tw+x)*4+2]}`);for(let x=0;x<tw;x++){add(x,0);add(x,th-1)}for(let y=0;y<th;y++){add(0,y);add(tw-1,y)}for(let i=0;i<td.length;i+=4)if(palette.has(`${td[i]},${td[i+1]},${td[i+2]}`))td[i+3]=0;
 const seen=new Uint8Array(tw*th),components=[];for(let p=0;p<tw*th;p++){if(seen[p]||!td[p*4+3])continue;const q=[p],c=[];seen[p]=1;while(q.length){const v=q.pop();c.push(v);const x=v%tw,y=Math.floor(v/tw);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const nx=x+dx,ny=y+dy,n=ny*tw+nx;if(nx>=0&&nx<tw&&ny>=0&&ny<th&&!seen[n]&&td[n*4+3]){seen[n]=1;q.push(n)}}}components.push(c)}components.sort((a,b)=>b.length-a.length);const keep=new Uint8Array(tw*th);for(const p of components[0]||[])keep[p]=1;for(let p=0;p<tw*th;p++)if(!keep[p])td[p*4+3]=0;const treeBase=await sharp(td,{raw:treeRaw.info}).png({compressionLevel:9}).toBuffer();for(const mode of['spring','summer','autumn','winter']){const source=(mode==='autumn'||mode==='winter')?await recolor(treeBase,mode):treeBase,cells=new Map();for(let y=0;y<6;y++)for(let x=0;x<5;x++)cells.set(key(x,y),await sharp(source).extract({left:x*24,top:y*24,width:24,height:24}).png({compressionLevel:9}).toBuffer());const name=`No_Name_Village_Standalone_Tree_${mode[0].toUpperCase()+mode.slice(1)}`;results['standalone_'+mode]=writePkg(path.join(ROOT,`Content/Tile/${name}.tile`),24,cells)}
 const forest=readPkg(path.join(ROOT,'Content/Tile/ForestCamp.tile'));for(const mode of['autumn','winter']){const cells=new Map();for(const[k,p]of forest.cells)cells.set(k,await recolor(p,mode));const name=`No_Name_Village_Forest_${mode[0].toUpperCase()+mode.slice(1)}`;results['forest_'+mode]=writePkg(path.join(ROOT,`Content/Tile/${name}.tile`),24,cells)}
 fs.writeFileSync(path.join(ROOT,'NO_NAME_VILLAGE_ADAPTATION/reports/pmd-tile-build.json'),JSON.stringify({schema:'no-name-village.pmd-tile-build.v2',sources:['Content/Tile/TownBase.tile','Content/Tile/ForestCamp.tile'],policy:'PMDO-native buildings, isolated seasonal trees and seamless seasonal forest-canopy derivatives only.',results},null,2)+'\n');console.log(results)}main().catch(e=>{console.error(e);process.exit(1)});
