-- PMU Ground Controller for pmu_s1990 (Boss Rush [Stonecore])
-- Generated by PMU Pipeline (New Era)
local pmu_s1990 = {}

function pmu_s1990.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1990.Enter(map)
  local music = 'BW2) The Tournament is Under Way!.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1990.Update(map, time)
end

function pmu_s1990.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1988', 'Entrance', false)
end

return pmu_s1990
