-- PMU Ground Controller for pmu_s1753 (Tanren Mines B7F)
-- Generated by PMU Pipeline (New Era)
local pmu_s1753 = {}

function pmu_s1753.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1753.Enter(map)
  local music = ''
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1753.Update(map, time)
end

return pmu_s1753
