-- PMU Ground Controller for pmu_s1263 (Sauna Cavern Source)
-- Generated by PMU Pipeline (New Era)
local pmu_s1263 = {}

function pmu_s1263.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1263.Enter(map)
  local music = 'PMD3) Danger!.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1263.Update(map, time)
end

return pmu_s1263
