-- PMU Ground Controller for pmu_s787 (Boggy Wastes [Final Boss])
-- Generated by PMU Pipeline (New Era)
local pmu_s787 = {}

function pmu_s787.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s787.Enter(map)
  local music = 'Colo) Nascour's Theme.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s787.Update(map, time)
end

return pmu_s787
