--[[
    init.lua
    Created: 03/21/2021 22:07:39
    Description: Autogenerated script file for the map metano_electric_home.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'halcyon.PartnerEssentials'
require 'halcyon.ground.metano_electric_home.metano_electric_home_ch_2'
require 'halcyon.ground.metano_electric_home.metano_electric_home_ch_3'
require 'halcyon.ground.metano_electric_home.metano_electric_home_ch_4'
--Le ch5 existe depuis longtemps (2 PNJ, cles MEH5_001/002 traduites) mais
--n'etait pas require : sa table globale restait nil, donc les trois
--dispatch load("metano_electric_home_ch_5.X_Action") echouaient et
--l'assert avortait le callback. Maison vide et muette au chapitre 5.
require 'halcyon.ground.metano_electric_home.metano_electric_home_ch_5'
require 'halcyon.ground.metano_electric_home.metano_electric_home_ch_6'

-- Package name
local metano_electric_home = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---metano_electric_home.Init
--Engine callback function
function metano_electric_home.Init(map, time)
	DEBUG.EnableDbgCoro()
	print('=>> Init_metano_electric_home <<=')
	
	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()
    
	if SOUND:GetCurrentSong() ~= SV.metano_town.Song then
      SOUND:PlayBGM(SV.metano_town.Song, true)
    end
end

---metano_electric_home.Enter
--Engine callback function
function metano_electric_home.Enter(map, time)
	metano_electric_home.PlotScripting()

end

---metano_electric_home.Exit
--Engine callback function
function metano_electric_home.Exit(map, time)


end

---metano_electric_home.Update
--Engine callback function
function metano_electric_home.Update(map, time)


end

function metano_electric_home.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	metano_electric_home.PlotScripting()
end

function metano_electric_home.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end


function metano_electric_home.PlotScripting()
	if SV.ChapterProgression.Chapter == 2 then 
		metano_electric_home_ch_2.SetupGround()
	elseif SV.ChapterProgression.Chapter == 3 then 
		metano_electric_home_ch_3.SetupGround()	
	elseif SV.ChapterProgression.Chapter == 4 then 
		metano_electric_home_ch_4.SetupGround()
	elseif SV.ChapterProgression.Chapter == 5 then
		--Sans cette branche, SetupGround n'etait jamais appele au ch5 :
		--MapChars est vide dans le .rsground, tous les habitants viennent
		--du script. La maison s'ouvrait donc deserte.
		metano_electric_home_ch_5.SetupGround()
	elseif SV.ChapterProgression.Chapter == 6 then
		metano_electric_home_ch_6.SetupGround()
	else
		GAME:FadeIn(20)
	end
end


-------------------------------
-- Map Transitions
-------------------------------

function metano_electric_home.Electric_Home_Entrance_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("metano_town", "Electric_Home_Entrance_Marker", true)
  SV.partner.Spawn = 'Electric_Home_Entrance_Marker_Partner'
end



------------------
--NPCS 
----------------
function metano_electric_home.Electrike_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  assert(pcall(load("metano_electric_home_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Electrike_Action(...,...)"), chara, activator))
end

function metano_electric_home.Luxray_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  assert(pcall(load("metano_electric_home_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Luxray_Action(...,...)"), chara, activator))
end

function metano_electric_home.Manectric_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  assert(pcall(load("metano_electric_home_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Manectric_Action(...,...)"), chara, activator))
end





function metano_electric_home.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))end

return metano_electric_home

