-- PMU Ground Controller for pmu_s1393 (Crystal Castle Entrance)
-- Generated by PMU Pipeline (New Era)
local pmu_s1393 = {}

function pmu_s1393.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1393.Enter(map)
  local music = 'PMD2) Hidden Highland.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1393.Update(map, time)
end

function pmu_s1393.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1991', 'Entrance', false)
end

function pmu_s1393.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1991', 'Entrance', false)
end

function pmu_s1393.Warp_3_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1991', 'Entrance', false)
end

function pmu_s1393.Warp_4_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1991', 'Entrance', false)
end

return pmu_s1393
