--[[
    Ground Controller: Grasstown Style Village (grasstown_style_village)
    Procedurally generated by PMDO Town Generator (Seed: 20260830)
]]

require 'origin.common'

local grasstown_style_village = {}

function grasstown_style_village.Init(map)
    DEBUG.EnableDbgCoro()
    PrintInfo("=>> Initializing ground grasstown_style_village")
end

function grasstown_style_village.Enter(map)
    GROUND:Hide('PLAYER')
    local player = CH('PLAYER')
    if player then
        GROUND:TeleportTo(player, 768, 979, Direction.Up)
    end
    GAME:FadeIn(20)
end

function grasstown_style_village.Exit(map)
    GAME:FadeOut(20)
end

return grasstown_style_village
