-- PMU Ground Controller for pmu_s55 (Loomy's Treasure Trade Market)
-- Generated by PMU Pipeline (New Era)
local pmu_s55 = {}

function pmu_s55.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s55.Enter(map)
  local music = 'Anime) Pokemon Center II.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s55.Update(map, time)
end

function pmu_s55.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1777', 'Entrance', false)
end

function pmu_s55.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1777', 'Entrance', false)
end

function pmu_s55.Warp_3_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1777', 'Entrance', false)
end

return pmu_s55
