--[[
    Ground Controller: Metano Town (Recreated) (metano_town_recreated)
    Procedurally generated by PMDO Town Generator (Seed: 184729)
]]

require 'origin.common'

local metano_town_recreated = {}

function metano_town_recreated.Init(map)
    DEBUG.EnableDbgCoro()
    PrintInfo("=>> Initializing ground metano_town_recreated")
end

function metano_town_recreated.Enter(map)
    GROUND:Hide('PLAYER')
    local player = CH('PLAYER')
    if player then
        GROUND:TeleportTo(player, 756, 1285, Direction.Up)
    end
    GAME:FadeIn(20)
end

function metano_town_recreated.Exit(map)
    GAME:FadeOut(20)
end

return metano_town_recreated
