-- PMU Ground Controller for pmu_s1402 (Iceberg Adrift Base)
-- Generated by PMU Pipeline (New Era)
local pmu_s1402 = {}

function pmu_s1402.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1402.Enter(map)
  local music = 'PMD2) Great Iceberg.mp3'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1402.Update(map, time)
end

function pmu_s1402.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1403', 'Entrance', false)
end

function pmu_s1402.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1403', 'Entrance', false)
end

function pmu_s1402.Warp_3_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s60', 'Entrance', false)
end

return pmu_s1402
