--[[
    init.lua
    Created: 08/22/2025 00:15:20
    Description: Autogenerated script file for the map sentient_workshop.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local sentient_workshop = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---sentient_workshop.Init(zone)
--Engine callback function
function sentient_workshop.Init(zone)


end

---sentient_workshop.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function sentient_workshop.EnterSegment(zone, rescuing, segmentID, mapID)


end

---sentient_workshop.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function sentient_workshop.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---sentient_workshop.Rescued(zone, name, mail)
--Engine callback function
function sentient_workshop.Rescued(zone, name, mail)


end

return sentient_workshop

