-- PMU Ground Controller for pmu_s21 (Pok? Town)
-- Generated by PMU Pipeline (New Era)
local pmu_s21 = {}

function pmu_s21.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s21.Enter(map)
  local music = 'PMD) Pokemon Plaza.mp3'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s21.Update(map, time)
end

function pmu_s21.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s793', 'Entrance', false)
end

function pmu_s21.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s793', 'Entrance', false)
end

function pmu_s21.Warp_3_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s55', 'Entrance', false)
end

function pmu_s21.Sign_1_Action(obj, activator)
  UI:WaitShowDialogue('Come one, come all!')
  UI:WaitShowDialogue('Participate in Wigglytuff\'s Minigame Tent!')
end

function pmu_s21.Sign_2_Action(obj, activator)
  UI:WaitShowDialogue('<--- To the Jail.')
end

function pmu_s21.Sign_3_Action(obj, activator)
  UI:WaitShowDialogue('Winden up ahead.')
end

function pmu_s21.Sign_4_Action(obj, activator)
  UI:WaitShowDialogue('Winden up ahead.')
end

function pmu_s21.Sign_5_Action(obj, activator)
  UI:WaitShowDialogue('Loomy\'s Treasure Exchange')
  UI:WaitShowDialogue('Mushrooms, you say? Bring \'em here!')
end

return pmu_s21
