-- PMU Ground Controller for pmu_s1394 (Crystal Castle Throne)
-- Generated by PMU Pipeline (New Era)
local pmu_s1394 = {}

function pmu_s1394.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1394.Enter(map)
  local music = 'PMD) Frosty Grotto.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1394.Update(map, time)
end

return pmu_s1394
