--[[
    init.lua
    Created: 06/29/2021 10:02:14
    Description: Autogenerated script file for the map guild_guildmasters_room.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'halcyon.PartnerEssentials'
require 'halcyon.ground.guild_guildmasters_room.guild_guildmasters_room_ch_1'
require 'halcyon.ground.guild_guildmasters_room.guild_guildmasters_room_ch_2'
require 'halcyon.ground.guild_guildmasters_room.guild_guildmasters_room_ch_3'
require 'halcyon.ground.guild_guildmasters_room.guild_guildmasters_room_ch_4'
require 'halcyon.ground.guild_guildmasters_room.guild_guildmasters_room_ch_5'
require 'halcyon.ground.guild_guildmasters_room.guild_guildmasters_room_ch_6'

-- Package name
local guild_guildmasters_room = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---guild_guildmasters_room.Init
--Engine callback function
function guild_guildmasters_room.Init(map)
	DEBUG.EnableDbgCoro()
	print('=>> Init_guild_guildmasters_room<<=')
	
	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()
	
	--Remove nicknames from characters if the nickname mod is enabled.
	if CONFIG.UseNicknames() then
		CH('Tropius').Data.Nickname = CharacterEssentials.GetCharacterName('Tropius')
	else 
		CH('Tropius').Data.Nickname = 'Tropius'
	end
end

---guild_guildmasters_room.Enter
--Engine callback function
function guild_guildmasters_room.Enter(map)
	guild_guildmasters_room.PlotScripting()
end

---guild_guildmasters_room.Exit
--Engine callback function
function guild_guildmasters_room.Exit(map)


end

---guild_guildmasters_room.Update
--Engine callback function
function guild_guildmasters_room.Update(map)


end

function guild_guildmasters_room.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	guild_guildmasters_room.PlotScripting()
end

function guild_guildmasters_room.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end

function guild_guildmasters_room.PlotScripting()
	--plot scripting
	if SV.ChapterProgression.Chapter == 1 then
		if SV.Chapter1.TeamCompletedForest then 
			guild_guildmasters_room_ch_1.MeetGuildmaster()
		else
			GAME:FadeIn(20)
		end
	elseif SV.ChapterProgression.Chapter == 2 then 
		if SV.Chapter2.FinishedRiver then 
			guild_guildmasters_room_ch_2.NoctowlTropiusScene()
		else
			GAME:FadeIn(20)
		end
	elseif SV.ChapterProgression.Chapter == 4 then
		if SV.Chapter4.FinishedGrove and not SV.Chapter4.FinishedBedtimeCutscene then
			guild_guildmasters_room_ch_4.PresentApricornCutscene()
		else 
			GAME:FadeIn(20)
		end
	elseif SV.ChapterProgression.Chapter == 5 then
		guild_guildmasters_room_ch_5.SetupGround()
	elseif SV.ChapterProgression.Chapter == 6 then
		--L'AUDIENCE DU RETOUR. Elle ouvre la chambre du maitre pour de bon.
		--Ne se joue qu'une fois : PlayedGuildmasterAudience est pose HORS du
		--pcall de la scene, donc meme une scene ecourtee ne la rejoue pas.
		if SV.Chapter5.FinishedExpedition and not SV.Chapter6.PlayedGuildmasterAudience then
			guild_guildmasters_room_ch_6.GuildmasterAudience()
		else
			guild_guildmasters_room_ch_6.SetupGround()
		end
	else
		GAME:FadeIn(20)
	end
end

---------------------------
-- Map Transitions
---------------------------
--LA PORTE DE LA CHAMBRE. Posee au fond du bureau (160,88), sur le mur
--le plus haut REELLEMENT atteignable : verifie par parcours en largeur
--depuis l'entree du joueur, la bande accessible va de y=96 a y=376, et
--la travee libre a y=96 s'etend de x=136 a x=232. Une porte plus haut
--aurait ete decorative — la zone du fond est isolee par un mur.
--
--Elle suit le verrou du bureau : si on a pu entrer ici, on peut entrer
--dans la chambre. Inutile de verrouiller deux fois la meme progression.
function guild_guildmasters_room.Bedroom_Door_Touch(obj, activator)
  DEBUG.EnableDbgCoro()
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_guildmasters_bedroom", "Main_Entrance_Marker")
  SV.partner.Spawn = 'Default'
end

-------------------------------
-- Entities Callbacks
-------------------------------
--------------------------------------------------------------------
-- ROUTEUR DE DIALOGUE PAR CHAPITRE
--------------------------------------------------------------------
-- Les quatre handlers ci-dessous deleguaient en dur a
-- guild_guildmasters_room_ch_<N>. Or ce fichier n'existe QUE pour les
-- chapitres 1 a 6 : aux chapitres 7 a 10, load() renvoyait nil et le
-- assert() faisait planter le jeu.
--
-- Le bug etait masque jusqu'ici parce que la porte du maitre n'etait
-- jamais franchie apres le ch6. En l'ouvrant pour de bon, on l'aurait
-- rendu atteignable. Reproduit et confirme en Lua avant correction.
--
-- Ce routeur essaie le fichier du chapitre courant ; s'il n'existe pas,
-- il retombe sur le dernier chapitre disponible plutot que de casser.
local DERNIER_CHAPITRE_ECRIT = 6

local function Router(nom, obj, activator)
  DEBUG.EnableDbgCoro()
  local ch = (SV.ChapterProgression and SV.ChapterProgression.Chapter) or 1
  if ch > DERNIER_CHAPITRE_ECRIT then ch = DERNIER_CHAPITRE_ECRIT end

  local fn = load("return guild_guildmasters_room_ch_" .. tostring(ch)
                  .. "." .. nom .. "_Action")
  local ok, cible = pcall(fn)
  if ok and type(cible) == 'function' then
    pcall(cible, obj, activator)
    return
  end

  --Aucun dialogue ecrit pour ce personnage a ce chapitre : on repond
  --quand meme, plutot que de laisser le joueur devant un PNJ muet.
  pcall(function()
    UI:ResetSpeaker(false)
    UI:SetCenter(true)
    UI:WaitShowDialogue("Il est absorbe par ses cartes.[pause=25] Mieux vaut ne pas le deranger.")
    UI:SetCenter(false)
    UI:ResetSpeaker()
  end)
end

function guild_guildmasters_room.Tropius_Action(obj, activator)
  Router('Tropius', obj, activator)
end

function guild_guildmasters_room.Noctowl_Action(obj, activator)
  Router('Noctowl', obj, activator)
end

function guild_guildmasters_room.Breloom_Action(obj, activator)
  Router('Breloom', obj, activator)
end

function guild_guildmasters_room.Girafarig_Action(obj, activator)
  Router('Girafarig', obj, activator)
end







function guild_guildmasters_room.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
end

---------------------------
-- Map Transitions
---------------------------
function guild_guildmasters_room.Bottom_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_third_floor_lobby", "Guild_Third_Floor_Lobby_Door_Marker")
  SV.partner.Spawn = 'Guild_Third_Floor_Lobby_Door_Marker_Partner'
end

return guild_guildmasters_room

