--[[
    Ground Controller: Starter Village (test_starter_village)
    Procedurally generated by PMDO Town Generator (Seed: 184729)
]]

require 'origin.common'

local test_starter_village = {}

function test_starter_village.Init(map)
    DEBUG.EnableDbgCoro()
    PrintInfo("=>> Initializing ground test_starter_village")
end

function test_starter_village.Enter(map)
    GROUND:Hide('PLAYER')
    local player = CH('PLAYER')
    if player then
        GROUND:TeleportTo(player, 768, 979, Direction.Up)
    end
    GAME:FadeIn(20)
end

function test_starter_village.Exit(map)
    GAME:FadeOut(20)
end

return test_starter_village
