--[[
    D55P11A_n06a3908.lua — ARC DU FUTUR (adaptation New Era)
    Source canonique : pret/pmd-sky files/language-specific/US/SCRIPT/D55P11A/n06a3908.ssb
    Généré par tools/ssb_to_lua.py — IR canonique + couche d'adaptation New Era.
    Chorégraphie 1:1 (déplacements, positions, timings, animations, caméra,
    fades, SFX, BGM, transitions, flags, embranchements). Seul le CAST change :
    Dusknoir/Grovyle (alliés), Sableye (sbires de Necrozma), Celebi, héros/
    partenaire ; le maître du futur = Necrozma (Dialga absent). Les dialogues
    canoniques sont joués (cast appliqué), la clé FUT_* en commentaire sert
    d'éventuelle passe FR. Les tables anim/SE/effets manquantes sont marquées
    TODO (jamais inventées).
]]
require 'origin.common'
require 'halcyon.GeneralFunctions'
require 'halcyon.BossFX'

local n06a3908 = {}

function n06a3908.Cutscene()
  DEBUG.EnableDbgCoro()
  local ok, err = pcall(function()
    GAME:CutsceneMode(true)

        -- PARTIEL : sound_Stop []
        -- back_SetGround(D55P11A) : ground courant déjà posé
        -- supervision_tationCommon layer [0] (structurel)
        -- supervision_cting layer [1] (structurel)
        -- supervision_cting layer [0] (structurel)
        -- supervision_emoveActing layer [1] (structurel)
        -- NON CONVERTI : WaitLockLives [5, 9]
        -- NON CONVERTI : WaitLockLives [10, 112]
        -- NON CONVERTI : WaitLockLives [15, 191]
        -- performer 0
        -- camera_SetMyself : la caméra suit le héros (défaut PMDO)
        GAME:FadeIn(30)
        -- bgm_PlayFadeIn [145, 0, 256] : BGM RandomDungeonTheme3 non mappé
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' By the way, we\'re not finished\nwith you.') -- FUT_N06A3908_001 (FR optionnel)
        UI:SetCenter(false)
        UI:SetCenter(true)
        UI:WaitShowDialogue(' The next time we see you...\n\nWe\'re not going to go easy on you...') -- FUT_N06A3908_002 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : Turn2Direction (acteur NPC_MANYUURA)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Arbok! Drapion!\n\nLet\'s go!') -- FUT_N06A3908_003 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : MovePositionMark (acteur NPC_MANYUURA)
        -- performer 0
        GROUND:MoveToPosition(CH('PLAYER'), 276, 304, false, 2.0)
        GAME:WaitFrames(45)
        -- NON CONVERTI : MovePositionMark (acteur NPC_AABOKKU)
        GAME:WaitFrames(45)
        -- NON CONVERTI : MovePositionMark (acteur NPC_DORAPION)
        -- NON CONVERTI : Turn2Direction (acteur NPC_AABOKKU)
        -- NON CONVERTI : Turn2Direction (acteur NPC_DORAPION)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Next time, we\'ll beat you up!') -- FUT_N06A3908_004 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Remember that!') -- FUT_N06A3908_005 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : MovePositionMark (acteur NPC_AABOKKU)
        GAME:WaitFrames(45)
        -- NON CONVERTI : MovePositionMark (acteur NPC_DORAPION)
        GAME:WaitFrames(20)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Hee-hee!\n\nIt\'s a date! [M:H8]') -- FUT_N06A3908_006 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- performer 0
        GROUND:MoveToPosition(CH('PLAYER'), 276, 236, false, 2.0)
        GAME:WaitFrames(15)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Worried')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Phew...\n So the treasure here\nwas just the Time Gear...') -- FUT_N06A3908_007 (FR optionnel)
        UI:SetCenter(false)
        -- NON CONVERTI : Unlock [15]
        -- NON CONVERTI : Unlock [5]
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Up until now we\'ve gotten every\ntreasure we\'ve aimed for...') -- FUT_N06A3908_008 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : Unlock [10]
        -- NON CONVERTI : WaitLockLives [11, 112]
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Worried')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Yeah...\n This time we\'ve found\nsomething even we can\'t take...') -- FUT_N06A3908_009 (FR optionnel)
        UI:SetCenter(false)
        UI:SetCenter(true)
        UI:WaitShowDialogue(' No way...') -- FUT_N06A3908_010 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : WaitLockLives [16, 191]
        -- NON CONVERTI : WaitLockLives [6, 9]
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' It has to be this way.') -- FUT_N06A3908_011 (FR optionnel)
        UI:SetCenter(false)
        UI:SetCenter(true)
        UI:WaitShowDialogue(' There are some things in this\nworld that you just can\'t take.') -- FUT_N06A3908_012 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Even though we can\'t take the\ntreasure with us, I\'d call this a success.\nWouldn\'t you?') -- FUT_N06A3908_013 (FR optionnel)
        UI:SetCenter(false)
        UI:SetCenter(true)
        UI:WaitShowDialogue(' We even had a more than fair\nfight against the villainous Team AWD.') -- FUT_N06A3908_014 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : Unlock [11]
        SOUND:PlayBattleSE('EVT_Emote_Exclaim') -- SE 8978 (SE_NUM_EVENT_SIGN_NOTICE_05)
        -- NON CONVERTI : WaitLockLives [12, 112]
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Oh! That\'s right!') -- FUT_N06A3908_015 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Besides, that beautiful and\nprecious Time Gear...') -- FUT_N06A3908_016 (FR optionnel)
        UI:SetCenter(false)
        UI:SetCenter(true)
        UI:WaitShowDialogue(' We saw one for the first time,\ndidn\'t we?!') -- FUT_N06A3908_017 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Oh yeah!\n That\'s right!') -- FUT_N06A3908_018 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Yep. ♪ That\'s right! ♪') -- FUT_N06A3908_019 (FR optionnel)
        UI:SetCenter(false)
        -- NON CONVERTI : Unlock [12]
        -- NON CONVERTI : WaitLockLives [13, 112]
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' And we made it successfully\nthrough the maze that has stumped so many\nothers before us...') -- FUT_N06A3908_020 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' I knew it. ♪ We are...\nthe best,\naren\'t we? [M:H8]') -- FUT_N06A3908_021 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : Unlock [6]
        -- NON CONVERTI : Unlock [13]
        -- NON CONVERTI : Unlock [16]
        GAME:WaitFrames(6)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Uwahahahahaha!') -- FUT_N06A3908_022 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Uhuhuhuhuhuhu!') -- FUT_N06A3908_023 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Hah-hah-hah! Hah-hah-hah!') -- FUT_N06A3908_024 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        pcall(function() SOUND:PlayBattleSE('SSB_SE_8961') end) -- TODO SE 8961 (SE_NUM_EVENT_SIGN_ASE_01)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Um...\n That\'s great everyone. ♪') -- FUT_N06A3908_025 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : flag_CalcValue [92, 0, 1]
        -- NON CONVERTI : WaitLockLives [7, 9]
        -- NON CONVERTI : WaitLockLives [14, 112]
        -- NON CONVERTI : WaitLockLives [17, 191]
        -- (parallèle) NPC_CHAAREMU, NPC_SAANAITO
        TASK:JoinCoroutines({
            function()
                -- NON CONVERTI : MovePositionOffset (acteur NPC_SAANAITO)
                -- NON CONVERTI : Turn2DirectionLives (acteur NPC_SAANAITO)
            end,
            function()
                -- NON CONVERTI : MovePositionOffset (acteur NPC_CHAAREMU)
            end,
        })
        GAME:WaitFrames(3)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_CHAAREMU)
        GAME:WaitFrames(3)
        -- NON CONVERTI : Turn2DirectionLives (acteur PLAYER_CHARMS)
        GAME:WaitFrames(15)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Well, I\'m headed home now.') -- FUT_N06A3908_026 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_SAANAITO)
        GAME:WaitFrames(3)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_CHAAREMU)
        SOUND:FadeOutBGM(150)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Gardevoir, Medicham.') -- FUT_N06A3908_027 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Yes.') -- FUT_N06A3908_028 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Got it.') -- FUT_N06A3908_029 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_SAANAITO)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_CHAAREMU)
        GAME:WaitFrames(10)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        GAME:WaitFrames(20)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        GAME:WaitFrames(20)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        GAME:WaitFrames(15)
        SOUND:PlayBattleSE('EVT_Emote_Startled') -- SE 8962 (SE_NUM_EVENT_SIGN_HATENA_02)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Huh?\n What\'s with everyone?') -- FUT_N06A3908_030 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Wigglytuff.\n You\'re not half bad!') -- FUT_N06A3908_031 (FR optionnel)
        UI:SetCenter(false)
        UI:SetCenter(true)
        UI:WaitShowDialogue(' We\'ve got a better opinion of\nyou now!') -- FUT_N06A3908_032 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Huh?') -- FUT_N06A3908_033 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' You saw through Ditto\'s\ntreasure-chest disguise...') -- FUT_N06A3908_034 (FR optionnel)
        UI:SetCenter(false)
        UI:SetCenter(true)
        UI:WaitShowDialogue(' You\'re really cool!') -- FUT_N06A3908_035 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' I-is that so...?\n I see...') -- FUT_N06A3908_036 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Hee-hee-hee-hee...') -- FUT_N06A3908_037 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' So...\n What will you do next,\nWigglytuff?') -- FUT_N06A3908_038 (FR optionnel)
        UI:SetCenter(false)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Huh?\n Next?') -- FUT_N06A3908_039 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Yes, next. ♪') -- FUT_N06A3908_040 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Worried')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' I wonder...\n I don\'t really have\nany plans...') -- FUT_N06A3908_041 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Well, if you\'d like...\nyou could\nalways come explore with us?') -- FUT_N06A3908_042 (FR optionnel)
        UI:SetCenter(false)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' With you?') -- FUT_N06A3908_043 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Yes, with us.\n What do you think?') -- FUT_N06A3908_044 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Worried')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Hmmm...\n What should I do...?') -- FUT_N06A3908_045 (FR optionnel)
        UI:SetCenter(false)
        UI:SetCenter(true)
        UI:WaitShowDialogue(' It would be fun exploring\nwith you...') -- FUT_N06A3908_046 (FR optionnel)
        UI:SetCenter(false)
        UI:SetCenter(true)
        UI:WaitShowDialogue(' But I\'ve never explored with\nanyone other than my master...') -- FUT_N06A3908_047 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_SAANAITO)
        GAME:WaitFrames(4)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_CHAAREMU)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Lopunny. That thing...') -- FUT_N06A3908_048 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : Turn2DirectionLives (acteur PLAYER_CHARMS)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' I\'m on it, Gardevoir.') -- FUT_N06A3908_049 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : Turn2DirectionLives (acteur PLAYER_CHARMS)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_SAANAITO)
        GAME:WaitFrames(6)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_CHAAREMU)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Hey, ummm... ♪\nWigglytuff. [M:H8]') -- FUT_N06A3908_050 (FR optionnel)
        UI:SetCenter(false)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        UI:SetCenter(true)
        UI:WaitShowDialogue(' If you were to come exploring\nwith us...') -- FUT_N06A3908_051 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : Turn2Direction (acteur PLAYER_CHARMS)
        GAME:WaitFrames(6)
        -- NON CONVERTI : MovePositionOffset (acteur PLAYER_CHARMS)
        pcall(function() SOUND:PlayBattleSE('SSB_SE_6410') end) -- TODO SE 6410 (None)
        -- supervision_cting layer [1] (structurel)
        -- object 128 (p03p02a1) : contexte objet
        local obj_128 = OBJ('p03p02a1') -- objet 128
        GROUND:ObjectSetAnim(obj_128, 9, 0, 3, Direction.Down, 1) -- anim 9 (table REQUISE)
        GAME:WaitFrames(15)
        -- NON CONVERTI : SetAnimation (acteur PLAYER_CHARMS)
        -- NON CONVERTI : SlidePositionOffset (acteur PLAYER_CHARMS)
        -- NON CONVERTI : SetAnimation (acteur PLAYER_CHARMS)
        GAME:WaitFrames(15)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' We could give you this. Would\nyou like that? [M:H8]') -- FUT_N06A3908_052 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        SOUND:PlayBattleSE('EVT_Emote_Exclaim') -- SE 8978 (SE_NUM_EVENT_SIGN_NOTICE_05)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Surprised')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Oooh!') -- FUT_N06A3908_053 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- ExecuteCommon(JUMP_HAPPY_FUNC_SERIES) : gestuelle parallèle à implémenter
        -- NON CONVERTI : SetAnimation (acteur NPC_PUKURIN)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Sigh')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' I-it\'s a...\nPerfect Apple! ♪') -- FUT_N06A3908_054 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' But...') -- FUT_N06A3908_055 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : MovePositionOffset (acteur PLAYER_CHARMS)
        pcall(function() SOUND:PlayBattleSE('SSB_SE_8710') end) -- TODO SE 8710 (None)
        GAME:WaitFrames(9)
        -- supervision_emoveActing layer [1] (structurel)
        GAME:WaitFrames(9)
        -- (parallèle) NPC_PUKURIN, PLAYER_CHARMS
        TASK:JoinCoroutines({
            function()
                -- NON CONVERTI : SetAnimation (acteur NPC_PUKURIN)
            end,
            function()
                -- NON CONVERTI : SetAnimation (acteur PLAYER_CHARMS)
                -- NON CONVERTI : SlidePositionOffset (acteur PLAYER_CHARMS)
            end,
        })
        -- NON CONVERTI : SetAnimation (acteur PLAYER_CHARMS)
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Happy')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' I haven\'t decided if I\'m giving it\nto you yet. ♪') -- FUT_N06A3908_056 (FR optionnel)
        UI:SetCenter(false)
        SOUND:PlayBattleSE('EVT_Emote_Shock_2') -- SE 8968 (SE_NUM_EVENT_SIGN_SHOCK_01)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetAnimation (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        UI:ResetSpeaker()
        -- bgm_PlayFadeIn [165, 0, 256] : BGM TeamCharmsTheme non mappé
        -- NON CONVERTI : message_SetWaitMode [180, 90]
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Let\'s get something straight...\n\nWe\'re all pretty fast moving.') -- FUT_N06A3908_057 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : message_SetWaitMode [210, 60]
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Do you think you could keep up\nwith us?') -- FUT_N06A3908_058 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : message_SetWaitMode [120, 60]
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Normal')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' What do you think?\n\nHow about a race?') -- FUT_N06A3908_059 (FR optionnel)
        UI:SetCenter(false)
        -- message_KeyWait (le dialogue bloque déjà)
        -- NON CONVERTI : message_SetWaitMode [45, 45]
        UI:SetCenter(true)
        UI:WaitShowDialogue(' 3...\n 2...\n 1...\n GO!') -- FUT_N06A3908_060 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : SetAnimation (acteur PLAYER_CHARMS)
        -- NON CONVERTI : SlidePositionMark (acteur PLAYER_CHARMS)
        GAME:WaitFrames(6)
        -- NON CONVERTI : SetAnimation (acteur NPC_CHAAREMU)
        -- NON CONVERTI : SlidePositionMark (acteur NPC_CHAAREMU)
        GAME:WaitFrames(6)
        -- NON CONVERTI : SetAnimation (acteur NPC_SAANAITO)
        -- NON CONVERTI : SlidePositionMark (acteur NPC_SAANAITO)
        GAME:WaitFrames(6)
        -- NON CONVERTI : WaitAnimation (acteur PLAYER_CHARMS)
        -- (parallèle) NPC_CHAAREMU, PLAYER_CHARMS
        TASK:JoinCoroutines({
            function()
                -- NON CONVERTI : SetAnimation (acteur PLAYER_CHARMS)
                -- NON CONVERTI : SlidePositionMark (acteur PLAYER_CHARMS)
            end,
            function()
                -- NON CONVERTI : WaitAnimation (acteur NPC_CHAAREMU)
                -- NON CONVERTI : SetAnimation (acteur NPC_CHAAREMU)
            end,
        })
        -- (parallèle) NPC_CHAAREMU, NPC_SAANAITO
        TASK:JoinCoroutines({
            function()
                -- NON CONVERTI : SlidePositionMark (acteur NPC_CHAAREMU)
            end,
            function()
                -- NON CONVERTI : WaitAnimation (acteur NPC_SAANAITO)
                -- NON CONVERTI : SetAnimation (acteur NPC_SAANAITO)
            end,
        })
        -- NON CONVERTI : SlidePositionMark (acteur NPC_SAANAITO)
        GAME:WaitFrames(30)
        -- ExecuteCommon(JUMP_HAPPY_FUNC_SERIES) : gestuelle parallèle à implémenter
        -- NON CONVERTI : message_SetWaitMode [90, 45]
        UI:ResetSpeaker()
        GeneralFunctions.SetEmotion('Sigh')
        UI:SetCenter(true)
        UI:WaitShowDialogue(' Yay!\n GO! GO!') -- FUT_N06A3908_061 (FR optionnel)
        UI:SetCenter(false)
        UI:ResetSpeaker()
        -- NON CONVERTI : MovePositionMark (acteur NPC_PUKURIN)
        GAME:WaitFrames(30)
        GAME:FadeOut(false, 30)
        GAME:WaitFrames(40)
        -- NON CONVERTI : message_SetWaitMode [150, 60]
        -- NON CONVERTI : message_Explanation [61]
        -- NON CONVERTI : message_Explanation [62]
        UI:ResetSpeaker()
        -- NON CONVERTI : message_SetWaitMode [32767, 32767]
        GAME:FadeOut(false, 30)
        GAME:WaitFrames(20)
        -- End : fin de scène
        -- NON CONVERTI : Lock [5]
        -- NON CONVERTI : SetAnimation (acteur NPC_PUKURIN)
        GAME:WaitFrames(6)
        -- NON CONVERTI : Lock [6]
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        GAME:WaitFrames(6)
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [18, 21]
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [12, 30]
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [18, 21]
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : Turn2Direction (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- CallCommon(JUMP_HAPPY_FUNC) : helper à implémenter
        -- NON CONVERTI : WaitRandom [12, 30]
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- CallCommon(JUMP_HAPPY_FUNC) : helper à implémenter
        -- Switch (structurel)
        -- Case (structurel)
        -- Jump (structurel)
        -- NON CONVERTI : Lock [7]
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- Hold : NON CONVERTI (pause maintenue, pas d'équivalent PMDO)
        -- NON CONVERTI : SetPositionInitial []
        -- NON CONVERTI : Lock [10]
        -- NON CONVERTI : Lock [11]
        -- NON CONVERTI : Lock [12]
        -- NON CONVERTI : Lock [13]
        -- NON CONVERTI : SetAnimation (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetAnimation (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitAnimation (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetAnimation (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : MovePositionOffset (acteur NPC_PUKURIN)
        GAME:WaitFrames(20)
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [12, 30]
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [18, 24]
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- CallCommon(JUMP_HAPPY_FUNC) : helper à implémenter
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [12, 30]
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [18, 24]
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- CallCommon(JUMP_HAPPY_FUNC) : helper à implémenter
        -- Switch (structurel)
        -- Case (structurel)
        -- Jump (structurel)
        -- NON CONVERTI : Lock [14]
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- Hold : NON CONVERTI (pause maintenue, pas d'équivalent PMDO)
        -- NON CONVERTI : SetPositionInitial []
        -- NON CONVERTI : Lock [15]
        -- NON CONVERTI : Lock [16]
        -- NON CONVERTI : SetAnimation (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        GAME:WaitFrames(15)
        -- NON CONVERTI : MovePositionOffset (acteur NPC_PUKURIN)
        GAME:WaitFrames(2)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        GAME:WaitFrames(9)
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [18, 21]
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [12, 27]
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [18, 21]
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- CallCommon(JUMP_HAPPY_FUNC) : helper à implémenter
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [12, 27]
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [18, 21]
        -- Switch (structurel)
        -- Case (structurel)
        -- NON CONVERTI : WaitRandom [12, 27]
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : Turn2DirectionLives (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : WaitEffect (acteur NPC_PUKURIN)
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- CallCommon(JUMP_HAPPY_FUNC) : helper à implémenter
        -- Switch (structurel)
        -- Case (structurel)
        -- Jump (structurel)
        -- NON CONVERTI : Lock [17]
        -- NON CONVERTI : SetEffect (acteur NPC_PUKURIN)
        -- Hold : NON CONVERTI (pause maintenue, pas d'équivalent PMDO)

    GAME:CutsceneMode(false)
  end)
  if not ok then PrintInfo('[n06a3908] scène interrompue : '..tostring(err)) end
end

return n06a3908
