-- PMU Ground Controller for pmu_s1244 (Grassroot Bazaar)
-- Generated by PMU Pipeline (New Era)
local pmu_s1244 = {}

function pmu_s1244.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1244.Enter(map)
  local music = 'PMD3) Kecleon Shop.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1244.Update(map, time)
end

function pmu_s1244.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s737', 'Entrance', false)
end

return pmu_s1244
