-- PMU Ground Controller for pmu_s1249 (Sauna Cave Rest Point)
-- Generated by PMU Pipeline (New Era)
local pmu_s1249 = {}

function pmu_s1249.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1249.Enter(map)
  local music = 'PMD) At the End of the Road.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1249.Update(map, time)
end

return pmu_s1249
