-- PMU Ground Controller for pmu_s1362 (Southern Sea Trench)
-- Generated by PMU Pipeline (New Era)
local pmu_s1362 = {}

function pmu_s1362.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1362.Enter(map)
  local music = 'Colo) Pyrite Building.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1362.Update(map, time)
end

return pmu_s1362
