-- PMU Ground Controller for pmu_s737 (Exbel, Grassroot Town)
-- Generated by PMU Pipeline (New Era)
local pmu_s737 = {}

function pmu_s737.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s737.Enter(map)
  local music = 'PMD3) So Come! Post Town.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s737.Update(map, time)
end

function pmu_s737.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s50', 'Entrance', false)
end

function pmu_s737.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1144', 'Entrance', false)
end

function pmu_s737.Warp_3_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1143', 'Entrance', false)
end

function pmu_s737.Warp_4_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1146', 'Entrance', false)
end

function pmu_s737.Warp_5_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1145', 'Entrance', false)
end

function pmu_s737.Warp_6_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1777', 'Entrance', false)
end

function pmu_s737.Warp_7_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1000', 'Entrance', false)
end

function pmu_s737.Warp_8_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s793', 'Entrance', false)
end

function pmu_s737.Warp_9_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s793', 'Entrance', false)
end

function pmu_s737.Warp_10_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1142', 'Entrance', false)
end

function pmu_s737.Warp_11_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1244', 'Entrance', false)
end

function pmu_s737.Warp_12_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s412', 'Entrance', false)
end

function pmu_s737.Sign_1_Action(obj, activator)
  UI:WaitShowDialogue('Leavi and Bulby\'s House')
end

function pmu_s737.Sign_2_Action(obj, activator)
  UI:WaitShowDialogue('Rustle\'s House')
end

function pmu_s737.Sign_3_Action(obj, activator)
  UI:WaitShowDialogue('Lark\'s House')
end

function pmu_s737.Sign_4_Action(obj, activator)
  UI:WaitShowDialogue('Trishian\'s House')
end

function pmu_s737.Sign_5_Action(obj, activator)
  UI:WaitShowDialogue('Basic House Commands:~')
  UI:WaitShowDialogue('- "/edithouse" Opens the Map Editor to edit your own house. "/houseentrance" Sets the spawn point of your house when you visit it. "/housesign" Adds a sign on the tile you are standing on. "/housesound" Places a Sound Tile that plays a sound effect on the tile you are standing on. ')
  UI:WaitShowDialogue('"/houselight" Changes the Light/Dark settings of the house. "/houseroof" Opens the roof of the house to set weather conditions and allow the change of time. "/houseweather" Sets the house weather. "/housexpand" Expands the house size.')
end

function pmu_s737.Sign_6_Action(obj, activator)
  UI:WaitShowDialogue('Eevee Family House')
end

function pmu_s737.Sign_7_Action(obj, activator)
  UI:WaitShowDialogue('Grassroot Bazaar')
  UI:WaitShowDialogue('Need your boxes unsealed, need your items cleansed, need your eggs to be homed?')
  UI:WaitShowDialogue('You are at the right place!')
end

function pmu_s737.Sign_8_Action(obj, activator)
  UI:WaitShowDialogue('Grassroot Bazaar')
  UI:WaitShowDialogue('Need your boxes unsealed, need your items cleansed, need your eggs to be homed?')
  UI:WaitShowDialogue('You are at the right place!')
end

function pmu_s737.Sign_9_Action(obj, activator)
  UI:WaitShowDialogue('Welcome to Grassroot Town.')
  UI:WaitShowDialogue('The root of all beginnings.')
end

function pmu_s737.Sign_10_Action(obj, activator)
  UI:WaitShowDialogue('Welcome to Grassroot Town.')
  UI:WaitShowDialogue('The root of all beginnings.')
end

function pmu_s737.Sign_11_Action(obj, activator)
  UI:WaitShowDialogue('Kangaskhan\'s Storage')
end

function pmu_s737.Sign_12_Action(obj, activator)
  UI:WaitShowDialogue('Chimecho\'s Assembly')
end

function pmu_s737.Sign_13_Action(obj, activator)
  UI:WaitShowDialogue('Milly\'s Grassroot Inn')
end

return pmu_s737
