--[[
    init.lua
    Created: 08/30/2025 12:53:38
    Description: Autogenerated script file for the map coven_cave.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local coven_cave = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---coven_cave.Init(zone)
--Engine callback function
function coven_cave.Init(zone)


end

---coven_cave.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function coven_cave.EnterSegment(zone, rescuing, segmentID, mapID)


end

---coven_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function coven_cave.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---coven_cave.Rescued(zone, name, mail)
--Engine callback function
function coven_cave.Rescued(zone, name, mail)


end

return coven_cave

