--- Scene: d03p01
local d03p01 = {}
function d03p01.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('Mt Steel', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D03P01_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D03P01_002"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D03P01_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D03P01_004"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  GAME:PlayBGM('Mt Steel', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D03P01_005"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D03P01_006"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D03P01_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D03P01_008"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  GAME:CutsceneMode(false)
end
return d03p01
