--- Scene: d05p02
local d05p02 = {}
function d05p02.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('In The Depths Of The Pit', true)
  GAME:FadeOutBGM(60)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_002"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_005"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_006"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_008"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_011"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_012"))
  GAME:FadeOut(true, 2)
  GAME:FadeIn(3)
  GAME:FadeOut(true, 2)
  GAME:FadeIn(3)
  GAME:FadeOut(true, 4)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_013"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_014"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_015"))
  GAME:FadeIn(2)
  GAME:FadeOut(true, 2)
  GAME:FadeIn(2)
  GAME:FadeOut(true, 2)
  GAME:FadeOut(true, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_016"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_017"))
  GAME:FadeIn(2)
  GAME:FadeOut(true, 2)
  GAME:FadeIn(2)
  GAME:FadeOut(true, 2)
  GAME:FadeOut(true, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_018"))
  GAME:FadeIn(32)
  GAME:FadeOut(true, 16)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_019"))
  GAME:FadeIn(16)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_020"))
  GAME:PlayBGM('Rising Fear', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_021"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_022"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_023"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_024"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D05P02_025"))
  GAME:CutsceneMode(false)
end
return d05p02
