--- Scene: d06p03
local d06p03 = {}
function d06p03.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('In The Depths Of The Pit', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_002"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_005"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_006"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_008"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_011"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_012"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_013"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_014"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_015"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_016"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_017"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_018"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_019"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_020"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_021"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_022"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_023"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_024"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_025"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_026"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_027"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_028"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_029"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_030"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_031"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_032"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_033"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_034"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_035"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_036"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_037"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_038"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_039"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_040"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_041"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_042"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_043"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_044"))
  GAME:FadeOutBGM(120)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_045"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_046"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_047"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_048"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D06P03_049"))
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  GAME:CutsceneMode(false)
end
return d06p03
