--- Scene: d08p01
local d08p01 = {}
function d08p01.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('Lapis Cave', true)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('The Escape', true)
  -- GROUND:CharSetAction(ent, 2)
  GAME:FadeOutBGM(30)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_001"))
  GAME:PlayBGM('Lapis Cave', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_002"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_005"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_006"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_008"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_009"))
  -- CAMERA_PAN(256, 2),
  -- GROUND:CharSetAction(ent, 2)
  -- CAMERA_PAN(256, 2),
  GAME:PlayBGM('Lapis Cave', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_011"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_012"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_013"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_014"))
  GAME:FadeOutBGM(60)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Lapis Cave', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_015"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_016"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Lapis Cave', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_017"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D08P01_018"))
  GAME:CutsceneMode(false)
end
return d08p01
