--- Scene: d09p01
local d09p01 = {}
function d09p01.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('Mt Blaze', true)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_002"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_005"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_006"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_008"))
  GAME:PlayBGM('Mt Blaze', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_011"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_012"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_013"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_014"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_015"))
  GAME:FadeOutBGM(60)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Mt Blaze', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_016"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_017"))
  -- CAMERA_PAN(512, 7),
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_018"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_019"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_020"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_021"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_022"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_023"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_024"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_025"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_026"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_027"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_028"))
  -- CAMERA_PAN(512, 9),
  GAME:PlayBGM('Mt Blaze', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_029"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_030"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Mt Blaze', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_031"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D09P01_032"))
  GAME:CutsceneMode(false)
end
return d09p01
