--- Scene: d11p01
local d11p01 = {}
function d11p01.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('Escape Through The Snow', true)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Escape Through The Snow', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_002"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_005"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_006"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_008"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_011"))
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_012"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_013"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_014"))
  GAME:FadeOutBGM(120)
  -- CAMERA_PAN(256, 0),
  GAME:FadeOutBGM(120)
  -- CAMERA_PAN(256, 0),
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_015"))
  GAME:FadeOutBGM(120)
  -- CAMERA_PAN(256, 0),
  GAME:FadeOutBGM(120)
  -- CAMERA_PAN(256, 0),
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- CAMERA_PAN(256, 0),
  -- GROUND:CharSetAction(ent, 5)
  -- CAMERA_PAN(256, 0),
  GAME:PlayBGM('Escape Through The Snow', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_016"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_017"))
  GAME:PlayBGM('Escape Through The Snow', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_018"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_019"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Escape Through The Snow', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_020"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_021"))
  GAME:PlayBGM('Mt Freeze', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_022"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D11P01_023"))
  -- GROUND:CharSetAction(ent, 2)
  -- CAMERA_PAN(256, 1),
  GAME:CutsceneMode(false)
end
return d11p01
