--- Scene: d13p03
local d13p03 = {}
function d13p03.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('Rayquazas Domain', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_001"))
  GAME:FadeOut(true, 8)
  GAME:FadeIn(8)
  GAME:FadeOut(true, 8)
  GAME:FadeIn(8)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_002"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  GAME:FadeOut(true, 30)
  GAME:FadeIn(16)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_005"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 23)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_006"))
  GAME:FadeOut(true, 8)
  GAME:FadeIn(8)
  -- GROUND:CharSetAction(ent, 24)
  GAME:FadeOut(true, 4)
  GAME:FadeIn(4)
  -- GROUND:CharSetAction(ent, 25)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rayquazas Domain', true)
  GAME:FadeOut(true, 16)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_008"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_011"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_012"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_013"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_014"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_015"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_016"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_017"))
  GAME:FadeOutBGM(120)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_018"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 24)
  GAME:PlayBGM('Rayquazas Domain', true)
  GAME:FadeIn(16)
  GAME:FadeOutBGM(60)
  GAME:FadeOut(true, 60)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D13P03_019"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:CutsceneMode(false)
end
return d13p03
