--- Scene: d17p01
local d17p01 = {}
function d17p01.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('In The Depths Of The Pit', true)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 2)
  GAME:FadeOut(true, 5)
  GAME:FadeIn(5)
  GAME:FadeOut(true, 5)
  GAME:FadeIn(5)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_002"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_005"))
  GAME:FadeOutBGM(30)
  GAME:FadeOut(true, 3)
  GAME:FadeIn(3)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_006"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_007"))
  GAME:FadeOut(true, 60)
  GAME:FadeIn(60)
  GAME:PlayBGM('In The Depths Of The Pit', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_008"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_011"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_012"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_013"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_014"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_015"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D17P01_016"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  GAME:CutsceneMode(false)
end
return d17p01
