--[[
    init.lua
    Created: 02/07/2021 21:52:45
    Description: Autogenerated script file for the map metano_cafe.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'halcyon.PartnerEssentials'
require 'halcyon.GeneralFunctions'
require 'halcyon.CharacterEssentials'
require 'halcyon.ground.metano_cafe.metano_cafe_ch_3'
require 'halcyon.ground.metano_cafe.metano_cafe_ch_4'
require 'halcyon.ground.metano_cafe.metano_cafe_ch_5'
require 'halcyon.ground.metano_cafe.metano_cafe_ch_6'
require 'halcyon.menu.ferment_menu'
require 'halcyon.menu.single_deal_menu'
-- Package name
local metano_cafe = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---metano_cafe.Init
--Engine callback function
function metano_cafe.Init(map, time)
	DEBUG.EnableDbgCoro()
	print('=>> Init_metano_cafe <<=')
	
	COMMON.RespawnAllies(true)
	PartnerEssentials.InitializePartnerSpawn()
	
	--Remove nicknames from characters if the nickname mod is enabled.
	if CONFIG.UseNicknames() then
		CH('Cafe_Owner').Data.Nickname = CharacterEssentials.GetCharacterName('Shuckle')
	else 
		CH('Cafe_Owner').Data.Nickname = 'Shuckle'
	end
end

---metano_cafe.Enter
--Engine callback function
function metano_cafe.Enter(map, time)
	metano_cafe.PlotScripting()
end

---metano_cafe.Update
--Engine callback function
function metano_cafe.Update(map, time)
	

end

function metano_cafe.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	metano_cafe.PlotScripting()
end

function metano_cafe.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end

function metano_cafe.PlotScripting()
	if SV.ChapterProgression.Chapter == 3 then
		metano_cafe_ch_3.SetupGround()
	elseif SV.ChapterProgression.Chapter == 4 then
		metano_cafe_ch_4.SetupGround()	
	elseif SV.ChapterProgression.Chapter == 5 then
		metano_cafe_ch_5.SetupGround()
	elseif SV.ChapterProgression.Chapter == 6 then
		metano_cafe_ch_6.SetupGround()
	else 
		GAME:FadeIn(20)
	end 
	pcall(function() metano_cafe.PlayDailyCutscene() end)
end

-------------------------------
-- Map Transition
-------------------------------

function metano_cafe.Cafe_Entrance_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  if SV.metano_town.Song ~= "Spinda's Cafe.ogg" then SOUND:FadeOutBGM(20) end--map transition may result in a music change depending on song Falo is playing
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("metano_town", "Cafe_Entrance_Marker", SV.metano_town.Song == "Spinda's Cafe.ogg")
  SV.partner.Spawn = 'Cafe_Entrance_Marker_Partner'
end



-------------------------------
-- Entities Callbacks
-------------------------------

--lists fermented drinks, their effects, and the recipes for each
function metano_cafe.Cafe_Sign_Action(obj, activator)
	DEBUG.EnableDbgCoro()
	print("Cafe sign action")
	local hero = CH('PLAYER')
	local partner = CH('Teammate1')
	UI:ResetSpeaker(false)
	local state = 0
	UI:SetCenter(true)
	partner.IsInteracting = true
	GROUND:CharSetAnim(partner, 'None', true)
	GROUND:CharSetAnim(hero, 'None', true)		
    GeneralFunctions.TurnTowardsLocation(hero, obj.Position.X + obj.Width // 2, obj.Position.Y + obj.Height // 2)
    GeneralFunctions.TurnTowardsLocation(partner, obj.Position.X + obj.Width // 2, obj.Position.Y + obj.Height // 2)

	local shuckle_name = CharacterEssentials.GetCharacterName("Shuckle")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Sign_Intro'], shuckle_name))
	
	local item1
	local item2
	
	while state > -1 do
		local choices = {STRINGS:Format(STRINGS.MapStrings['Cafe_Option_Domi']),
						STRINGS:Format(STRINGS.MapStrings['Cafe_Option_Cider']), 
						STRINGS:Format(STRINGS.MapStrings['Cafe_Option_Bomb']), 
						STRINGS:FormatKey('MENU_EXIT')}
						
		--Endurance Tonic is added in Chapter 4.
		--todo: better system for this?
		if SV.ChapterProgression.Chapter >= 4 then 
			table.insert(choices, 4, STRINGS:Format(STRINGS.MapStrings['Cafe_Option_Endurance']))
		end
				
				
		UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['Cafe_Sign_Which_Drinks']), choices, 1, #choices)
		UI:WaitForChoice()
		local result = UI:ChoiceResult()
		if result == 1 then
			item1 = RogueEssence.Dungeon.InvItem("berry_oran")--oran berry 
			item2 = RogueEssence.Dungeon.InvItem("ammo_stick")--stick
			item2.Amount = 5
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Sign_Domi_1']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Sign_Domi_2'], item1:GetDisplayName(), item2:GetDisplayName()))
		elseif result == 2 then
			item1 = RogueEssence.Dungeon.InvItem("food_apple")--Apple 
			item2 = RogueEssence.Dungeon.InvItem("berry_oran")--oran berry
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Sign_Cider_1']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Sign_Cider_2'], item1:GetDisplayName(), item2:GetDisplayName()))
		elseif result == 3 then 
			item1 = RogueEssence.Dungeon.InvItem("berry_cheri")--cheri berry
			item2 = RogueEssence.Dungeon.InvItem("seed_blast")--blast seed 
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Sign_Bomb_1']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Sign_Bomb_2'], item1:GetDisplayName(), item2:GetDisplayName()))
		elseif result == 4 and #choices > 4 then 
			item1 = RogueEssence.Dungeon.InvItem("seed_reviver")
			item2 = RogueEssence.Dungeon.InvItem("berry_chesto")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Sign_Endurance_1']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Sign_Endurance_2'], item1:GetDisplayName(), item2:GetDisplayName()))
		else
			state = -1
		end
	end

	UI:SetCenter(false)
	partner.IsInteracting = false
	GROUND:CharEndAnim(partner)
	GROUND:CharEndAnim(hero)	
end


--[[
Drink ideas:
Frosty Float:
- ingredients: aspear berries, oran berries
- grants aurora veil to the party, even if it's not hailing

Banana Smoothie:
- Party full HP recovery + all stats EVs up by 1
- Tropius provides bananas to guild members as a rare reward for a job well done 


Endure Tonic:
- Gives drinker endure status for some time where they cannot be KO'd.
- Costs a reviver seed and something else.
]]--

--PARLER AU TENANCIER. triggerType = 1, 4 cases libres sur 4 : il est
--parfaitement abordable, mais n'avait aucun handler. On delegue au
--comptoir, qui porte le menu du cafe.
function metano_cafe.Cafe_Owner_Action(chara, activator)
  metano_cafe.Cafe_Action(chara, activator)
end

function metano_cafe.Cafe_Action(obj, activator)
	DEBUG.EnableDbgCoro()
	print("Cafe action")
	
	local state = 0
	local repeated = false
	
	--list of ~100 items, a random one is taken for new day to be sold as the cafe's special.
	local specials_catalog = 
	{
		{"food_apple_big", 30},
		{"food_apple_huge", 20},
		{"food_apple_perfect", 3},
		{"food_apple_golden", 1},
		
		{"food_banana", 10},
		{"food_banana_big", 2},
		{"food_banana_golden", 1},
		
		{"berry_lum", 15},
		{"berry_sitrus", 5},
		
		{"berry_tanga", 3},
		{"berry_colbur", 3},
		{"berry_haban", 3},
		{"berry_wacan", 3},
		{"berry_chople", 3},
		{"berry_occa", 3},
		{"berry_coba", 3},
		{"berry_kasib", 3},
		{"berry_rindo", 3},
		{"berry_shuca", 3},
		{"berry_yache", 3},
		{"berry_chilan", 3},
		{"berry_kebia", 3},
		{"berry_payapa", 3},
		{"berry_charti", 3},
		{"berry_babiri", 3},
		{"berry_passho", 3},
		{"berry_roseli", 3},
		
		{"berry_jaboca", 3},
		{"berry_rowap", 3},
		{"berry_apicot", 3},
		{"berry_liechi", 3},
		{"berry_ganlon", 3},
		{"berry_salac", 3},
		{"berry_petaya", 3},
		{"berry_starf", 3},
		{"berry_micle", 3},
		{"berry_enigma", 3},
		
				
		{"gummi_blue", 1}, --Blue Gummi
		{"gummi_black", 1}, --Black Gummi
		{"gummi_clear", 1}, --Clear Gummi
		{"gummi_grass", 1}, --Grass Gummi
		{"gummi_green", 1}, --Green Gummi
		{"gummi_brown", 1}, --Brown Gummi
		{"gummi_orange", 1}, --Orange Gummi
		{"gummi_gold", 1}, --Gold Gummi
		{"gummi_pink", 1}, --Pink Gummi
		{"gummi_purple", 1}, --Purple Gummi
		{"gummi_red", 1}, --Red Gummi
		{"gummi_royal", 1}, --Royal Gummi
		{"gummi_silver", 1}, --Silver Gummi
		{"gummi_white", 1}, --White Gummi
		{"gummi_yellow", 1}, --Yellow Gummi
		{"gummi_sky", 1}, --Sky Gummi
		{"gummi_gray", 1}, --Gray Gummi
		{"gummi_magenta", 1},	--Magenta Gummi
		{"gummi_wonder", 1}, --Wonder Gummi
		
		{"seed_plain", 20},
		{"seed_reviver", 10},
		{"seed_joy", 1},
		{"seed_doom", 3},

		{"boost_nectar", 1},
		{"boost_protein", 1},
		{"boost_iron", 1},
		{"boost_calcium", 1},
		{"boost_zinc", 1},
		{"boost_carbos", 1},
		{"boost_hp_up", 1},
		
		{"herb_mental", 5},
		{"herb_power", 5},
		{"herb_white", 5}
	}
	
	-- special is -1 if nothing has been selected as the daily special. It should be set back to -1 when a new day happens
	--but more ideally it should just be reinitialized when a new day happens. I just need to figure out how to do that properly
	if SV.metano_cafe.CafeSpecial == "" then 
		SV.metano_cafe.CafeSpecial =  GeneralFunctions.WeightedRandom(specials_catalog)
	end
	
	local special = RogueEssence.Dungeon.InvItem(SV.metano_cafe.CafeSpecial)
	local specialName = special:GetDisplayName()
	local specialPrice = special:GetSellValue()
	local owner = CH('Cafe_Owner')
	UI:SetSpeaker(owner)
	
	local hero = CH('PLAYER')
	local partner = CH('Teammate1')
	owner.IsInteracting = true
	partner.IsInteracting = true
	GROUND:CharSetAnim(partner, 'None', true)
	GROUND:CharSetAnim(hero, 'None', true)
	GROUND:CharSetAnim(owner, 'None', true)
			
	GROUND:CharTurnToChar(hero, owner)
	local coro1 = TASK:BranchCoroutine(function() GROUND:CharTurnToCharAnimated(partner, owner, 4) end)

	--He has a new type of drink he can serve
	if SV.metano_cafe.NewDrinkUnlocked then
		GeneralFunctions.SetEmotion("Happy")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_New_Drink_1']))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_New_Drink_2']))
		SV.metano_cafe.NewDrinkUnlocked = false
		GAME:WaitFrames(20)
	end 
	
	--He gives a free Domi Blend before the expedition
	if SV.ChapterProgression.Chapter == 5 and not SV.Chapter5.GotFreeCafeItem then
		GeneralFunctions.SetEmotion("Inspired")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Expedition_Item_Intro_1']))
		GeneralFunctions.SetEmotion("Happy")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Expedition_Item_Intro_2']))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Expedition_Item_Intro_3']))
		GAME:WaitFrames(20)
		GeneralFunctions.RewardItem("cafe_domi_blend")
		GAME:WaitFrames(20)
		SV.Chapter5.GotFreeCafeItem = true
	end
	
	--he has a fermented item to give you
	if SV.metano_cafe.FermentedItem ~= "" and SV.metano_cafe.ItemFinishedFermenting then
		local juiceEntry = RogueEssence.Data.DataManager.Instance:GetItem(SV.metano_cafe.FermentedItem)
		local juice = RogueEssence.Dungeon.InvItem(SV.metano_cafe.FermentedItem, false, juiceEntry.MaxStack)
		GeneralFunctions.SetEmotion('Normal')
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Fermented_Give_Item_1'], juice:GetDisplayName()))
		if GAME:GetPlayerBagCount() + GAME:GetPlayerEquippedCount() >= GAME:GetPlayerBagLimit() then
			GeneralFunctions.SetEmotion('Worried')
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Bag_Full'], CharacterEssentials.GetCharacterName('Kangaskhan')))
			state = -1 --don't go to normal dialogue if he cant give you the fermented item.
		else
			--he retreats into his shell and pulls it out.
			GAME:WaitFrames(20)
			SOUND:PlayBattleSE('DUN_Equip')
			GROUND:CharSetAction(owner, RogueEssence.Ground.PoseGroundAction(owner.Position, owner.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Special0")))
			GAME:WaitFrames(60)
			SOUND:PlayBattleSE('DUN_Worry_Seed')
			GROUND:CharSetAction(owner, RogueEssence.Ground.PoseGroundAction(owner.Position, owner.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Special2")))
			GeneralFunctions.SetEmotion("Happy")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Fermented_Give_Item_2'], juice:GetDisplayName()))
			GROUND:CharSetAnim(owner, "None", true)
		
			--gives it to the player.
			GAME:GivePlayerItem(juice.ID, juiceEntry.MaxStack)
			SV.metano_cafe.FermentedItem = ""
			SV.metano_cafe.ItemFinishedFermenting = false
			SOUND:PlayBattleSE("DUN_Drink")
			UI:ResetSpeaker()
			UI:SetCenter(true)
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Fermented_Item_Received'], juice:GetDisplayName(), owner:GetDisplayName()))
			UI:SetCenter(false)
		end			
	end
	

	--Normal Cafe Shop script
	while state > -1 do
		UI:SetSpeaker(owner)
		GeneralFunctions.SetEmotion("Normal")
		local msg = STRINGS:Format(STRINGS.MapStrings['Cafe_Intro'])
		if repeated then 
			msg = STRINGS:Format(STRINGS.MapStrings['Cafe_Intro_Return'])
		end
		local cafe_choices = {STRINGS:Format(STRINGS.MapStrings['Cafe_Option_Ferment']), STRINGS:Format(STRINGS.MapStrings['Cafe_Option_Special']),
							  STRINGS:FormatKey('MENU_INFO'), STRINGS:FormatKey('MENU_EXIT')}
		UI:BeginChoiceMenu(msg, cafe_choices, 1, 4)
		UI:WaitForChoice()
		local result = UI:ChoiceResult()
		repeated = true
		if result == 1 then --drinks
			--he's already brewing something
			if SV.metano_cafe.FermentedItem ~= "" then
				local ferment_item = RogueEssence.Dungeon.InvItem(SV.metano_cafe.FermentedItem)
				local ferment_item_entry = RogueEssence.Data.DataManager.Instance:GetItem(SV.metano_cafe.FermentedItem)
				if ferment_item_entry.MaxStack > 1 then ferment_item.Amount = ferment_item_entry.MaxStack end--for multi-use items, like the apple cider
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Already_Fermenting'], ferment_item:GetDisplayName()))
			--Can't brew items if you're about to go on the expedition
			--This is to safeguard you against using up items that you may potentially want to use on the expedition, rather than lock them away here for the duration of it
			elseif SV.ChapterProgression.Chapter == 5 then
				GeneralFunctions.SetEmotion("Worried")
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Expedition_Prevent_Fermenting_1']))
				GeneralFunctions.SetEmotion("Normal")
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Expedition_Prevent_Fermenting_2']))
			else		
				GeneralFunctions.SetEmotion("Normal")
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Ferment_Prompt']))
				
				local CreateFermentMenu = CreateFermentMenu()
				local items = {
					{ 
						item_to_ferment = "cafe_domi_blend",
						servings = 1,
						recipe_list = {{"berry_oran", 3}, {"ammo_stick", 5}},
						description_key = "Cafe_Sign_Domi_1",
					},
					{
						item_to_ferment = "cafe_apple_cider",
						servings = 4,
						recipe_list = {{"berry_oran", 1}, {"food_apple", 3}},
						description_key = "Cafe_Sign_Cider_1"
					},
					{
						item_to_ferment = "cafe_cheri_bomb",
						servings = 1,
						recipe_list = {{"berry_cheri", 1}, {"seed_blast", 1}},
						description_key = "Cafe_Sign_Bomb_1"
					},
	
				}
				if SV.ChapterProgression.Chapter >= 4 then 
					local endurance_tonic = {
						item_to_ferment = "cafe_endurance_tonic",
						servings = 1,
						recipe_list = {{"seed_reviver", 1}, {"berry_chesto", 1}},
						description_key = "Cafe_Sign_Endurance_1"
					}
					table.insert(items, 4, endurance_tonic)
				end
	
				local menu = CreateFermentMenu:new(items, STRINGS.MapStrings)
				UI:SetCustomMenu(menu.menu)
				UI:WaitForChoice()
	
				if (menu.item_list_index > -1) then
					local menu_item = items[menu.item_list_index + 1]
					local ferment_item = RogueEssence.Dungeon.InvItem(menu_item.item_to_ferment, false, menu_item.servings)
					UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Cafe_Confirm_Ferment_Choice'], ferment_item:GetDisplayName()), true)
					UI:WaitForChoice()
					local confirm = UI:ChoiceResult()
					if confirm then
						SV.metano_cafe.FermentedItem = menu_item.item_to_ferment
						metano_cafe.RemoveItems(menu_item.recipe_list)
						GeneralFunctions.SetEmotion("Happy")
						UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Begin_Fermenting_1']))
						--puts the items in his shell
						SOUND:PlayBattleSE('DUN_Equip')
						GROUND:CharSetAction(owner, RogueEssence.Ground.PoseGroundAction(owner.Position, owner.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Special0")))
						GAME:WaitFrames(60)
						GROUND:CharSetDrawEffect(owner, DrawEffect.Trembling)
						SOUND:PlayBattleSE('DUN_Drink')
						GAME:WaitFrames(60)
						SOUND:PlayBattleSE('DUN_Fake_Tears')
						GAME:WaitFrames(60)
						SOUND:PlayBattleSE('DUN_Food')
						GAME:WaitFrames(60)
						SOUND:PlayBattleSE('DUN_Worry_Seed')
						GROUND:CharEndDrawEffect(owner, DrawEffect.Trembling)
						GROUND:CharWaitAnim(owner, "Special1")
						GROUND:CharSetAnim(owner, "None", true)
						GeneralFunctions.SetEmotion("Inspired")
						UI:WaitShowTimedDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Begin_Fermenting_2']), 60)
						GAME:WaitFrames(20)
						GeneralFunctions.SetEmotion("Happy")
						UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Begin_Fermenting_3'], ferment_item:GetDisplayName()))
					end
				end
			end
		elseif result == 2 then --today's special
			if SV.metano_cafe.BoughtSpecial then 
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Bought_Special']))	
			else 					
				--UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Cafe_Daily_Special'], specialName, specialPrice)) --deprecated
				local SingleItemDealMenu = SingleItemDealMenu()
				local menu = SingleItemDealMenu:new("Café Special", special, specialPrice)
				UI:SetCustomMenu(menu.menu)
				UI:WaitForChoice()
				if menu.result then
					if specialPrice > GAME:GetPlayerMoney() then --Menu coding prevents this from being hit (can't try to buy if no money), but keep this here in case.
						GeneralFunctions.SetEmotion('Worried')
						UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_No_Money']))
						GeneralFunctions.SetEmotion('Normal')
					elseif GAME:GetPlayerBagCount() + GAME:GetPlayerEquippedCount() >= GAME:GetPlayerBagLimit() then
						GeneralFunctions.SetEmotion('Worried')
						UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Bag_Full'], CharacterEssentials.GetCharacterName('Kangaskhan')))
						GeneralFunctions.SetEmotion('Normal')
					else
						SV.metano_cafe.BoughtSpecial = true
						GAME:RemoveFromPlayerMoney(specialPrice)
						GAME:GivePlayerItem(special.ID, 1)
						SOUND:PlayBattleSE("DUN_Money")
						GeneralFunctions.SetEmotion("Happy")
						UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Special_Complete'], specialName))
						GeneralFunctions.SetEmotion("Normal")
					end
				end 
			end
		elseif result == 3 then --cafe info
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Info_1']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Info_2']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Info_3']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Info_4']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Info_5']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Info_6']))
		else--exit
			GeneralFunctions.SetEmotion("Happy")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Cafe_Goodbye']))
			GeneralFunctions.SetEmotion("Normal")
			state = -1
		end
				
				
		
	
	
	
	--elseif state == 1 then 	 shop menu for smoothies	
		
		
	end

	--reimplementing parts of endconversation
	TASK:JoinCoroutines({coro1})
	partner.IsInteracting = false
	owner.IsInteracting = false
	
	GROUND:CharEndAnim(partner)
	GROUND:CharEndAnim(hero)
	GROUND:CharEndAnim(owner)	
	
	
end




--used to check what items you have. Returns true or false.
--item list is a list of pairs that contain an item ID and the corresponding amount needed.
function metano_cafe.CheckForItems(itemList)
	local bag_count = GAME:GetPlayerBagCount()
	local item_count = #itemList--how many unique items are needed for the recipe?
	local stack_count
	local recipe_item
	local item
	local item_entry
	local togo 
	
	--no items, no way this could return true
	if bag_count == 0 then return false end
	
	for i=1, item_count, 1 do
		recipe_item = itemList[i][1]
		togo = itemList[i][2]
		for j=0, bag_count-1, 1 do
			item = GAME:GetPlayerBagItem(j)
			item_entry = RogueEssence.Data.DataManager.Instance:GetItem(item.ID)
			if item_entry.MaxStack > 1 then stack_count = item.Amount else stack_count = 1 end
			if item.ID == recipe_item then
				togo = togo - stack_count --subtract from the needed items by the stack count. This can go negative, which is fine.
			end
		end
		
		if togo > 0 then return false end --Break early and return a false if we couldn't meet the item requirements for a particular recipe item.
		
	end
	
	--to get to this point, we must have passed item counts for all needed items.
	return true

	

end

--used to remove items needed for a drink.
--item list is a list of pairs that contain an item ID and the corresponding amount needed.
function metano_cafe.RemoveItems(itemList)
	local bag_count
	local item_count = #itemList--how many unique items are needed for the recipe?
	local stack_count
	local recipe_item
	local item
	local item_entry
	local togo

	--the item bag indexes at 0.
	for i=1, item_count, 1 do
		recipe_item = itemList[i][1]	
		togo = itemList[i][2]
		bag_count = GAME:GetPlayerBagCount()--update bag count as we go
		for j=bag_count-1 , 0, -1 do
			item = GAME:GetPlayerBagItem(j)
			item_entry = RogueEssence.Data.DataManager.Instance:GetItem(item.ID)
			if item_entry.MaxStack > 1 then stack_count = item.Amount else stack_count = 1 end
			if item.ID == recipe_item then
				if item_entry.MaxStack <= 1 then 
					GAME:TakePlayerBagItem(j, true)
				else
					if item.Amount > togo then--check if the stackable item needs to be deleted, or just subtracted from.
						--remove from the player's bag item stack but not fully.
						item.Amount = stack_count - togo
					else
						--print(item.Amount)
						--print(j)
						GAME:TakePlayerBagItem(j, true)
					end
				end
				
				togo = togo - stack_count --subtract from the needed items by the stack count. This can go below 0 when stackables are involved.
						
				--break early for an item if this particular item has been cleared.
				if togo <= 0 then break end
			end
		end
	end

end




function metano_cafe.Breloom_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("metano_cafe_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Breloom_Action(...,...)"), chara, activator))
end

function metano_cafe.Girafarig_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("metano_cafe_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Girafarig_Action(...,...)"), chara, activator))
end

function metano_cafe.Mareep_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("metano_cafe_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Mareep_Action(...,...)"), chara, activator))
end

function metano_cafe.Cranidos_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("metano_cafe_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Cranidos_Action(...,...)"), chara, activator))
end

function metano_cafe.Linoone_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("metano_cafe_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Linoone_Action(...,...)"), chara, activator))
end

function metano_cafe.Cleffa_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("metano_cafe_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Cleffa_Action(...,...)"), chara, activator))
end

function metano_cafe.Aggron_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("metano_cafe_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Aggron_Action(...,...)"), chara, activator))
end


function metano_cafe.Gulpin_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("metano_cafe_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Gulpin_Action(...,...)"), chara, activator))
end

function metano_cafe.Lickitung_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("metano_cafe_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Lickitung_Action(...,...)"), chara, activator))
end






function metano_cafe.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
end

--your allies will wait for you in the cafe if you have any.
function metano_cafe.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GeneralFunctions.GroundInteract(activator, chara)
end

function metano_cafe.Teammate3_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GeneralFunctions.GroundInteract(activator, chara)
end

function metano_cafe.PlayDailyCutscene()
  local day = (SV.ChapterProgression and SV.ChapterProgression.DaysPassed) or 0
  if SV.metano_cafe.LastDailyCutsceneDay == day then
    return
  end
  -- Le jour n'est marque comme consomme qu'A LA FIN de la scene (voir plus bas).
  -- Il l'etait ici, AVANT le corps de la scene : si celle-ci echouait, le pcall
  -- appelant avalait l'erreur mais le jour restait brule, et le joueur perdait
  -- definitivement la cinematique de ce jour-la, sans aucun message.

  local hero = CH('PLAYER')
  local partner = CH('Teammate1')
  GAME:CutsceneMode(true)
  GAME:FadeOut(false, 1)

  local scene_index = day % 7
  
  if scene_index == 0 then
    -- Scène 0 : Goinfrex mendie à manger
    local goinfrex = CharacterEssentials.MakeCharactersFromList({{'Goinfrex', 140, 160, Direction.Right}})
    local ludicolo = CharacterEssentials.MakeCharactersFromList({{'Ludicolo', 180, 160, Direction.Left}})
    GROUND:CharSetAnim(goinfrex, 'Idle', true)
    GROUND:CharSetAnim(ludicolo, 'Idle', true)
    GAME:MoveCamera(160, 160, 1, false)
    GAME:FadeIn(20)
    
    UI:SetSpeaker(goinfrex)
    UI:WaitShowDialogue("S'il te plaît, Ludicolo...[pause=15] Donne-moi un smoothie gratuit !")
    UI:WaitShowDialogue("Je n'ai pas mangé depuis au moins dix minutes...[pause=20] Je vais m'évanouir !")
    
    UI:SetSpeaker(ludicolo)
    UI:WaitShowDialogue("Haha ! Non, non, mon garçon ![pause=15] Au café, on danse et on s'active d'abord !")
    UI:WaitShowDialogue("Fais une petite danse de l'estomac, et on verra !")
    
    GAME:FadeOut(false, 20)
    GAME:GetCurrentGround():RemoveTempChar(goinfrex)
    GAME:GetCurrentGround():RemoveTempChar(ludicolo)

  elseif scene_index == 1 then
    -- Scène 1 : Foreshadowing Cresselia
    local girafarig = CharacterEssentials.MakeCharactersFromList({{'Girafarig', 140, 160, Direction.Right}})
    local cleffa = CharacterEssentials.MakeCharactersFromList({{'Cleffa', 180, 160, Direction.Left}})
    GROUND:CharSetAnim(girafarig, 'Idle', true)
    GROUND:CharSetAnim(cleffa, 'Idle', true)
    GAME:MoveCamera(160, 160, 1, false)
    GAME:FadeIn(20)
    
    UI:SetSpeaker(girafarig)
    UI:WaitShowDialogue("J'ai fait un rêve si étrange la nuit dernière, Mélo...")
    UI:WaitShowDialogue("Un vide noir immense essayait d'avaler la lune...[pause=15] et un Pokémon en croissant doré se battait contre lui.")
    
    UI:SetSpeaker(cleffa)
    UI:WaitShowDialogue("Oh ! C'est la légende de Cresselia, la gardienne de la Cour Clair-Lune !")
    UI:WaitShowDialogue("On dit qu'elle protège les rêves des gens contre l'obscurité totale...")
    
    GAME:FadeOut(false, 20)
    GAME:GetCurrentGround():RemoveTempChar(girafarig)
    GAME:GetCurrentGround():RemoveTempChar(cleffa)

  elseif scene_index == 2 then
    -- Scène 2 : Dispute d'Almotz (Gloom) et Excelangue (Lickitung)
    local gloom = CharacterEssentials.MakeCharactersFromList({{'Gloom', 140, 160, Direction.Right}})
    local lickitung = CharacterEssentials.MakeCharactersFromList({{'Lickitung', 180, 160, Direction.Left}})
    GROUND:CharSetAnim(gloom, 'Idle', true)
    GROUND:CharSetAnim(lickitung, 'Idle', true)
    GAME:MoveCamera(160, 160, 1, false)
    GAME:FadeIn(20)
    
    UI:SetSpeaker(gloom)
    GeneralFunctions.SetEmotion("Angry")
    UI:WaitShowDialogue("Ne lèche pas ça !![pause=15] C'est mon miel de rechange, et il est hautement toxique !")
    
    UI:SetSpeaker(lickitung)
    GeneralFunctions.SetEmotion("Surprised")
    UI:WaitShowDialogue("Léchouille... ?[pause=10] Oh, pardon, Almotz !")
    UI:WaitShowDialogue("Il avait l'air si sucré...[pause=15] J'ai la langue toute bleue maintenant !")
    
    UI:SetSpeaker(gloom)
    UI:WaitShowDialogue("Tu as failli y laisser ta langue ![pause=15] Va boire de l'eau, vite !")
    
    GAME:FadeOut(false, 20)
    GAME:GetCurrentGround():RemoveTempChar(gloom)
    GAME:GetCurrentGround():RemoveTempChar(lickitung)

  elseif scene_index == 3 then
    -- Scène 3 : Foreshadowing Regigigas
    local aggron = CharacterEssentials.MakeCharactersFromList({{'Aggron', 140, 160, Direction.Right}})
    local cranidos = CharacterEssentials.MakeCharactersFromList({{'Cranidos', 180, 160, Direction.Left}})
    GROUND:CharSetAnim(aggron, 'Idle', true)
    GROUND:CharSetAnim(cranidos, 'Idle', true)
    GAME:MoveCamera(160, 160, 1, false)
    GAME:FadeIn(20)
    
    UI:SetSpeaker(aggron)
    UI:WaitShowDialogue("Tu t'intéresses aux ruines antiques, gamin ?")
    UI:WaitShowDialogue("On raconte que sous le Sanctuaire Millénaire sommeille un golem colossal...[pause=20] Regigigas.")
    
    UI:SetSpeaker(cranidos)
    UI:WaitShowDialogue("Regigigas ?! Le colosse qui déplace les montagnes ?")
    UI:WaitShowDialogue("Je me demande s'il est aussi solide que ma tête !")
    
    GAME:FadeOut(false, 20)
    GAME:GetCurrentGround():RemoveTempChar(aggron)
    GAME:GetCurrentGround():RemoveTempChar(cranidos)

  elseif scene_index == 4 then
    -- Scène 4 : Grodoudou (Wigglytuff) sleep-walk
    local breloom = CharacterEssentials.MakeCharactersFromList({{'Breloom', 140, 160, Direction.Right}})
    local mareep = CharacterEssentials.MakeCharactersFromList({{'Mareep', 180, 160, Direction.Left}})
    GROUND:CharSetAnim(breloom, 'Idle', true)
    GROUND:CharSetAnim(mareep, 'Idle', true)
    GAME:MoveCamera(160, 160, 1, false)
    GAME:FadeIn(20)
    
    UI:SetSpeaker(mareep)
    UI:WaitShowDialogue("J'ai vu le Maître de la Guilde traverser le mur en pleine nuit...")
    UI:WaitShowDialogue("Il a avalé une Pomme Parfaite entière sans ouvrir les yeux !")
    
    UI:SetSpeaker(breloom)
    UI:WaitShowDialogue("Haha ! Ne t'inquiète pas, c'est tout à fait normal pour Grodoudou.")
    UI:WaitShowDialogue("Évite juste de le regarder quand il cherche ses pommes !")
    
    GAME:FadeOut(false, 20)
    GAME:GetCurrentGround():RemoveTempChar(breloom)
    GAME:GetCurrentGround():RemoveTempChar(mareep)

  elseif scene_index == 5 then
    -- Scène 5 : Foreshadowing Latias/Latios
    local linoone = CharacterEssentials.MakeCharactersFromList({{'Linoone', 140, 160, Direction.Right}})
    local gulpin = CharacterEssentials.MakeCharactersFromList({{'Gulpin', 180, 160, Direction.Left}})
    GROUND:CharSetAnim(linoone, 'Idle', true)
    GROUND:CharSetAnim(gulpin, 'Idle', true)
    GAME:MoveCamera(160, 160, 1, false)
    GAME:FadeIn(20)
    
    UI:SetSpeaker(linoone)
    UI:WaitShowDialogue("Je jure avoir vu deux ombres colorées voler à toute vitesse au-dessus de la mer.")
    UI:WaitShowDialogue("Une rouge et une bleue... Elles filaient comme des étoiles filantes !")
    
    UI:SetSpeaker(gulpin)
    UI:WaitShowDialogue("Des ombres... ?[pause=15] Gloups... C'était peut-être la Cité Suspendue.")
    UI:WaitShowDialogue("Moi, je préfère garder mes pieds sur terre et mon verre bien rempli.")
    
    GAME:FadeOut(false, 20)
    GAME:GetCurrentGround():RemoveTempChar(linoone)
    GAME:GetCurrentGround():RemoveTempChar(gulpin)

  elseif scene_index == 6 then
    -- Scène 6 : Goinfrex qui vole de la sève
    local goinfrex = CharacterEssentials.MakeCharactersFromList({{'Goinfrex', 140, 160, Direction.Right}})
    local shuckle = CH('Cafe_Owner')
    GROUND:CharSetAnim(goinfrex, 'Idle', true)
    GAME:MoveCamera(160, 160, 1, false)
    GAME:FadeIn(20)
    
    UI:SetSpeaker(shuckle)
    GeneralFunctions.SetEmotion("Angry")
    UI:WaitShowDialogue("Arrête toi tout de suite ![pause=15] Ne mange pas ma jarre de fermentation !")
    
    UI:SetSpeaker(goinfrex)
    GeneralFunctions.SetEmotion("Surprised")
    UI:WaitShowDialogue("Mais... mais elle sentait si bon...[pause=15] C'est juste de la sève !")
    
    UI:SetSpeaker(shuckle)
    UI:WaitShowDialogue("C'est notre réserve spéciale pour les smoothies de demain ! Hors de ma vue, petit glouton !")
    
    GAME:FadeOut(false, 20)
    GAME:GetCurrentGround():RemoveTempChar(goinfrex)
  end

  GAME:MoveCamera(160, 240, 1, false)
  GAME:FadeIn(20)
  GAME:CutsceneMode(false)

  -- Scene jouee jusqu'au bout : on peut consommer le jour.
  SV.metano_cafe.LastDailyCutsceneDay = day
end


-- ============================================================
-- KIRLIA, L'ERUDITE DE LA GUILDE — Cafe Spinda
--
-- Placement : le Quizz Theorique est l'Epreuve II du Grand Tournoi
-- Inter-Guilde (ch8, cf. docs/CHAPITRE8_GRAND_TOURNOI_INTER_GUILDE.md).
-- Kirlia tient sa table de revision au Cafe, pas sur la place : c'est
-- l'endroit ou l'on s'assoit pour reviser, et cela evite d'encombrer
-- metano_town deja tres charge.
--
-- Le handler est unique et interroge le chapitre lui-meme (pas de
-- dispatch metano_cafe_ch_N) : Kirlia n'existe pas avant le ch8 et
-- garde un mot d'accueil apres, ce qui tient en une fonction.
-- ============================================================

function metano_cafe.Kirlia_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  local ok, err = pcall(function() metano_cafe.KirliaQuiz(chara, activator) end)
  if not ok then
    PrintInfo('[metano_cafe] Kirlia_Action ecourtee : ' .. tostring(err))
    pcall(function()
      UI:ResetSpeaker()
      GeneralFunctions.EndConversation(chara)
    end)
  end
end

function metano_cafe.KirliaQuiz(chara, activator)
  local chapter = SV.ChapterProgression.Chapter

  -- Avant le ch8 : Kirlia revise, le tournoi n'est pas annonce.
  if chapter < 8 then
    GeneralFunctions.StartConversation(chara,
      "Chut...[pause=20] Je revise.", "Normal")
    GeneralFunctions.SetEmotion("Worried")
    UI:WaitShowDialogue("Un jour, la Guilde organisera de nouveau un grand tournoi.[pause=20] Ce jour-la, je serai prete.")
    GeneralFunctions.EndConversation(chara)
    return
  end

  -- Apres le ch8 : elle commente le score obtenu.
  if SV.Chapter8.QuizScore ~= nil then
    if SV.Chapter8.QuizScore == "Perfect" then
      GeneralFunctions.StartConversation(chara,
        "Trois sur trois.[pause=20] Je n'avais pas vu ca depuis des annees.", "Happy")
      UI:WaitShowDialogue("Gardez cette rigueur sous terre.[pause=15] Les donjons corrigent plus severement que moi.")
    elseif SV.Chapter8.QuizScore == "Pass" then
      GeneralFunctions.StartConversation(chara,
        "Votre score est enregistre.[pause=20] Vous passez l'Epreuve II.", "Normal")
      UI:WaitShowDialogue("De justesse, sur certaines reponses.[pause=15] Relisez vos manuels avant l'epreuve de combat.")
    else
      GeneralFunctions.StartConversation(chara,
        "Votre score est enregistre.[pause=20] Nous n'en reparlerons pas.", "Sad")
      UI:WaitShowDialogue("La theorie n'a jamais sauve personne seule.[pause=20] Prouvez-moi que la pratique vous reussit mieux.")
    end
    GeneralFunctions.EndConversation(chara)
    return
  end

  GeneralFunctions.StartConversation(chara,
    "Vous voila.[pause=20] Je suis Kirlia, erudite de la Guilde.", "Normal")
  GeneralFunctions.SetEmotion("Determined")
  UI:WaitShowDialogue("Epreuve II du Grand Tournoi :[pause=15] le Quizz Theorique d'Exploration.")
  UI:WaitShowDialogue("Trois questions.[pause=20] Prenez le temps qu'il vous faut : je ne suis pas pressee.")

  UI:ChoiceMenuYesNo("Passer l'Epreuve II maintenant ?", true)
  UI:WaitForChoice()

  if not UI:ChoiceResult() then
    GeneralFunctions.SetEmotion("Normal")
    UI:WaitShowDialogue("Sage.[pause=20] Revenez quand vous serez prets.")
    GeneralFunctions.EndConversation(chara)
    return
  end

  local score = 0

  -- QUESTION 1 : affinites de types
  GeneralFunctions.SetEmotion("Normal")
  UI:WaitShowDialogue("Premiere question.[pause=15] Quel type est super efficace contre un Pokemon Acier et Spectre ?")
  UI:BeginChoiceMenu("Votre reponse :", {"Type Combat", "Type Feu", "Type Normal", "Type Psy"}, 1, 4)
  UI:WaitForChoice()
  if UI:ChoiceResult() == 2 then
    score = score + 1
    SOUND:PlaySE("DUN_Hit_Weak")
    GeneralFunctions.SetEmotion("Happy")
    UI:WaitShowDialogue("Le Feu fait fondre l'Acier.[pause=15] Exact.")
  else
    SOUND:PlaySE("DUN_Worry_Seed")
    GeneralFunctions.SetEmotion("Sad")
    UI:WaitShowDialogue("Non.[pause=15] L'Acier encaisse le Psy, et le Spectre ignore le Combat comme le Normal.")
  end
  GAME:WaitFrames(20)

  -- QUESTION 2 : lore etabli au ch5 (mount_windswept_entrance) et rappele au ch7
  GeneralFunctions.SetEmotion("Normal")
  UI:WaitShowDialogue("Deuxieme question.[pause=15] Qui veille au sommet de la Tour Celeste ?")
  UI:BeginChoiceMenu("Votre reponse :", {"Lugia", "Rayquaza", "Dialga", "Ho-Oh"}, 1, 4)
  UI:WaitForChoice()
  if UI:ChoiceResult() == 2 then
    score = score + 1
    SOUND:PlaySE("DUN_Hit_Weak")
    GeneralFunctions.SetEmotion("Happy")
    UI:WaitShowDialogue("Rayquaza.[pause=20] Celui que les caravaniers appellent l'Arbitre du Ciel.")
  else
    SOUND:PlaySE("DUN_Worry_Seed")
    GeneralFunctions.SetEmotion("Sad")
    UI:WaitShowDialogue("Non.[pause=15] C'est Rayquaza qui regne sur cette tour.")
  end
  GAME:WaitFrames(20)

  -- QUESTION 3 : survie en donjon
  GeneralFunctions.SetEmotion("Normal")
  UI:WaitShowDialogue("Troisieme question.[pause=15] Quel objet dissipe d'un coup les alterations de toute l'equipe ?")
  UI:BeginChoiceMenu("Votre reponse :", {"La Graine Guerison", "L'Orbe Echappee", "L'Orbe Purge", "Le Ruban Statut"}, 1, 4)
  UI:WaitForChoice()
  if UI:ChoiceResult() == 3 then
    score = score + 1
    SOUND:PlaySE("DUN_Hit_Weak")
    GeneralFunctions.SetEmotion("Happy")
    UI:WaitShowDialogue("L'Orbe Purge.[pause=20] Toute l'equipe, en une fois.")
  else
    SOUND:PlaySE("DUN_Worry_Seed")
    GeneralFunctions.SetEmotion("Sad")
    UI:WaitShowDialogue("Non.[pause=15] La Graine ne soigne qu'un seul d'entre vous.")
  end
  GAME:WaitFrames(30)

  -- VERDICT — l'ecriture de SV n'intervient qu'ici, apres les 3 reponses.
  GeneralFunctions.SetEmotion("Normal")
  UI:WaitShowDialogue("L'epreuve est close.[pause=20] Voici mon verdict.")
  GAME:WaitFrames(15)

  if score == 3 then
    SOUND:PlayFanfare("Fanfare/Note")
    GeneralFunctions.SetEmotion("Joyous")
    UI:WaitShowDialogue("Trois sur trois.[pause=25] Je n'avais pas vu ca depuis des annees.")
    SV.Chapter8.QuizScore = "Perfect"
  elseif score >= 1 then
    GeneralFunctions.SetEmotion("Normal")
    UI:WaitShowDialogue(score .. " sur 3.[pause=20] Vous etes qualifies.[pause=15] Ne vous en contentez pas.")
    SV.Chapter8.QuizScore = "Pass"
  else
    GeneralFunctions.SetEmotion("Sad")
    UI:WaitShowDialogue("Zero.[pause=25] Relisez vos manuels avant de redescendre sous terre.")
    SV.Chapter8.QuizScore = "Fail"
  end

  GeneralFunctions.EndConversation(chara)
end


return metano_cafe

