-- PMU Ground Controller for pmu_s1144 (Grassroot Town, Leavi and Bulby's House)
-- Generated by PMU Pipeline (New Era)
local pmu_s1144 = {}

function pmu_s1144.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1144.Enter(map)
  local music = 'PMD3) So Come! Post Town.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1144.Update(map, time)
end

function pmu_s1144.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s737', 'Entrance', false)
end

function pmu_s1144.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s737', 'Entrance', false)
end

return pmu_s1144
