-- PMU Ground Controller for pmu_s13 (Pok? Town)
-- Generated by PMU Pipeline (New Era)
local pmu_s13 = {}

function pmu_s13.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s13.Enter(map)
  local music = 'PMD) Pokemon Plaza.mp3'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s13.Update(map, time)
end

function pmu_s13.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s987', 'Entrance', false)
end

function pmu_s13.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s357', 'Entrance', false)
end

function pmu_s13.Sign_1_Action(obj, activator)
  UI:WaitShowDialogue('Left: Poketown Outskirts')
  UI:WaitShowDialogue('Right: Poketown Square')
end

function pmu_s13.Sign_2_Action(obj, activator)
  UI:WaitShowDialogue('Spinda\'s Caf')
end

function pmu_s13.Sign_3_Action(obj, activator)
  UI:WaitShowDialogue('Spinda\'s Caf')
end

return pmu_s13
