-- PMU Ground Controller for pmu_s115 (Sour Root Lair)
-- Generated by PMU Pipeline (New Era)
local pmu_s115 = {}

function pmu_s115.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s115.Enter(map)
  local music = 'PMDB) At the End of the Road.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s115.Update(map, time)
end

return pmu_s115
