--[[
    init.lua
    Created: 01/03/2024 12:34:54
    Description: Autogenerated script file for the map mount_windswept_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'halcyon.PartnerEssentials'
require 'halcyon.GeneralFunctions'
require 'halcyon.ground.mount_windswept_entrance.mount_windswept_entrance_ch_5'

-- Package name
local mount_windswept_entrance = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']

-- Map Callbacks
---mount_windswept_entrance.Init(map)
--Engine callback function
function mount_windswept_entrance.Init(map)
  DEBUG.EnableDbgCoro()
  print('=>> Init_mount_windswept_entrance <<= [build 2026-08-03-N]')

  --LE NOIR ET LE GEL, AVANT TOUT LE RESTE.
  --
  --Cet Init s'execute APRES que le moteur a place le joueur et recadre la
  --camera (GSceneZone.EnterGround:22-27 -> ResetGround, ViewCenter=null),
  --mais AVANT le Enter qui lance la cinematique (moveToZoneInit:770-775,
  --commente « no fade; the script handles that itself »). Un rendu de la
  --carte d'arrivee est donc possible des maintenant : c'est l'apercu de
  --la NOUVELLE zone signale en jeu.
  --
  --Ces deux lignes sont donc les toutes premieres :
  --  * FadeOut(false,1) : une frame, opacite 1.0 des le premier rendu.
  --    Gratuit si l'ecran est deja noir (garde FadeEffect.cs:63-67).
  --  * CutsceneMode(true) : gele GroundScene.ProcessInput (l.176), donc
  --    ni entree joueur ni OnCheck pendant la mise en place.
  --
  --Le mode est pose SANS CONDITION. La version precedente le reservait au
  --chapitre 5 via une lecture de SV sous pcall : si la lecture echouait,
  --rien n'etait pose et la fenetre de rendu se rouvrait.
  pcall(function() GAME:FadeOut(false, 1) end)
  pcall(function() GAME:CutsceneMode(true) end)

  --LES DEUX APPELS SUIVANTS s'executent dans la coroutine de bascule
  --du moteur (moveToZoneInit -> InitGround -> OnInit) : on les protege
  --parce qu'ils sont idempotents et non vitaux — une anomalie y sera
  --tracee au lieu d'interrompre la mise en place.
  --RespawnAllies reste volontairement NON protege : si le joueur ne
  --peut pas etre place, l'erreur doit etre visible dans le log plutot
  --qu'avalee (un joueur absent produit des etats bien pires, en
  --silence). C'est aussi l'appel atteste par toutes les cartes du jeu.
  COMMON.RespawnAllies()
  pcall(function() GROUND:AddMapStatus("blowing_wind") end)
  pcall(function() PartnerEssentials.InitializePartnerSpawn() end)

  --Entree LIBRE (hors chapitre 5, ou intro deja vue et aucune scene
  --programmee) : aucune cinematique ne relacherait le mode et le joueur
  --resterait fige, incapable de bouger. On le rend donc ici, la mise en
  --place faite et l'ecran encore noir ; la branche `else` de
  --PlotScripting enchaine sur son FadeIn(20).
  --Les conditions sont EXACTEMENT celles lues par PlotScripting, pour que
  --les deux ne puissent pas diverger.
  pcall(function()
    local sceneAVenir = false
    if SV.ChapterProgression ~= nil and SV.ChapterProgression.Chapter == 5 then
      local c5 = SV.Chapter5
      sceneAVenir = (not c5.FinishedMountWindsweptIntro)
                 or c5.PlayTempMountScene
                 or (c5.MountGuardianDefeated and c5.MountVigilSceneSeen
                     and not c5.WindSecretSceneSeen)
    end
    if not sceneAVenir then GAME:CutsceneMode(false) end
  end)

end

---mount_windswept_entrance.Enter(map)
--Engine callback function
function mount_windswept_entrance.Enter(map)

  mount_windswept_entrance.PlotScripting()

end

---mount_windswept_entrance.Exit(map)
--Engine callback function
function mount_windswept_entrance.Exit(map)

end

---mount_windswept_entrance.Update(map)
--Engine callback function
function mount_windswept_entrance.Update(map)

end

---mount_windswept_entrance.GameSave(map)
--Engine callback function
function mount_windswept_entrance.GameSave(map)

	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))

end

---mount_windswept_entrance.GameLoad(map)
--Engine callback function
function mount_windswept_entrance.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	mount_windswept_entrance.PlotScripting()
end

function mount_windswept_entrance.PlotScripting()
  if SV.ChapterProgression.Chapter == 5 then
    -- RETOUR DU REVE — cette branche passe AVANT toutes les autres.
    -- La veillee (CampNightfall) se termine en envoyant le joueur sur la
    -- carte dediee `hero_dream`. Celle-ci renvoie ici une fois le reve
    -- fini. Sans cette branche, on retomberait sur ArrivalCutscene —
    -- FinishedMountWindsweptIntro n'est pose qu'a la toute fin de
    -- l'intro — et TOUTE la soiree se rejouerait en boucle.
    -- CampNightWatchDone est pose juste avant le depart vers le reve ;
    -- MorningAfterDream le consomme. Les deux drapeaux encadrent donc
    -- exactement l'aller-retour, et la scene ne peut pas se rejouer.
    if SV.Chapter5.CampNightWatchDone and not SV.Chapter5.FinishedMountWindsweptIntro then
      -- RATTRAPAGE DU REVE MANQUE (bug signale en jeu : « la scene du
      -- reve ne s'est pas lancee, il y a uniquement le reveil en sursaut
      -- au milieu de la nuit et la discussion avec Phileas »).
      --
      -- CAUSE RACINE. Deux drapeaux encadrent l'aller-retour vers la
      -- carte du reve, et ils ne sont pas poses au meme moment :
      --   * CampNightWatchDone est pose AVANT la bascule
      --     (mount_windswept_entrance_ch_5.lua:1594) ;
      --   * DreamSceneSeen n'est pose QU'APRES le reve
      --     (hero_dream/init.lua:532 en fin de scene, 561 en secours).
      -- Ce routeur ne lisait que le PREMIER. Or entre les deux se
      -- trouvent : un preflight qui peut refuser la bascule (il pose
      -- alors DreamSceneSeen et rentre — cas propre), MAIS AUSSI toute
      -- interruption qui ne pose rien (fermeture du jeu pendant le noir,
      -- bascule avortee cote moteur, sauvegarde reprise a cet instant).
      -- Dans ces cas-la on revient ici avec CampNightWatchDone = true et
      -- DreamSceneSeen = false : le routeur croyait le reve joue et
      -- enchainait droit sur ResumeAfterDream, c'est-a-dire sur le
      -- sursaut du reveil puis Phileas. Exactement le symptome decrit :
      -- le reveil sans le reve.
      --
      -- CORRECTIF. On distingue desormais « on revient du reve » de
      -- « on devait rever et on ne l'a pas fait ». Dans le second cas on
      -- renvoie vers la carte du reve au lieu de l'escamoter. Le
      -- preflight de hero_dream reste seul juge de la faisabilite : s'il
      -- refuse, il pose DreamSceneSeen et cette branche ne se represente
      -- pas — donc aucune boucle possible.
      if not SV.Chapter5.DreamSceneSeen then
        PrintInfo('[MWE5] reve non joue alors que la veillee est terminee — nouvelle tentative de bascule vers hero_dream')
        mount_windswept_entrance_ch_5.RetryDream()
        return
      end
      mount_windswept_entrance_ch_5.ResumeAfterDream()
      return
    end
    if SV.Chapter5.PlayTempMountScene then
      --RETOUR DU DONJON EN MAUVAISE POSTURE (KO/abandon) : la cinematique
      --de RESPAWN prime sur la cinematique d'entree (demande utilisateur :
      --« la cinematique d'entree ne doit pas etre rejouee, c'est celle du
      --respawn qui doit etre rejouee »). Meme si l'intro n'a jamais ete
      --jouee (partie neuve, debug warp), on ne rejoue JAMAIS ArrivalCutscene
      --au retour d'un donjon.
      --SetupGround d'abord (les PNJ du camp existent), puis la scene de
      --retour adaptee a la raison de sortie. SetupGround lit encore
      --PlayTempMountScene pour choisir entre camp du matin (apres defaite)
      --et camp de jour : on ne consomme le flag qu'APRES SetupGround, juste
      --avant la scene. Si la scene plante en cours (xpcall moteur), elle ne
      --rejouera pas au prochain chargement. Le `= false` de fin de scene
      --reste en ceinture (idempotent).
      mount_windswept_entrance_ch_5.SetupGround()
      SV.Chapter5.PlayTempMountScene = false
      if SV.Chapter5.MountLastExitReason == 'Retreated' then
        mount_windswept_entrance_ch_5.RetreatReturnCutscene()
      else
        mount_windswept_entrance_ch_5.KODefeatCutscene()
      end
    elseif not SV.Chapter5.FinishedMountWindsweptIntro then
      mount_windswept_entrance_ch_5.ArrivalCutscene()
    elseif SV.Chapter5.MountGuardianDefeated and SV.Chapter5.MountVigilSceneSeen
       and not SV.Chapter5.WindSecretSceneSeen then
      --Cinematique emotionnelle : le secret Hyko x Penticus, surprise de nuit.
      --Se joue apres la veillee du relais (l'ordre des revelations compte).
      mount_windswept_entrance_ch_5.SetupGround()
      mount_windswept_entrance_ch_5.WindSecretScene()
    else
      mount_windswept_entrance_ch_5.SetupGround()
      GAME:FadeIn(20)
    end
  else
    GAME:FadeIn(20)
  end
end 

-- Entities Callbacks
function mount_windswept_entrance.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
 end

-- QUI EST TEAMMATE2/3 ? CA CHANGE AU MILIEU DU CHAPITRE.
local function talkToTeammate(chara, activator, slot)
  if SV.ChapterProgression.Chapter ~= 5 then
    COMMON.GroundInteract(activator, chara, true)
    return
  end

  local who = nil
  pcall(function() who = LTBL(chara).Importance end)
  if who == nil or who == '' then
    --Repli : on regarde l'espece du sprite present sur la carte.
    pcall(function() who = chara.CurrentForm.Species end)
    if who == 'cranidos' then who = 'Cranidos'
    elseif who == 'mareep' then who = 'Mareep'
    elseif who == 'growlithe' then who = 'Growlithe'
    elseif who == 'zigzagoon' then who = 'Zigzagoon' end
  end

  if who == 'Cranidos' then
    mount_windswept_entrance_ch_5.Cranidos_Action(chara, activator)
  elseif who == 'Mareep' then
    mount_windswept_entrance_ch_5.Mareep_Action(chara, activator)
  elseif who == 'Zigzagoon' then
    mount_windswept_entrance_ch_5.Zigzagoon_Action(chara, activator)
  elseif who == 'Growlithe' then
    mount_windswept_entrance_ch_5.Growlithe_Action(chara, activator)
  else
    --Inconnu : on ne met JAMAIS les mots d'un autre dans sa bouche.
    COMMON.GroundInteract(activator, chara, true)
  end
end

function mount_windswept_entrance.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  talkToTeammate(chara, activator, 2)
end

function mount_windswept_entrance.Teammate3_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  talkToTeammate(chara, activator, 3)
end

--PNJ du camp de base (present uniquement au chapitre 5)
function mount_windswept_entrance.Tropius_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Tropius_Action(chara, activator)
end

function mount_windswept_entrance.Noctowl_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Noctowl_Action(chara, activator)
end

function mount_windswept_entrance.Audino_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Audino_Action(chara, activator)
end

function mount_windswept_entrance.Snubbull_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Snubbull_Action(chara, activator)
end

function mount_windswept_entrance.Mareep_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Mareep_Action(chara, activator)
end

function mount_windswept_entrance.Cranidos_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Cranidos_Action(chara, activator)
end

function mount_windswept_entrance.Breloom_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Breloom_Action(chara, activator)
end

function mount_windswept_entrance.Girafarig_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Girafarig_Action(chara, activator)
end

--PLUM (Jigglypuff). Elle n'est presente que si elle a suivi l'expedition
--jusqu'ici (SV.Chapter5.PlumAtMountCamp, arme par son irruption au repas).
--Sans ce callback, un joueur qui lui parlait tombait sur le dialogue
--generique du moteur : un personnage qu'on vient de faire exister par une
--scene entiere ne peut pas etre muet des qu'on reprend la main.
--GroundChar.cs:153 : tout personnage cree par script est TriggerType.Action,
--donc cliquable — le callback est bel et bien atteignable.
function mount_windswept_entrance.Jigglypuff_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Jigglypuff_Action(chara, activator)
end

--HYKO (Growlithe), garde du camp de base.
--
--BUG SIGNALE : « Hyko doit etre interactif au meme titre que les autres
--PNJ sur place, une fois que le joueur recupere le controle. Pour le
--moment, il est present mais ne dit rien lorsqu'on lui parle. »
--
--CAUSE EXACTE. Le camp de jour cree trois PNJ par
--MakeCharactersFromList : Tropius, Noctowl et GROWLITHE. Les deux
--premiers avaient leur callback ici, pas le troisieme. Le dialogue
--mount_windswept_entrance_ch_5.Growlithe_Action EXISTE pourtant (trois
--variantes selon l'avancement), mais rien ne l'appelait : le seul
--appelant etait talkToTeammate, qui ne sert QUE les emplacements
--Teammate2/3. Hyko n'est pas dans l'equipe au camp de jour — il est
--PNJ — donc ce chemin ne le concernait jamais. Resultat : le moteur
--retombait sur son interaction par defaut, et Hyko restait muet.
--
--Meme correctif que pour Plum quelques lignes plus haut, et meme
--justification : un personnage present a l'ecran ne peut pas etre le
--seul du camp a ne rien avoir a dire.
function mount_windswept_entrance.Growlithe_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Growlithe_Action(chara, activator)
end

function mount_windswept_entrance.Kangaskhan_Rock_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GeneralFunctions.Kangashkhan_Rock_Interact(obj, activator)
end

-- Map Transitions
function mount_windswept_entrance.Dungeon_Entrance_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  local zone = _DATA.DataIndices[RogueEssence.Data.DataManager.DataType.Zone]:Get("mount_windswept")
  UI:ResetSpeaker()
  local hero = CH('PLAYER')
  local partner = CH('Teammate1')

  -- BEAT 4.10 DU PLAN — L'ECHANGE AVANT D'ENTRER.
  -- « Shuca et/ou Galon lancent l'echange : "Alors, vous etes prets ?"
  --   ... "Bon, on y va !" Court retour en mode scene pour ce dialogue
  --   ponctuel, puis rendu de la main au joueur juste apres. Le ton est
  --   motive, tourne vers l'action a venir, pas une redite du
  --   rassemblement. »
  --
  -- Il se joue UNE SEULE FOIS, au premier passage apres l'intro : le
  -- drapeau MountDoorTalkDone l'empeche de se rejouer a chaque
  -- aller-retour du joueur devant la porte, ce qui le transformerait en
  -- verbiage. Condition d'intro terminee : sans elle, l'echange se
  -- declencherait aussi pendant les retours de donjon.
  --
  -- Ganlon et Shuca sont dans l'equipe (Teammate2/3, cf. SetParty) :
  -- ils sont donc physiquement derriere le heros a cet instant, et
  -- CharTurnToCharAnimated suffit — aucun deplacement a scripter.
  if SV.ChapterProgression.Chapter == 5
     and SV.Chapter5.FinishedMountWindsweptIntro
     and not SV.Chapter5.MountDoorTalkDone then
    local ganlon = CH('Teammate2')
    local shuca  = CH('Teammate3')
    if ganlon ~= nil or shuca ~= nil then
      SV.Chapter5.MountDoorTalkDone = true
      GAME:CutsceneMode(true)
      GAME:WaitFrames(15)
      --Shuca prend la parole la premiere : c'est elle qui a hate.
      if shuca ~= nil then
        pcall(function()
          GROUND:CharTurnToCharAnimated(shuca, hero, 4)
          GROUND:CharTurnToCharAnimated(hero, shuca, 4)
          GeneralFunctions.EmoteAndPause(shuca, "Glowing", true)
        end)
        UI:SetSpeaker(shuca)
        GeneralFunctions.SetEmotion("Joyous")
        UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['MWE5_E01']))
        GAME:WaitFrames(12)
      end
      --Ganlon rale, comme toujours — et suit, comme toujours.
      if ganlon ~= nil then
        pcall(function()
          GROUND:CharTurnToCharAnimated(ganlon, hero, 4)
          GROUND:CharTurnToCharAnimated(hero, ganlon, 4)
        end)
        UI:SetSpeaker(ganlon)
        GeneralFunctions.SetEmotion("Sigh")
        UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['MWE5_E02']))
        GAME:WaitFrames(10)
        pcall(function() GROUND:CharSetEmote(ganlon, "determined", 1) end)
        GeneralFunctions.SetEmotion("Determined")
        UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['MWE5_E03']))
        GAME:WaitFrames(12)
      end
      --Le partenaire clot, tourne vers la porte : on regarde ou on va.
      pcall(function()
        GROUND:CharTurnToCharAnimated(partner, hero, 4)
      end)
      UI:SetSpeaker(partner)
      GeneralFunctions.SetEmotion("Determined")
      UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['MWE5_E04']))
      GAME:WaitFrames(15)
      UI:ResetSpeaker()
      --PAS DE FONDU ICI, ET C'EST DELIBERE.
      --La regle « un fondu avant chaque reprise de main » vise le
      --passage cinematique -> EXPLORATION. Ce n'est pas le cas de cet
      --echange : le joueur ne reprend pas la main sur la carte, le menu
      --« Voulez-vous entrer ? » s'ouvre immediatement apres (quelques
      --lignes plus bas). Noircir puis rallumer entre la derniere
      --replique et la question ferait clignoter l'ecran pour rien, et
      --casserait l'enchainement voulu par le beat 4.10 du plan.
      GAME:CutsceneMode(false)
    end
  end

  partner.IsInteracting = true
  GROUND:CharSetAnim(partner, 'None', true)
  GROUND:CharSetAnim(hero, 'None', true)
  UI:ChoiceMenuYesNo("Voulez-vous entrer dans " .. zone:GetColoredName() .. " ?", true)
  UI:WaitForChoice()
  local yesnoResult = UI:ChoiceResult()
  if yesnoResult then
    SOUND:FadeOutBGM(60)
    GAME:FadeOut(false, 60)
    partner.IsInteracting = false
    GROUND:CharEndAnim(partner)
    GROUND:CharEndAnim(hero)
    --default partner spawn, since it should be default wherever we end up after the dungeon.
    SV.partner.Spawn = "Default"
    GAME:EnterDungeon("mount_windswept", 0, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, true, false)
  end
  partner.IsInteracting = false
  GROUND:CharEndAnim(partner)
  GROUND:CharEndAnim(hero)
end

return mount_windswept_entrance
