--[[
    init.lua
    Created: 01/03/2024 12:34:54
    Description: Autogenerated script file for the map mount_windswept_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'halcyon.PartnerEssentials'
require 'halcyon.GeneralFunctions'
require 'halcyon.ground.mount_windswept_entrance.mount_windswept_entrance_ch_5'

-- Package name
local mount_windswept_entrance = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---mount_windswept_entrance.Init(map)
--Engine callback function
--Les scenes de cette carte qui commencent ECRAN NOIR. Si l'une d'elles
--va se jouer, Init doit garantir le noir AVANT le premier rendu.
local function needsBlackOnEntry()
  --Lire un champ d'une table ABSENTE crashe (regle projet §2.4) : sur
  --une sauvegarde anterieure a ces flags, SV.Chapter5 pourrait manquer.
  --Init ne doit jamais lever d'erreur — la carte deviendrait injouable.
  local ok, res = pcall(function()
    if SV.ChapterProgression == nil or SV.ChapterProgression.Chapter ~= 5 then
      return false
    end
    local c5 = SV.Chapter5
    if c5 == nil then return false end
    if not c5.FinishedMountWindsweptIntro then return true end
    if c5.PlayTempMountScene then return true end
    if c5.MountGuardianDefeated and c5.MountVigilSceneSeen
       and not c5.WindSecretSceneSeen then return true end
    return false
  end)
  return ok and res or false
end

function mount_windswept_entrance.Init(map)
  DEBUG.EnableDbgCoro()
  print('=>> Init_mount_windswept_entrance <<=')

  ------------------------------------------------------------------
  -- L'ECRAN EST NOIR AVANT LE PREMIER RENDU.
  ------------------------------------------------------------------
  -- BUG VU EN JEU : « le fond noir n'est pas maintenu, on revoit le
  -- ground du tunnel avant d'arriver ». Poser le FadeOut en tete de
  -- ArrivalCutscene ne suffisait pas — et la lecture du moteur dit
  -- pourquoi (RogueCollab/RogueEssence) :
  --
  --   GameManager.moveToZoneInit:773
  --       InitGround()   -> appelle CE Init(map)
  --       // « no fade; the script handles that itself »
  --       BeginGround()  -> appelle Enter(map), donc PlotScripting,
  --                         donc seulement LA notre cinematique
  --
  --   GSceneZone.EnterGround:27  -> ResetGround()
  --       ViewCenter = null : la camera SAUTE sur le joueur
  --
  -- Autrement dit, la carte est chargee, la camera repositionnee et le
  -- premier rendu possible AVANT que Enter() ne s'execute. Tout fondu
  -- pose dans la cinematique arrive donc une frame trop tard. Et le
  -- moteur, lui, n'en pose aucun : il laisse ce que le script a laisse.
  --
  -- On pose donc le noir ICI, dans Init, avant COMMON.RespawnAllies et
  -- avant le placement du partenaire. FadeOut(false, 1) est instantane
  -- et idempotent : si l'ecran est deja noir (cas normal, le Crucible
  -- l'a laisse ainsi), il ne fait rien de visible.
  --
  -- CONDITIONNE : uniquement si une cinematique qui commence dans le
  -- noir va suivre. Sinon on noircirait une entree normale sur la carte
  -- (retour de donjon, promenade) dont la branche `else` de
  -- PlotScripting ne fait qu'un FadeIn(20) — l'ecran resterait noir une
  -- demi-seconde sans raison.
  if needsBlackOnEntry() then
    pcall(function() GAME:FadeOut(false, 1) end)
  end

  COMMON.RespawnAllies()
  GROUND:AddMapStatus("blowing_wind")
  PartnerEssentials.InitializePartnerSpawn()

end

---mount_windswept_entrance.Enter(map)
--Engine callback function
function mount_windswept_entrance.Enter(map)

  mount_windswept_entrance.PlotScripting()

end

---mount_windswept_entrance.Exit(map)
--Engine callback function
function mount_windswept_entrance.Exit(map)


end

---mount_windswept_entrance.Update(map)
--Engine callback function
function mount_windswept_entrance.Update(map)


end

---mount_windswept_entrance.GameSave(map)
--Engine callback function
function mount_windswept_entrance.GameSave(map)

	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))

end

---mount_windswept_entrance.GameLoad(map)
--Engine callback function
function mount_windswept_entrance.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	mount_windswept_entrance.PlotScripting()
end

function mount_windswept_entrance.PlotScripting()
  if SV.ChapterProgression.Chapter == 5 then
    if not SV.Chapter5.FinishedMountWindsweptIntro then
      mount_windswept_entrance_ch_5.ArrivalCutscene()
    elseif SV.Chapter5.PlayTempMountScene then
      --Retour de la premiere moitie du donjon en mauvaise posture
      --(KO/temps ecoule ou repli volontaire). Miroir du routeur du
      --Tunnel : SetupGround d'abord (les PNJ du camp existent), puis
      --la cinematique de retour adaptee a la raison de sortie.
      mount_windswept_entrance_ch_5.SetupGround()
      if SV.Chapter5.MountLastExitReason == 'Retreated' then
        mount_windswept_entrance_ch_5.RetreatReturnCutscene()
      else
        mount_windswept_entrance_ch_5.KODefeatCutscene()
      end
    elseif SV.Chapter5.MountGuardianDefeated and SV.Chapter5.MountVigilSceneSeen
       and not SV.Chapter5.WindSecretSceneSeen then
      --Cinematique emotionnelle : le secret Hyko x Penticus, surprise de nuit.
      --Se joue apres la veillee du relais (l'ordre des revelations compte).
      mount_windswept_entrance_ch_5.SetupGround()
      mount_windswept_entrance_ch_5.WindSecretScene()
    else
      mount_windswept_entrance_ch_5.SetupGround()
      GAME:FadeIn(20)
    end
  else
    GAME:FadeIn(20)
  end
end 


-------------------------------
-- Entities Callbacks
-------------------------------
function mount_windswept_entrance.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
 end

function mount_windswept_entrance.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  if SV.ChapterProgression.Chapter == 5 then
    mount_windswept_entrance_ch_5.Growlithe_Action(chara, activator)
  else
    COMMON.GroundInteract(activator, chara, true)
  end
end

function mount_windswept_entrance.Teammate3_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  if SV.ChapterProgression.Chapter == 5 then
    mount_windswept_entrance_ch_5.Zigzagoon_Action(chara, activator)
  else
    COMMON.GroundInteract(activator, chara, true)
  end
end

--PNJ du camp de base (present uniquement au chapitre 5)
function mount_windswept_entrance.Tropius_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Tropius_Action(chara, activator)
end

function mount_windswept_entrance.Noctowl_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Noctowl_Action(chara, activator)
end

function mount_windswept_entrance.Audino_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Audino_Action(chara, activator)
end

function mount_windswept_entrance.Snubbull_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Snubbull_Action(chara, activator)
end

function mount_windswept_entrance.Mareep_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Mareep_Action(chara, activator)
end

function mount_windswept_entrance.Cranidos_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Cranidos_Action(chara, activator)
end

function mount_windswept_entrance.Breloom_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Breloom_Action(chara, activator)
end

function mount_windswept_entrance.Girafarig_Action(chara, activator)
  DEBUG.EnableDbgCoro()
  mount_windswept_entrance_ch_5.Girafarig_Action(chara, activator)
end

function mount_windswept_entrance.Kangaskhan_Rock_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GeneralFunctions.Kangashkhan_Rock_Interact(obj, activator)
end

---------------------------
-- Map Transitions
---------------------------
function mount_windswept_entrance.Dungeon_Entrance_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  local zone = _DATA.DataIndices[RogueEssence.Data.DataManager.DataType.Zone]:Get("mount_windswept")
  UI:ResetSpeaker()
  local hero = CH('PLAYER')
  local partner = CH('Teammate1')
  partner.IsInteracting = true
  GROUND:CharSetAnim(partner, 'None', true)
  GROUND:CharSetAnim(hero, 'None', true)
  UI:ChoiceMenuYesNo("Voulez-vous entrer dans " .. zone:GetColoredName() .. " ?", true)
  UI:WaitForChoice()
  local yesnoResult = UI:ChoiceResult()
  if yesnoResult then
    SOUND:FadeOutBGM(60)
    GAME:FadeOut(false, 60)
    partner.IsInteracting = false
    GROUND:CharEndAnim(partner)
    GROUND:CharEndAnim(hero)
    --default partner spawn, since it should be default wherever we end up after the dungeon.
    SV.partner.Spawn = "Default"
    GAME:EnterDungeon("mount_windswept", 0, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, true, false)
  end
  partner.IsInteracting = false
  GROUND:CharEndAnim(partner)
  GROUND:CharEndAnim(hero)
end

return mount_windswept_entrance

