-- PMU Ground Controller for pmu_s1000 (Grassroot Housing Center)
-- Generated by PMU Pipeline (New Era)
local pmu_s1000 = {}

function pmu_s1000.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1000.Enter(map)
  local music = 'PMDB) Rescue Team Base.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1000.Update(map, time)
end

function pmu_s1000.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s737', 'Entrance', false)
end

function pmu_s1000.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s737', 'Entrance', false)
end

function pmu_s1000.Sign_1_Action(obj, activator)
  UI:WaitShowDialogue('Housing Center Tips.')
  UI:WaitShowDialogue('Use /edithouse to edit your own house.')
  UI:WaitShowDialogue('Use /leavehouse to return to the housing center from any house.')
end

function pmu_s1000.Sign_2_Action(obj, activator)
  UI:WaitShowDialogue('Housing Center Tips.')
  UI:WaitShowDialogue('Use /edithouse to edit your own house.')
  UI:WaitShowDialogue('Use /leavehouse to return to the housing center from any house.')
end

function pmu_s1000.Sign_3_Action(obj, activator)
  UI:WaitShowDialogue('Note:')
  UI:WaitShowDialogue('Do not save your house when there are items on the ground.')
  UI:WaitShowDialogue('You will lose them. So Make sure to pick them up before saving your house. Thank You.')
end

function pmu_s1000.Sign_4_Action(obj, activator)
  UI:WaitShowDialogue('Step right up to the desk to purchase a guild!')
  UI:WaitShowDialogue('A guild may have co-leaders, but can only be obtained at the creation point of the guild when partied with the founder.')
  UI:WaitShowDialogue('Each leader of the guild must also be of master rank, as well as having 100,000 poke.')
end

return pmu_s1000
