--[[
    Ground Controller: Starter Village (pixellab_starter_town)
    Procedurally generated by PMDO Town Generator (Seed: 184729)
]]

require 'origin.common'

local pixellab_starter_town = {}

function pixellab_starter_town.Init(map)
    DEBUG.EnableDbgCoro()
    PrintInfo("=>> Initializing ground pixellab_starter_town")
end

function pixellab_starter_town.Enter(map)
    GROUND:Hide('PLAYER')
    local player = CH('PLAYER')
    if player then
        GROUND:TeleportTo(player, 768, 979, Direction.Up)
    end
    GAME:FadeIn(20)
end

function pixellab_starter_town.Exit(map)
    GAME:FadeOut(20)
end

return pixellab_starter_town
