--[[
    init.lua
    Created: 12/23/2023 14:32:40
    Description: Autogenerated script file for the map searing_crucible.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'halcyon.PartnerEssentials'
require 'halcyon.ReplayEnding'
require 'halcyon.ground.searing_crucible.searing_crucible_ch_5'

-- [NREPROBE] sonde locale : état complet de la scène à un point donné.
local function nre_snap(tag)
  local ok, msg = pcall(function()
    local zone = tostring(_ZONE.CurrentZoneID)
    local seg = tostring(_ZONE.CurrentMapID.Segment)
    local save_n = _DATA.Save.ActiveTeam.Players.Count
    local leader = '<nil>'
    if _DATA.Save.ActiveTeam.Leader ~= nil then
      leader = _DATA.Save.ActiveTeam.Leader:GetDisplayName(true)
    end
    local hero = CH('PLAYER')
    local partner = CH('Teammate1')
    return string.format('[NREPROBE][%s] zone=%s seg=%s Save.Team=%d leader=%s hero=%s partner=%s',
      tag, zone, seg, save_n, leader,
      hero ~= nil and 'OK' or 'NIL', partner ~= nil and 'OK' or 'NIL')
  end)
  PrintInfo(ok and msg or ('[NREPROBE]['..tag..'] snapshot FAILED: '..tostring(msg)))
end

-- Package name
local searing_crucible = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']

-- Map Callbacks
---searing_crucible.Init(map)
--Engine callback function
function searing_crucible.Init(map)
  nre_snap('searing_crucible.Init')
  DEBUG.EnableDbgCoro()
  print('=>> Init_searing_crucible <<=')

  -- ECRAN NOIR AVANT LE PREMIER RENDU (meme correctif qu'au Mont).
  -- Les trois scenes de cette carte (FirstPreBossScene,
  -- SecondPreBossScene, DefeatedBoss) ouvrent toutes par un FadeIn :
  -- elles SUPPOSENT donc un ecran noir a l'arrivee. Mais le moteur
  -- charge la carte, repositionne la camera (EnterGround ->
  -- ResetGround, ViewCenter=null) et peut dessiner AVANT que Enter()
  -- n'appelle PlotScripting — le commentaire de moveToZoneInit est
  -- explicite : « no fade; the script handles that itself ».
  -- Sans ce noir pose des Init, le joueur apercoit le Creuset et le
  -- saut de camera avant que la scene ne commence. Instantane et
  -- idempotent : si l'ecran est deja noir, rien de visible.
  -- Conditionne au chapitre 5 hors rejouabilite : les autres cas
  -- tombent sur la branche `else` de PlotScripting, un simple
  -- FadeIn(20), et n'ont pas a etre noircis.
  pcall(function()
    if SV.ChapterProgression ~= nil and SV.ChapterProgression.Chapter == 5
       and not ReplayEnding.IsReplay('searing_tunnel', 5) then
      GAME:FadeOut(false, 1)
    end
  end)

  COMMON.RespawnAllies(true)
  GROUND:AddMapStatus("steam")
  PartnerEssentials.InitializePartnerSpawn()

end

---searing_crucible.Enter(map)
--Engine callback function
function searing_crucible.Enter(map)
  nre_snap('searing_crucible.Enter')

  searing_crucible.PlotScripting()

end

---searing_crucible.Exit(map)
--Engine callback function
function searing_crucible.Exit(map)

end

---searing_crucible.Update(map)
--Engine callback function
function searing_crucible.Update(map)

end

---searing_crucible.GameSave(map)
--Engine callback function
function searing_crucible.GameSave(map)

	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))

end

---searing_crucible.GameLoad(map)
--Engine callback function
function searing_crucible.GameLoad(map)
	--Chargement d'une partie sauvegardee SUR cette carte : Init n'est pas
	--rejoue, donc les allies (Teammate1-3) n'existeraient pas au sol et la
	--cinematique post-boss (CH('Teammate2')/CH('Teammate3')) serait ecourtee
	--par son pcall. On les fait reapparaitre comme le fait Init.
	COMMON.RespawnAllies(true)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	searing_crucible.PlotScripting()
end

function searing_crucible.PlotScripting()
	-- Rejouabilite : l'expedition est bouclee, le Creuset est desert. Sans cette
	-- branche, la carte hors chapitre 5 tombait dans le `else` (simple FadeIn)
	-- et n'offrait AUCUNE sortie au joueur.
	if ReplayEnding.IsReplay('searing_tunnel', 5) then
		ReplayEnding.EmptyArena({
			hero = {84, 120}, partner = {52, 120},
			camera = {68, 96}, look = {68, 72},
			walk = 32, title = true, music = 'In the Depths of the Pit.ogg',
			lines = {
				{ spk='partner', emo='Normal', key='SC5_R01', wait=10 },
				{ spk='hero',    emo='Normal', key='SC5_R02', wait=10 },
				{ spk='partner', emo='Normal', key='SC5_R03' },
				{ spk='narrator',              key='SC5_R04' },
			},
		})
		return
	end
	if SV.ChapterProgression.Chapter == 5 then
		if SV.Chapter5.DefeatedBoss then 
			searing_crucible_ch_5.DefeatedBoss()
		elseif not SV.Chapter5.EncounteredBoss then
			searing_crucible_ch_5.FirstPreBossScene()
		else
			searing_crucible_ch_5.SecondPreBossScene()
		end
	else
		GAME:FadeIn(20)
	end
end 

-- Entities Callbacks
function searing_crucible.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
 end

function searing_crucible.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function searing_crucible.Teammate3_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

return searing_crucible
