-- PMU Ground Controller for pmu_s255 (Seaside Cavern Pit)
-- Generated by PMU Pipeline (New Era)
local pmu_s255 = {}

function pmu_s255.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s255.Enter(map)
  local music = 'PMDB) Versus Boss.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s255.Update(map, time)
end

return pmu_s255
