-- PMU Ground Controller for pmu_s1787 (Boggy Wastes [Final Reward Map])
-- Generated by PMU Pipeline (New Era)
local pmu_s1787 = {}

function pmu_s1787.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1787.Enter(map)
  local music = 'BW) Farewell.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1787.Update(map, time)
end

return pmu_s1787
