--[[
    Ground Controller: Batch Town (batch_town_seed_003)
    Procedurally generated by PMDO Town Generator (Seed: 102716)
]]

require 'origin.common'

local batch_town_seed_003 = {}

function batch_town_seed_003.Init(map)
    DEBUG.EnableDbgCoro()
    PrintInfo("=>> Initializing ground batch_town_seed_003")
end

function batch_town_seed_003.Enter(map)
    GROUND:Hide('PLAYER')
    local player = CH('PLAYER')
    if player then
        GROUND:TeleportTo(player, 768, 979, Direction.Up)
    end
    GAME:FadeIn(20)
end

function batch_town_seed_003.Exit(map)
    GAME:FadeOut(20)
end

return batch_town_seed_003
