--[[
    init.lua
    Created: 06/24/2022 14:47:08
    Description: Autogenerated script file for the map metano_inn.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'halcyon.PartnerEssentials'
require 'halcyon.GeneralFunctions'--ChapterDispatch (repli des PNJ permanents hors chapitres couverts)
require 'halcyon.ground.metano_inn.metano_inn_ch_2'
require 'halcyon.ground.metano_inn.metano_inn_ch_3'
require 'halcyon.ground.metano_inn.metano_inn_ch_4'
require 'halcyon.ground.metano_inn.metano_inn_ch_5'
require 'halcyon.ground.metano_inn.metano_inn_ch_6'
require 'halcyon.TownVoicesNight'

-- Package name
local metano_inn = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---metano_inn.Init
--Engine callback function
function metano_inn.Init(map, time)
	DEBUG.EnableDbgCoro()
	print('=>> Init_metano_inn <<=')
	
	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()
	
	if SOUND:GetCurrentSong() ~= SV.metano_town.Song then
      SOUND:PlayBGM(SV.metano_town.Song, true)
    end
end

---metano_inn.Enter
--Engine callback function
function metano_inn.Enter(map, time)
	metano_inn.PlotScripting()

end

---metano_inn.Exit
--Engine callback function
function metano_inn.Exit(map, time)


end

---metano_inn.Update
--Engine callback function
function metano_inn.Update(map, time)


end

function metano_inn.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	metano_inn.PlotScripting()
end

function metano_inn.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end


function metano_inn.PlotScripting()
	if SV.ChapterProgression.Chapter == 2 then 
		metano_inn_ch_2.SetupGround()
	elseif SV.ChapterProgression.Chapter == 3 then
		metano_inn_ch_3.SetupGround()
	elseif SV.ChapterProgression.Chapter == 4 then
		metano_inn_ch_4.SetupGround()	
	elseif SV.ChapterProgression.Chapter == 5 then
		metano_inn_ch_5.SetupGround()
	elseif SV.ChapterProgression.Chapter == 6 then
		metano_inn_ch_6.SetupGround()
	else
		GAME:FadeIn(20)
	end
end


-------------------------------
-- Map Transitions
-------------------------------

function metano_inn.Inn_Entrance_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("metano_town", "Inn_Entrance_Marker", true)
  SV.partner.Spawn = 'Inn_Entrance_Marker_Partner'
end



------------------
--NPCS 
----------------
function metano_inn.Nidoking_Action(chara, activator)
  --LA VILLE PARLE DE LA NUIT. Ces habitants tiennent l'auberge : ils
  --sont sur metano_inn, pas sur la carte de ville. Sans ce branchement
  --ils resteraient muets sur un raid, alors qu'ils l'ont vecu aussi.
  if TownVoicesNight.Talk('Nidoking') then return end
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GeneralFunctions.ChapterDispatch("metano_inn_ch_", "Nidoking_Action", chara, activator,
    function(c)
      GeneralFunctions.StartConversation(c, "Bienvenue a l'auberge ![pause=0] Il reste toujours un lit pour la guilde.", "Happy")
      GeneralFunctions.EndConversation(c)
    end)
end

function metano_inn.Nidoqueen_Action(chara, activator)
  --LA VILLE PARLE DE LA NUIT. Ces habitants tiennent l'auberge : ils
  --sont sur metano_inn, pas sur la carte de ville. Sans ce branchement
  --ils resteraient muets sur un raid, alors qu'ils l'ont vecu aussi.
  if TownVoicesNight.Talk('Nidoqueen') then return end
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GeneralFunctions.ChapterDispatch("metano_inn_ch_", "Nidoqueen_Action", chara, activator,
    function(c)
      GeneralFunctions.StartConversation(c, "Les chambres sont pretes.[pause=15] Mon mari s'occupe du registre,[pause=10] moi du reste.", "Normal")
      GeneralFunctions.EndConversation(c)
    end)
end

function metano_inn.Nidoran_M_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  assert(pcall(load("metano_inn_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Nidoran_M_Action(...,...)"), chara, activator))
end

function metano_inn.Nidorina_Action(chara, activator)
  --LA VILLE PARLE DE LA NUIT. Ces habitants tiennent l'auberge : ils
  --sont sur metano_inn, pas sur la carte de ville. Sans ce branchement
  --ils resteraient muets sur un raid, alors qu'ils l'ont vecu aussi.
  if TownVoicesNight.Talk('Nidorina') then return end
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GeneralFunctions.ChapterDispatch("metano_inn_ch_", "Nidorina_Action", chara, activator,
    function(c)
      GeneralFunctions.StartConversation(c, "J'aide a l'auberge quand je peux ![pause=0] Enfin...[pause=10] surtout quand papa regarde.", "Happy")
      GeneralFunctions.EndConversation(c)
    end)
end


--the innkeeper desks are what you use to talk to the NPC behind the desk
--Les deux comptoirs sont des GroundObjects PERMANENTS du .rsground
--(triggerType 1). Il n'existe de fichier de chapitre que pour ch2 a ch5 :
--du ch6 au ch10 l'auberge etait donc totalement muette, alors que c'est un
--service de la ville. Repli ajoute via GeneralFunctions.ChapterDispatch.
function metano_inn.Innkeeper_Desk_Left_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GeneralFunctions.ChapterDispatch("metano_inn_ch_", "Innkeeper_Desk_Left_Action", chara, activator,
    function(c)
      GeneralFunctions.StartConversation(c, "Une chambre ?[pause=0] Il y a toujours de la place pour la guilde.", "Happy")
      UI:WaitShowDialogue("Reposez-vous autant qu'il vous faut.[pause=15] La route ne va nulle part sans vous.")
      GeneralFunctions.EndConversation(c)
    end)
end

function metano_inn.Innkeeper_Desk_Right_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GeneralFunctions.ChapterDispatch("metano_inn_ch_", "Innkeeper_Desk_Right_Action", chara, activator,
    function(c)
      GeneralFunctions.StartConversation(c, "Le registre est a jour,[pause=10] si c'est ce que vous cherchez.", "Normal")
      UI:WaitShowDialogue("Beaucoup de passage ces temps-ci.[pause=15] Des tetes qu'on ne connait pas.")
      GeneralFunctions.EndConversation(c)
    end)
end


function metano_inn.Zangoose_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  assert(pcall(load("metano_inn_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Zangoose_Action(...,...)"), chara, activator))
end

function metano_inn.Seviper_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  assert(pcall(load("metano_inn_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Seviper_Action(...,...)"), chara, activator))
end

--passersby are NPCs who are one-off NPCs who are people passing through town that are staying at the inn. These could be adventuring teams or it could be random NPCs
function metano_inn.Passerby_1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  assert(pcall(load("metano_inn_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Passerby_1_Action(...,...)"), chara, activator))
end

function metano_inn.Passerby_2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  assert(pcall(load("metano_inn_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Passerby_2_Action(...,...)"), chara, activator))
end







function metano_inn.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))end

return metano_inn

