-- PMU Ground Controller for pmu_s1 (The Crossroads)
-- Generated by PMU Pipeline (New Era)
local pmu_s1 = {}

function pmu_s1.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1.Enter(map)
  local music = 'PMD2) Boss Battle!.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1.Update(map, time)
end

return pmu_s1
