-- PMU Ground Controller for pmu_s1991 (Winden, Snowbasin Town)
-- Generated by PMU Pipeline (New Era)
local pmu_s1991 = {}

function pmu_s1991.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1991.Enter(map)
  local music = 'PMU) Winden Snowfall.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1991.Update(map, time)
end

function pmu_s1991.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s278', 'Entrance', false)
end

function pmu_s1991.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1334', 'Entrance', false)
end

function pmu_s1991.Warp_3_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s321', 'Entrance', false)
end

function pmu_s1991.Warp_4_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1333', 'Entrance', false)
end

function pmu_s1991.Warp_5_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s56', 'Entrance', false)
end

function pmu_s1991.Warp_6_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s319', 'Entrance', false)
end

function pmu_s1991.Sign_1_Action(obj, activator)
  UI:WaitShowDialogue('Winden Sauna')
  UI:WaitShowDialogue('And Lickilicky\'s Drool Service')
end

function pmu_s1991.Sign_2_Action(obj, activator)
  UI:WaitShowDialogue('Winden Town Hall')
end

function pmu_s1991.Sign_3_Action(obj, activator)
  UI:WaitShowDialogue('North: Winden Sauna')
end

function pmu_s1991.Sign_4_Action(obj, activator)
  UI:WaitShowDialogue('North: Winden Sauna')
end

function pmu_s1991.Sign_5_Action(obj, activator)
  UI:WaitShowDialogue('East: Snowball Game')
  UI:WaitShowDialogue('---->')
  UI:WaitShowDialogue('Follow the path.')
end

function pmu_s1991.Sign_6_Action(obj, activator)
  UI:WaitShowDialogue('East: Snowball Game')
  UI:WaitShowDialogue('---->')
  UI:WaitShowDialogue('Follow the path.')
end

function pmu_s1991.Sign_7_Action(obj, activator)
  UI:WaitShowDialogue('NeverMeltIce Pillar')
  UI:WaitShowDialogue('Winden\'s Pride and Glory')
  UI:WaitShowDialogue('This ice pillar has stood here in Snowbasin Town since the day it was founded.')
end

return pmu_s1991
