-- PMU Ground Controller for pmu_s1145 (Grassroot Town, Trishian's  House)
-- Generated by PMU Pipeline (New Era)
local pmu_s1145 = {}

function pmu_s1145.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1145.Enter(map)
  local music = 'PMD3) So Come! Post Town.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1145.Update(map, time)
end

function pmu_s1145.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s737', 'Entrance', false)
end

function pmu_s1145.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s737', 'Entrance', false)
end

return pmu_s1145
