-- PMU Ground Controller for pmu_s17 (Pok? Town Square)
-- Generated by PMU Pipeline (New Era)
local pmu_s17 = {}

function pmu_s17.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s17.Enter(map)
  local music = 'PMD) Pokemon Plaza.mp3'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s17.Update(map, time)
end

function pmu_s17.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s412', 'Entrance', false)
end

function pmu_s17.Sign_1_Action(obj, activator)
  UI:WaitShowDialogue('<-- Dojo')
  UI:WaitShowDialogue('v Shops and post office')
  UI:WaitShowDialogue('Read other sign for more!')
end

function pmu_s17.Sign_2_Action(obj, activator)
  UI:WaitShowDialogue('--> Housing district')
  UI:WaitShowDialogue('Read other sign for more!')
end

function pmu_s17.Sign_3_Action(obj, activator)
  UI:WaitShowDialogue('New shadows arise! More friends to make! Generation 5... coming soon!')
end

return pmu_s17
