--[[
    Ground Controller: Amber Valley Village (amber_valley_village)
    Procedurally generated by PMDO Town Generator (Seed: 555888)
]]

require 'origin.common'

local amber_valley_village = {}

function amber_valley_village.Init(map)
    DEBUG.EnableDbgCoro()
    PrintInfo("=>> Initializing ground amber_valley_village")
end

function amber_valley_village.Enter(map)
    GROUND:Hide('PLAYER')
    local player = CH('PLAYER')
    if player then
        GROUND:TeleportTo(player, 768, 979, Direction.Up)
    end
    GAME:FadeIn(20)
end

function amber_valley_village.Exit(map)
    GAME:FadeOut(20)
end

return amber_valley_village
