-- PMU Ground Controller for pmu_s1980 (Sea)
-- Generated by PMU Pipeline (New Era)
local pmu_s1980 = {}

function pmu_s1980.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1980.Enter(map)
  local music = 'PMD2) Whose Footprint Whose Footprint (Sentry Duty).mp3'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1980.Update(map, time)
end

return pmu_s1980
