--[[
    init.lua
    Created: 06/28/2021 23:00:22
    Description: Autogenerated script file for the map guild_bottom_right_bedroom.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'halcyon.PartnerEssentials'
require 'halcyon.CharacterEssentials'
require 'halcyon.ground.guild_bottom_right_bedroom.guild_bottom_right_bedroom_ch_3'
require 'halcyon.ground.guild_bottom_right_bedroom.guild_bottom_right_bedroom_ch_4'

-- Package name
local guild_bottom_right_bedroom = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---guild_bottom_right_bedroom.Init
--Engine callback function
function guild_bottom_right_bedroom.Init(map)
	DEBUG.EnableDbgCoro()
	print('=>> Init_guild_bottom_right_bedroom<<=')

	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()

end

---guild_bottom_right_bedroom.Enter
--Engine callback function
function guild_bottom_right_bedroom.Enter(map)
	guild_bottom_right_bedroom.PlotScripting()
end

---guild_bottom_right_bedroom.Exit
--Engine callback function
function guild_bottom_right_bedroom.Exit(map)


end

---guild_bottom_right_bedroom.Update
--Engine callback function
function guild_bottom_right_bedroom.Update(map)


end

function guild_bottom_right_bedroom.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	guild_bottom_right_bedroom.PlotScripting()
end

function guild_bottom_right_bedroom.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end

function guild_bottom_right_bedroom.PlotScripting()
	if SV.ChapterProgression.Chapter == 3 then
		guild_bottom_right_bedroom_ch_3.SetupGround()
	elseif SV.ChapterProgression.Chapter == 4 then
		guild_bottom_right_bedroom_ch_4.SetupGround()
	else
		GAME:FadeIn(20)
	end
end


-------------------------------
-- Entities Callbacks
-------------------------------
function guild_bottom_right_bedroom.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
end

function guild_bottom_right_bedroom.Zigzagoon_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  assert(pcall(load("guild_bottom_right_bedroom_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Zigzagoon_Action(...,...)"), chara, activator))
end

function guild_bottom_right_bedroom.Growlithe_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  assert(pcall(load("guild_bottom_right_bedroom_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Growlithe_Action(...,...)"), chara, activator))
end

--function guild_bottom_right_bedroom.Almanac_Action(chara, activator)
	--UI:ResetSpeaker(false)
	--UI:WaitShowDialogue("This is Almotz's almanac (along with the books/papers on the floor)")
	--UI:WaitShowDialogue("But there's a lot of work that needs to go into this almanac...")
	--UI:WaitShowDialogue("Which will be done at a later date.[pause=0] It'll have some lore,[pause=10] gameplay tips,[pause=10] etc.")
	--UI:WaitShowDialogue("So look forward to it!")
--end



--[[
local AlmanacMenu = Class('AlmanacMenu')

function AlmanacMenu:initialize(items)
  assert(self, "ExampleMenu:initialize(): Error, self is nil!")
  self.menu = RogueEssence.Menu.ScriptableMenu(24, 24, 196, 128, function(input) self:Update(input) end)
  self.cursor = RogueEssence.Menu.MenuCursor(self.menu)
  self.menu.Elements:Add(self.cursor)
  for i = 1, #items, 1 do
	self.menu.Elements:Add(RogueEssence.Menu.MenuText(items[i], RogueElements.Loc(16, 8 + 14 * (i-1))))
  end
  self.total_items = #items
  self.current_item = 0
  self.cursor.Loc = RogueElements.Loc(8, 8)

end

function AlmanacMenu:Update(input)
    assert(self, "BaseState:Begin(): Error, self is nil!")
	if input:JustPressed(RogueEssence.FrameInput.InputType.Confirm) then
    _GAME:SE("Menu/Confirm")
  elseif input:JustPressed(RogueEssence.FrameInput.InputType.Cancel) then
    _GAME:SE("Menu/Cancel")
    _MENU:RemoveMenu()
  else
    moved = false
    if RogueEssence.Menu.InteractableMenu.IsInputting(input, LUA_ENGINE:MakeLuaArray(Dir8, { Dir8.Down, Dir8.DownLeft, Dir8.DownRight })) then
      moved = true
      self.current_item = (self.current_item + 1) % self.total_items
    elseif RogueEssence.Menu.InteractableMenu.IsInputting(input, LUA_ENGINE:MakeLuaArray(Dir8, { Dir8.Up, Dir8.UpLeft, Dir8.UpRight })) then
      moved = true
      self.current_item = (self.current_item + self.total_items - 1) % self.total_items
    end
    if moved then
      _GAME:SE("Menu/Select")
      self.cursor:ResetTimeOffset()
      self.cursor.Loc = RogueElements.Loc(8, 8 + 14 * self.current_item)
    end
  end
end

--]]




function guild_bottom_right_bedroom.Team_Almanac_Action(obj, activator)
	UI:ResetSpeaker(false)
	UI:SetCenter(true)
	UI:SetAutoFinish(true)
	local hero = CH('PLAYER')
	local partner = CH('Teammate1')
	partner.IsInteracting = true
	GROUND:CharSetAnim(partner, 'None', true)
	GROUND:CharSetAnim(hero, 'None', true)
    GeneralFunctions.TurnTowardsLocation(hero, obj.Position.X + obj.Width // 2, obj.Position.Y + obj.Height // 2)
    GeneralFunctions.TurnTowardsLocation(partner, obj.Position.X + obj.Width // 2, obj.Position.Y + obj.Height // 2)

	local zig_name = CharacterEssentials.GetCharacterName("Zigzagoon")
	local choices = {'Round', 'Cadence', 'Starlight', 'Rivals', 'Flutter', 'Flight'}

	--local team_name_length = string.len(GAME:GetTeamName())
	--local player_team_name = string.sub(GAME:GetTeamName(), 16, team_name_length - 7)

	--add player's team and team style in chapter 2
	if SV.ChapterProgression.Chapter >= 2 then
		table.insert(choices, #choices + 1, 'Style')
		table.insert(choices, #choices + 1, GAME:GetTeamName())
	end

	--cancel goes at end of choice list always
	table.insert(choices, #choices + 1, 'Never Mind')

	--Don't read his books until he tells you you can.
	if not SV.Chapter1.MetZigzagoon then
		UI:WaitShowDialogue("Cela semble être le livre de quelqu'un d'autre.\nMieux vaut ne pas le lire sans leur autorisation.")
		UI:SetCenter(false)
		UI:SetAutoFinish(false)
		partner.IsInteracting = false
		GROUND:CharEndAnim(partner)
		GROUND:CharEndAnim(hero)
		return
	end

	UI:ChoiceMenuYesNo("C'est l'un des almanachs de " .. zig_name .. ".\nIl s'intitule « Équipes d'aventure ». Le lire ?")
	UI:WaitForChoice()
	local result = UI:ChoiceResult()
	UI:SetAutoFinish(false)
	if result then
		  GROUND:ObjectSetDefaultAnim(obj, 'Diary_Red_Opening', 0, 0, 0, Direction.Right)
	      GROUND:ObjectSetAnim(obj, 6, 0, 3, Direction.Right, 1)
		  GROUND:ObjectSetDefaultAnim(obj, 'Diary_Red_Opening', 0, 3, 3, Direction.Right)
		  GAME:WaitFrames(40)
		  UI:BeginMultiPageMenu(24, 24, 196, "Almanach de l'équipe", choices, 8, 1, #choices)
		  UI:WaitForChoice()

		  local entry = choices[UI:ChoiceResult()]

		  if entry == 'Round' then
			local marill_species = _DATA:GetMonster('marill'):GetColoredName()
			local puff_species = _DATA:GetMonster('jigglypuff'):GetColoredName()
			local spheal_species = _DATA:GetMonster('spheal'):GetColoredName()
			local move = _DATA.DataIndices[RogueEssence.Data.DataManager.DataType.Skill]:Get("round")--

			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nInscription par équipe :[color=#FFA5FF]Round[color]")
			UI:SetCenter(false)
			UI:WaitShowDialogue("L'équipe[color=#FFA5FF]Round[color]est une équipe locale qui prend généralement le travail du Job Bulletin Board et se compose de trois membres.")
			UI:WaitShowDialogue("Tout d'abord,[pause=10]il y a " .. CharacterEssentials.GetCharacterName("Jigglypuff") .. ".[pause=0]C'est une " .. puff_species .. "![pause=0]Elle est très gentille et essaie d'être utile à tous les Pokémon qu'elle rencontre.")
			UI:WaitShowDialogue("Et puis il y a le " .. spheal_species .. " nommé " .. CharacterEssentials.GetCharacterName("Spheal") .. ".[pause=0]. J'ai l'impression qu'il pense plus avec son ventre qu'avec son cerveau...")
			UI:WaitShowDialogue("Enfin,[pause=10]il y a " .. CharacterEssentials.GetCharacterName("Marill") .. ",[pause=10]qui est un " .. marill_species .. ".[pause=0]C'est le leader de l'équipe et c'est un Pokémon agréable et optimiste !")
			UI:WaitShowDialogue("C'est aussi lui qui a trouvé le nom de leur équipe.")
			UI:WaitShowDialogue("Il prétend que c'est parce qu'ils savent utiliser le mouvement " .. move:GetColoredName() .. " ensemble,[pause=10]ce qui est vrai,[pause=10]mais...")
			UI:WaitShowDialogue("Euh...[pause=0]La plupart des Pokémon pensent que le nom de leur équipe a plus à voir avec leur type de corps qu'autre chose...")
			UI:WaitShowDialogue("...Je suppose que c'est difficile de leur en vouloir.[pause=0]Au début, je pensais la même chose,[pause=10]aussi.")
			UI:WaitShowDialogue("Quoi qu'il en soit,[pause=10] c'est l'une des équipes les plus sympathiques et les plus faciles à vivre.[pause=0]J'aimerais que plus d'équipes soient comme elles !")

		  elseif entry == 'Cadence' then
		    local ludicolo_species = _DATA:GetMonster('ludicolo'):GetColoredName()
			local roselia_species = _DATA:GetMonster('roselia'):GetColoredName()
			local spinda_species = _DATA:GetMonster('spinda'):GetColoredName()

			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nEntrée par équipe :[color=#FFA5FF]Cadence[color]")
			UI:SetCenter(false)
			UI:WaitShowDialogue("L'équipe[color=#FFA5FF]Cadence[color]compte trois membres,[pause=10]qui dansent généralement tous quelque part en ville.")
			UI:WaitShowDialogue("Leurs membres comprennent un " .. ludicolo_species .. " nommé " .. CharacterEssentials.GetCharacterName("Ludicolo") .. ",[pause=10]et un " .. spinda_species .. " nommé " .. CharacterEssentials.GetCharacterName("Spinda") .. ",[pause=10]et leur chef,[pause=10]" .. CharacterEssentials.GetCharacterName("Roselia") .. " le " .. roselia_species .. ".")
			UI:WaitShowDialogue("Ils ont tous un caractère joyeux et sont des aventuriers talentueux ![pause=0]Ils incitent souvent les autres à danser avec eux.")
			UI:WaitShowDialogue("Je sais qu'ils forment une équipe d'aventuriers compétente,[pause=10]mais...[pause=0]Il me semble qu'ils dansent plus qu'ils n'aventurent.")
			UI:WaitShowDialogue("Mais ils sont très bons dans les deux cas ![pause=0]Ils utilisent toutes sortes d'attaques et de techniques de danse au cours de leurs aventures.")
			UI:WaitShowDialogue("Il faut beaucoup de coordination et d'habileté pour utiliser la danse efficacement lors d'aventures !")
			UI:WaitShowDialogue("Ce serait sympa de les accompagner dans une de leurs aventures juste pour observer comment ils font !")


		  elseif entry == 'Flutter' then
		    local caterpie_species = _DATA:GetMonster('caterpie'):GetColoredName()
			local wurmple_species = _DATA:GetMonster('wurmple'):GetColoredName()
			local silcoon_species = _DATA:GetMonster('silcoon'):GetColoredName()
			local metapod_species = _DATA:GetMonster('metapod'):GetColoredName()

			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nEntrée par équipe :[color=#FFA5FF]Flutter[color]")
			UI:SetCenter(false)
			UI:WaitShowDialogue("L'équipe[color=#FFA5FF]Flutter[color]effectue la plupart des tâches de bas niveau qui entrent dans la guilde.")
			UI:WaitShowDialogue("L'équipe compte deux membres : " .. CharacterEssentials.GetCharacterName("Silcoon") .. " le " .. silcoon_species .. " et " .. CharacterEssentials.GetCharacterName("Metapod") .. " le " .. metapod_species .. ".")
			UI:WaitShowDialogue("Pendant longtemps, ces deux-là étaient en fait un " .. wurmple_species .. " et un " .. caterpie_species .. ",[pause=10] mais ils ont récemment décidé d'évoluer.")
			UI:WaitShowDialogue("Ils m'ont dit qu'ils prévoyaient également d'évoluer à nouveau bientôt.")
			UI:WaitShowDialogue("Je leur ai demandé pourquoi,[pause=10]et ils m'ont dit qu'ils voulaient enfin être à la hauteur du nom de leur équipe.")
			UI:WaitShowDialogue("Ils voulaient également commencer à occuper des emplois de niveau supérieur,[pause=10]et évoluer les aiderait également.")
			UI:WaitShowDialogue("Hmm.[pause=0]Évoluer deux fois en si peu de temps est fou pour moi,[pause=10]mais j'imagine que leurs formes actuelles sont difficiles à déplacer.")
			UI:WaitShowDialogue("Je ne voudrais pas non plus rester coincée dans un cocon longtemps si j'étais eux !")

		  elseif entry == 'Starlight' then
			local aggron_species = _DATA:GetMonster('aggron'):GetColoredName()
			local cleffa_species = _DATA:GetMonster('cleffa'):GetColoredName()
			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nEntrée par équipe :[color=#FFA5FF]Starlight[color]")
			UI:SetCenter(false)
			UI:WaitShowDialogue("L'équipe[color=#FFA5FF]Starlight[color]est composée de deux membres.[pause=0]Ils forment un duo un peu étrange, mais[pause=10]...")
			UI:WaitShowDialogue("Le leader est une " .. cleffa_species .. " nommée " .. CharacterEssentials.GetCharacterName("Cleffa") .. ",[pause=10]mais elle n'est pas très gentille et elle a un grand ego pour quelqu'un d'aussi petit.")
			UI:WaitShowDialogue("L'autre membre est un " .. aggron_species .. " qui s'appelle " .. CharacterEssentials.GetCharacterName("Aggron") .. ".[pause=0]. Il est vraiment timide et prend beaucoup de lèvres de " .. CharacterEssentials.GetCharacterName("Cleffa") .. ".")
			UI:WaitShowDialogue("C'est un peu étrange de voir un gros Pokémon comme celui-là être dirigé par un tout petit " .. cleffa_species .. ",[pause=10] je dois l'admettre.")
			UI:WaitShowDialogue("Ils acceptent toutes sortes de travaux différents,[pause=10] mais il semble qu'ils n'aient pas beaucoup de succès.")
			UI:WaitShowDialogue("Hmm.[pause=0]Je parie qu'ils feraient beaucoup mieux si " .. CharacterEssentials.GetCharacterName("Cleffa") .. " apprenait à mieux travailler avec son partenaire...")

		   elseif entry == 'Rivals' then
			local zangoose_species = _DATA:GetMonster('zangoose'):GetColoredName()
			local seviper_species = _DATA:GetMonster('seviper'):GetColoredName()
			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nInscription par équipe :[color=#FFA5FF]Rivals[color]")
			UI:SetCenter(false)
			UI:WaitShowDialogue("L'équipe[color=#FFA5FF]Rivals[color]compte deux membres qui, sans surprise étant donné leur nom,[pause=10] sont de féroces rivaux l'un avec l'autre.")
			UI:WaitShowDialogue("L'équipe est composée d'un " .. zangoose_species .. " nommé " .. CharacterEssentials.GetCharacterName("Zangoose") .. " et d'un " .. seviper_species .. " nommé " .. CharacterEssentials.GetCharacterName("Seviper") .. ".")
			UI:WaitShowDialogue("Quand je leur ai demandé qui était le leader,[pause=10] ils ont tous deux insisté sur le fait que c'était eux-mêmes et non leur partenaire.")
			UI:WaitShowDialogue("Ils ont commencé à se chamailler après ça et je n'ai pas pu poser d'autres questions...")
			UI:WaitShowDialogue("Cependant,[pause=10] un jour, j'ai remarqué qu'ils s'appuyaient l'un sur l'autre pour se soutenir après leur retour d'une mission difficile.")
			UI:WaitShowDialogue("Ils étaient tous les deux préoccupés par le bien-être de chacun plus que toute autre chose, bien qu'ils essayaient d'agir timidement à ce sujet.")
			UI:WaitShowDialogue("Malgré leur rivalité, il semble qu'ils se soucient l'un de l'autre,[pause=10]même s'ils n'aiment pas le montrer !")

		  elseif entry == 'Flight' then
			local doduo_species = _DATA:GetMonster('doduo'):GetColoredName()
			local bagon_species = _DATA:GetMonster('bagon'):GetColoredName()

			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nInscription par équipe :[color=#FFA5FF]Flight[color]")
			UI:SetCenter(false)
			UI:WaitShowDialogue("L'équipe[color=#FFA5FF]Flight[color]compte deux membres dans l'équipe.[pause=0]Un " .. doduo_species .. " nommé " .. CharacterEssentials.GetCharacterName("Doduo") .. " et un " .. bagon_species .. " nommé " .. CharacterEssentials.GetCharacterName("Bagon") .. ".")
			UI:WaitShowDialogue(CharacterEssentials.GetCharacterName("Bagon") .. " est courageux et optimiste,[pause=10]mais " .. CharacterEssentials.GetCharacterName("Doduo") .. " me semble douteux et nerveux.[pause=0]Il est un peu étrange...")
			UI:WaitShowDialogue("Ce qui est plus étrange, c'est leur nom,[pause=10]étant donné qu'aucun d'eux ne devrait être capable de voler...")
			UI:WaitShowDialogue(CharacterEssentials.GetCharacterName("Doduo") .. " prétend être capable de voler,[pause=10]mais je ne l'ai jamais vu le faire.[pause=0]Il est convaincu " .. CharacterEssentials.GetCharacterName("Bagon") .. " qu'il est capable de voler, cependant,[pause=10].")
			UI:WaitShowDialogue("J'aimerais bien voir au moins un d'entre eux voler un jour,[pause=10]en tout cas.")

		  elseif entry == 'Style' then
			local luxio_species = _DATA:GetMonster('luxio'):GetColoredName()
			local glameow_species = _DATA:GetMonster('glameow'):GetColoredName()
			local cacnea_species = _DATA:GetMonster('cacnea'):GetColoredName()

			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nEntrée de l'équipe :[color=#FFA5FF]Style[color]")
			UI:SetCenter(false)
			UI:WaitShowDialogue("Je ne connais pas grand chose à l'équipe[color=#FFA5FF]Style[color].[pause=0]C'est peut-être une nouvelle équipe ?")
			UI:WaitShowDialogue("Tout ce que je sais, c'est que l'équipe est composée d'un " .. luxio_species .. ", d'un[pause=10], d'un " .. glameow_species .. ", d'un[pause=10]et d'un " .. cacnea_species .. ".")
			UI:WaitShowDialogue("Une fois que j'en aurai appris davantage sur eux,[pause=10] j'aimerais écrire un article plus détaillé ici ![pause=0]Ils pourraient former une équipe vraiment cool !")

          elseif entry == GAME:GetTeamName() then
		  	local hero = CH('PLAYER')
			local partner = CH('Teammate1')
			local hero_species = _DATA:GetMonster(hero.CurrentForm.Species):GetColoredName()
			local partner_species = _DATA:GetMonster(partner.CurrentForm.Species):GetColoredName()



			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nInscription par équipe : " .. GAME:GetTeamName())
			UI:SetCenter(false)
			UI:WaitShowDialogue("L'équipe " .. GAME:GetTeamName() .. " est le nouveau membre de la guilde ![pause=0]C'est aussi une toute nouvelle équipe.")
			UI:WaitShowDialogue("L'équipe est composée de " .. hero:GetDisplayName() .. ", du " .. hero_species .. " et de " .. partner:GetDisplayName() .. ", du " .. partner_species .. ".")
			UI:WaitShowDialogue("Parce qu'ils sont si nouveaux,[pause=10] ils n'ont pas encore fait beaucoup d'aventures...")
			UI:WaitShowDialogue("Mais j'ai hâte de voir quel genre d'équipe ils vont former !")
			UI:WaitShowDialogue("Équipe " .. GAME:GetTeamName() .. ",[pause=10]si vous lisez ceci,[pause=10]sachez que je vous soutiens jusqu'au bout !")
		 end
		GROUND:ObjectSetDefaultAnim(obj, 'Diary_Red_Closing', 0, 0, 0, Direction.Right)
		GROUND:ObjectSetAnim(obj, 6, 0, 3, Direction.Right, 1)
		GROUND:ObjectSetDefaultAnim(obj, 'Diary_Red_Closing', 0, 3, 3, Direction.Right)
    end
	UI:SetCenter(false)
	partner.IsInteracting = false
	GROUND:CharEndAnim(partner)
	GROUND:CharEndAnim(hero)
end


function guild_bottom_right_bedroom.Tips_Almanac_Action(obj, activator)
	UI:ResetSpeaker(false)
	UI:SetCenter(true)
	UI:SetAutoFinish(true)
	local hero = CH('PLAYER')
	local partner = CH('Teammate1')
	partner.IsInteracting = true
	GROUND:CharSetAnim(partner, 'None', true)
	GROUND:CharSetAnim(hero, 'None', true)
    GeneralFunctions.TurnTowardsLocation(hero, obj.Position.X + obj.Width // 2, obj.Position.Y + obj.Height // 2)
    GeneralFunctions.TurnTowardsLocation(partner, obj.Position.X + obj.Width // 2, obj.Position.Y + obj.Height // 2)

	local zig_name = CharacterEssentials.GetCharacterName("Zigzagoon")
	local choices = {'Using Attacks to Move', 'Tough Opponents', 'Basic Attacks', 'Never Mind'}

	--Don't read his books until he tells you you can.
	if not SV.Chapter1.MetZigzagoon then
		UI:WaitShowDialogue("Cela semble être le livre de quelqu'un d'autre.\nMieux vaut ne pas le lire sans leur autorisation.")
		UI:SetCenter(false)
		UI:SetAutoFinish(false)
		partner.IsInteracting = false
		GROUND:CharEndAnim(partner)
		GROUND:CharEndAnim(hero)
		return
	end

	--todo: Different mons use different AI types
	UI:ChoiceMenuYesNo("C'est l'un des almanachs de " .. zig_name .. ".\nIl s'intitule \"Conseils d'aventure\". Le lire ?")
	UI:WaitForChoice()
	local result = UI:ChoiceResult()
	UI:SetAutoFinish(false)
	if result then
		  GROUND:ObjectSetDefaultAnim(obj, 'Diary_Blue_Opening', 0, 0, 0, Direction.Right)
	      GROUND:ObjectSetAnim(obj, 6, 0, 3, Direction.Right, 1)
		  GROUND:ObjectSetDefaultAnim(obj, 'Diary_Blue_Opening', 0, 3, 3, Direction.Right)
		  GAME:WaitFrames(40)
		  UI:BeginMultiPageMenu(24, 24, 196, "Almanach des conseils", choices, 8, 1, #choices)
		  UI:WaitForChoice()

		  local entry = choices[UI:ChoiceResult()]

		  if entry == 'Using Attacks to Move' then
			local quick_attack = _DATA.DataIndices[RogueEssence.Data.DataManager.DataType.Skill]:Get("quick_attack")
			local headbutt = _DATA.DataIndices[RogueEssence.Data.DataManager.DataType.Skill]:Get("headbutt")
			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nEntrée de conseils : Utiliser des attaques pour se déplacer")
			UI:SetCenter(false)
			UI:WaitShowDialogue("Certaines attaques font bouger l'utilisateur lorsqu'elles sont utilisées.[pause=0]Parfois plus qu'il ne le ferait normalement en un seul tour !")
			UI:WaitShowDialogue("C'est utile pour combler les écarts sur les adversaires,[pause=10]mais il existe aussi d'autres applications !")
			UI:WaitShowDialogue("En fonction de la distance à laquelle une attaque déplace l'utilisateur,[pause=10]l'utiliser pour se repositionner peut être plus efficace que la marche.")
			UI:WaitShowDialogue("Vous pouvez même sauter par-dessus un terrain sur lequel vous ne pourriez normalement pas rester au-dessus, comme de l'eau ou de la lave !")
			UI:WaitShowDialogue(quick_attack:GetColoredName() .. " est un mouvement courant qui me vient à l'esprit à cet effet,[pause=10]mais d'autres mouvements devraient également fonctionner !")
			UI:WaitShowDialogue("Pour moi,[pause=10]" .. headbutt:GetColoredName() .. " fonctionnerait,[pause=10]même si cela ne va pas aussi loin que " .. quick_attack:GetColoredName() .. ".")
		  elseif entry == 'Tough Opponents' then
		    UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nEntrée des astuces : adversaires coriaces")
			UI:SetCenter(false)
			UI:WaitShowDialogue("De temps en temps, au cours de mes aventures,[pause=10] j'ai rencontré des ennemis trop puissants pour que je puisse les affronter directement.")
			UI:WaitShowDialogue("Cela pourrait être dû au fait que j'étais épuisé,[pause=10]ou que cet adversaire était simplement plus fort que moi...")
			UI:WaitShowDialogue("Quoi qu'il en soit,[pause=10] même si je suis plus faible que mon adversaire,[pause=10] il y a des stratégies que j'ai apprises pour m'aider à sortir vainqueur.")
			UI:WaitShowDialogue("La première consiste à utiliser des objets comme des orbes et des baguettes pour désactiver l'adversaire afin qu'il ne puisse pas m'attaquer aussi efficacement, voire pas du tout.")
			UI:WaitShowDialogue("Peu importe s'ils sont plus forts s'ils ne peuvent pas riposter aussi bien !")
			UI:WaitShowDialogue("Une autre stratégie consiste simplement à fuir.[pause=0]Vous n'êtes pas obligé de battre tous les adversaires que vous trouvez après tout !")
			UI:WaitShowDialogue("S'ils ont des mouvements qui les aident à vous poursuivre,[pause=10] cela ne fonctionnera probablement pas très bien.")
			UI:WaitShowDialogue("Une dernière stratégie que j'ai proposée consiste à demander à " .. CharacterEssentials.GetCharacterName("Growlithe") .. " de combattre l'ennemi avec moi.")
			UI:WaitShowDialogue("Nous sommes une équipe après tout ![pause=0]Nous devrions travailler ensemble autant que possible pour rendre les choses plus faciles.")
		    UI:WaitShowDialogue("Bien sûr,[pause=10] je n'ai pas besoin de son aide pour chaque adversaire.")
			UI:WaitShowDialogue("Mais il y a des moments où une équipe doit travailler ensemble pour surmonter les obstacles !")
			UI:WaitShowDialogue("Quant à la stratégie que la situation appelle...")
			UI:WaitShowDialogue("Eh bien,[pause=10]cela dépend de l'adversaire,[pause=10]des objets que nous avons,[pause=10]" .. CharacterEssentials.GetCharacterName("Growlithe") .. " et de mon état,[pause=10]et bien d'autres facteurs...")
			UI:WaitShowDialogue("Je suppose que savoir quelle option choisir dans une situation difficile fait partie de ce qu'il faut pour être un grand aventurier,[pause=10]hmm.")
			UI:WaitShowDialogue("Quoi qu'il en soit,[pause=10] il est bon de savoir quelles sont mes options avant de devoir en choisir une lors d'une aventure !")
		  elseif entry == 'Basic Attacks' then
			local headbutt = _DATA.DataIndices[RogueEssence.Data.DataManager.DataType.Skill]:Get("headbutt")
			local aron_species = _DATA:GetMonster('aron'):GetColoredName()
			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nEntrée des astuces : attaques de base")
			UI:SetCenter(false)
			UI:WaitShowDialogue("Les attaques de base sont quelque chose que tous les Pokémon peuvent effectuer,[pause=10] quels que soient les mouvements qu'ils connaissent !")
			UI:WaitShowDialogue("Ils sont faibles par rapport à la plupart des mouvements,[pause=10]et vous n'obtiendrez aucun EXP si vous n'utilisez que des attaques de base pour vaincre un ennemi...")
			UI:WaitShowDialogue("Mais vous n'avez pas besoin d'énergie pour les exécuter,[pause=10]donc même lorsque vous avez épuisé vos mouvements,[pause=10]vous disposez toujours d'attaques de base !")
			UI:WaitShowDialogue("Cela les rend parfaits pour économiser l’énergie dont vous avez besoin pour effectuer des mouvements réguliers !")
			UI:WaitShowDialogue("Par exemple,[pause=10]si mon " .. headbutt:GetColoredName() .. " manque de peu la cible en mettant KO mon adversaire...")
			UI:WaitShowDialogue("Je peux utiliser une attaque de base pour les achever au lieu de gaspiller plus d'énergie en effectuant un autre " .. headbutt:GetColoredName() .. " !")
			UI:WaitShowDialogue("Un autre avantage des attaques de base est qu'elles sont sans type ![pause=0]Cela signifie qu'aucun type n'est faible ou n'y résiste !")
			UI:WaitShowDialogue("Alors parfois,[pause=10] si votre adversaire résiste à tous vos mouvements, les attaques de base[pause=10]peuvent être l'option la plus puissante dont vous disposez !")
			UI:WaitShowDialogue("Mon " .. headbutt:GetColoredName() .. " par exemple rayerait à peine un " .. aron_species .. ",[pause=10]puisque l'acier et la roche résistent à la normale...")
			UI:WaitShowDialogue("Mais une attaque de base ferait plus de dégâts que " .. headbutt:GetColoredName() .. " puisqu'on ne peut pas résister aux attaques de base !")
			UI:WaitShowDialogue("Beaucoup de Pokémon pensent que les attaques de base ne valent pas la peine d'être utilisées,[pause=10]mais ce n'est pas vrai !")
			UI:WaitShowDialogue("C'est juste quelque chose que vous devez savoir quand les utiliser pour en tirer le meilleur parti !")

		  end




		GROUND:ObjectSetDefaultAnim(obj, 'Diary_Blue_Closing', 0, 0, 0, Direction.Right)
		GROUND:ObjectSetAnim(obj, 6, 0, 3, Direction.Right, 1)
		GROUND:ObjectSetDefaultAnim(obj, 'Diary_Blue_Closing', 0, 3, 3, Direction.Right)
    end
	UI:SetCenter(false)
	partner.IsInteracting = false
	GROUND:CharEndAnim(partner)
	GROUND:CharEndAnim(hero)
end

function guild_bottom_right_bedroom.Data_Almanac_Action(obj, activator)
	UI:ResetSpeaker(false)
	UI:SetCenter(true)
	UI:SetAutoFinish(true)

	local hero = CH('PLAYER')
	local partner = CH('Teammate1')
	partner.IsInteracting = true
	GROUND:CharSetAnim(partner, 'None', true)
	GROUND:CharSetAnim(hero, 'None', true)
    GeneralFunctions.TurnTowardsLocation(hero, obj.Position.X + obj.Width // 2, obj.Position.Y + obj.Height // 2)
    GeneralFunctions.TurnTowardsLocation(partner, obj.Position.X + obj.Width // 2, obj.Position.Y + obj.Height // 2)


	local zig_name = CharacterEssentials.GetCharacterName("Zigzagoon")
	local choices = {'Gummi Stats', "Same Type Attack Bonus", "Type Matchups", "Stat Changes", "Never Mind"}
	--todos: Critical hit mechanics, belly mechanics and specifics

	--Don't read his books until he tells you you can.
	if not SV.Chapter1.MetZigzagoon then
		UI:WaitShowDialogue("Cela semble être le livre de quelqu'un d'autre.\nMieux vaut ne pas le lire sans leur autorisation.")
		UI:SetCenter(false)
		UI:SetAutoFinish(false)
		partner.IsInteracting = false
		GROUND:CharEndAnim(partner)
		GROUND:CharEndAnim(hero)
		return
	end

	UI:ChoiceMenuYesNo("C'est l'un des almanachs de " .. zig_name .. ".\nIl s'intitule \"Mesures et calculs\". Le lire ?")
	UI:WaitForChoice()
	local result = UI:ChoiceResult()
	UI:SetAutoFinish(false)
	if result then
		  GROUND:ObjectSetDefaultAnim(obj, 'Diary_Blue_Opening', 0, 0, 0, Direction.Left)
	      GROUND:ObjectSetAnim(obj, 6, 0, 3, Direction.Left, 1)
		  GROUND:ObjectSetDefaultAnim(obj, 'Diary_Blue_Opening', 0, 3, 3, Direction.Left)
		  GAME:WaitFrames(40)
		  UI:BeginMultiPageMenu(24, 24, 196, "Almanach des données", choices, 8, 1, #choices)
		  UI:WaitForChoice()

		  local entry = choices[UI:ChoiceResult()]

		  if entry == 'Gummi Stats' then
			local white_gummi = RogueEssence.Dungeon.InvItem("gummi_white")
			local orange_gummi = RogueEssence.Dungeon.InvItem("gummi_orange")
			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nSaisie de données : statistiques Gummi")
			UI:SetCenter(false)
			UI:WaitShowDialogue("Les gummis sont colorés, des friandises savoureuses[pause=10]![pause=0]Ils sont un peu difficiles à obtenir,[pause=10]mais ils valent la peine d'être recherchés !")
			UI:WaitShowDialogue("Il existe 18 types de Gummis,[pause=10] un pour chaque type de Pokémon.[pause=0]Ils augmentent même de manière permanente vos statistiques lorsqu'ils sont mangés !")
			UI:WaitShowDialogue("Les statistiques qu'ils génèrent dépendent du type de Gummi.[pause=0]Un " .. white_gummi:GetDisplayName() .. " fait monter les HP par exemple !")
			UI:WaitShowDialogue("De plus, le type de Gummi par rapport au type du mangeur affecte davantage les statistiques gagnées !")
			UI:WaitShowDialogue("Si le type de Gummi n'a aucun effet sur le mangeur,[pause=10] il ne gagnera aucune statistique !")
			UI:WaitShowDialogue("Si le type de Gummi n'est pas très efficace sur le mangeur,[pause=10]alors le Gummi n'augmentera pas autant la statistique.")
			UI:WaitShowDialogue("Si le type du Gummi est neutre sur le mangeur,[pause=10]alors le Gummi donne son boost régulier à la statistique.")
			UI:WaitShowDialogue("Si le type de Gummi est super efficace sur le mangeur,[pause=10]alors le Gummi augmentera également légèrement toutes les autres statistiques !")
			UI:WaitShowDialogue("Enfin,[pause=10]si le type du Gummi correspond à l'un des types du mangeur,[pause=10]alors toutes ses statistiques augmentent !")
			UI:WaitShowDialogue("En bref, les gommes[pause=10]donnent de meilleurs boosts plus vous êtes faible par rapport à son type,[pause=10]ou si vous correspondez à son type !")
			UI:WaitShowDialogue("Hmm.[pause=0]Je suppose que je devrais partager les Gummis que je trouve avec d'autres afin d'en tirer le meilleur parti.")
			UI:WaitShowDialogue("J'espère qu'ils feront de même et me donneront tous les " .. white_gummi:GetDisplayName() .. " ou " .. orange_gummi:GetDisplayName() .. " qu'ils trouveront !")
		  elseif entry == 'Same Type Attack Bonus' then
			local headbutt = _DATA.DataIndices[RogueEssence.Data.DataManager.DataType.Skill]:Get("headbutt")
			local hydro_pump = _DATA.DataIndices[RogueEssence.Data.DataManager.DataType.Skill]:Get("hydro_pump")
			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nSaisie de données : bonus d'attaque de même type")
			UI:SetCenter(false)
			UI:WaitShowDialogue("De nombreux Pokémon oublient que les capacités du même type que celui de l'utilisateur sont plus puissantes que les capacités d'autres types !")
			UI:WaitShowDialogue("Cela signifie que si un type Eau utilise " .. hydro_pump:GetColoredName() .. ",[pause=10] il serait plus fort que si un type Dragon l'utilisait !")
			UI:WaitShowDialogue("Au dojo, ils l'appellent Same Type Attack Bonus,[pause=10]mais j'aime le raccourcir en STAB.")
			UI:WaitShowDialogue("Après de nombreuses heures de tests avec Sensei " .. CharacterEssentials.GetCharacterName("Ledian") .. ",[pause=10] je pense avoir compris à quel point les mouvements sont plus forts avec STAB.")
			UI:WaitShowDialogue("On dirait que les mouvements font quatre tiers (4/3) de dégâts supplémentaires si l'utilisateur a STAB.")
			UI:WaitShowDialogue("Pour moi,[pause=10] cela signifie que mon " .. headbutt:GetColoredName() .. " est quatre tiers plus fort que les autres Pokémon qui ne sont pas de type Normal comme moi !")
			UI:WaitShowDialogue("J'espère que ces connaissances m'aideront à savoir quel mouvement est le meilleur à utiliser contre les ennemis que je rencontrerai au cours de mes aventures !")


		  elseif entry == 'Type Matchups' then
			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nSaisie de données : correspondances de types")
			UI:SetCenter(false)
			UI:WaitShowDialogue("Comme tout le monde le sait, les différents types de mouvements[pause=10]sont plus forts contre différents types de Pokémon.")
			UI:WaitShowDialogue("Mais ce que je parie que peu de Pokémon savent, c'est à quel point ces types de mouvements sont plus efficaces ou inefficaces !")
			UI:WaitShowDialogue("Après des tonnes de tests au Ledian Dojo,[pause=10] j'ai compris à quel point les correspondances de types affectent la force d'un mouvement !")
			UI:WaitShowDialogue("Si l'un des types du défenseur est immunisé contre le type d'attaque,[pause=10] alors le mouvement n'aura aucun effet !")
			UI:WaitShowDialogue("Une attaque de Combat sur un Pokémon Acier/Fantôme n'inflige aucun dégât,[pause=10]car Ghost est immunisé contre les combats malgré la faiblesse de l'Acier !")
			UI:WaitShowDialogue("Si le type du mouvement attaquant n'est pas efficace sur les deux types du défenseur,[pause=10] alors le mouvement inflige 0,25x dégâts.")
			UI:WaitShowDialogue("Une attaque normale sur un Pokémon Acier/Rocher n'inflige qu'un quart de dégâts,[pause=10]car Roche et Acier résistent à la Normale !")
		  	UI:WaitShowDialogue("Si le type du mouvement attaquant n'est pas très efficace sur l'un des types du défenseur,[pause=10]alors le mouvement inflige 0,5x dégâts.")
			UI:WaitShowDialogue("Un mouvement Herbe sur un Pokémon Feu/Ténèbres n'inflige que la moitié des dégâts,[pause=10]car le Feu résiste à l'Herbe mais l'Obscurité est neutre envers l'Herbe.")
		  	UI:WaitShowDialogue("Si le type du mouvement attaquant est globalement neutre par rapport aux types du défenseur,[pause=10] alors le mouvement infligera des dégâts réguliers.")
			UI:WaitShowDialogue("Une attaque Eau sur un Pokémon Roche/Herbe infligera des dégâts réguliers,[pause=10]car la Roche est faible face à l'Eau mais l'Herbe y résiste.")
			UI:WaitShowDialogue("Si le type du mouvement attaquant est super efficace sur l'un des types du défenseur,[pause=10] le mouvement inflige 1,5x dégâts.")
			UI:WaitShowDialogue("Une attaque de Feu sur un Pokémon Glace/Ténèbres inflige trois moitiés de dégâts,[pause=10]car la Glace est faible face au Feu et les Ténèbres sont neutres face au Feu.")
		    UI:WaitShowDialogue("Si le type du mouvement attaquant est super efficace sur les deux types du défenseur,[pause=10] alors le mouvement inflige 2,25x dégâts.")
			UI:WaitShowDialogue("Une attaque Glace inflige neuf quarts de dégâts à un Pokémon Dragon/Sol,[pause=10] car Dragon et Sol sont tous deux faibles face à la Glace !")
			UI:WaitShowDialogue("Les choses deviennent un peu plus compliquées lorsque les capacités entrent en jeu...[pause=0]Mais c'est une bonne ligne directrice sur laquelle travailler !")
			UI:WaitShowDialogue("C'est beaucoup de choses à retenir,[pause=10] mais connaître les bonus de dégâts et le tableau de correspondance des types m'aidera dans mes aventures !")

		  elseif entry == 'Stat Changes' then
		 	local belly_drum = _DATA.DataIndices[RogueEssence.Data.DataManager.DataType.Skill]:Get("belly_drum")
			local zone = _DATA.DataIndices[RogueEssence.Data.DataManager.DataType.Zone]:Get("beginner_lesson")
			UI:WaitShowDialogue("Almanach de " .. zig_name .. "\nSaisie de données : modifications des statistiques")
			UI:SetCenter(false)
			UI:WaitShowDialogue("Il existe toutes sortes de mouvements qui peuvent modifier temporairement les statistiques d'un Pokémon.")
			UI:WaitShowDialogue("Ceux-ci incluent des mouvements qui peuvent augmenter les statistiques d'un utilisateur ou réduire les statistiques d'un ennemi.")
			UI:WaitShowDialogue("Certains mouvements nécessitent même tellement de puissance qu'ils diminuent les statistiques de l'utilisateur !")
			UI:WaitShowDialogue("Mais dans quelle mesure ces changements de statistiques affectent-ils les statistiques d'un Pokémon ?")
			UI:WaitShowDialogue("Je voulais savoir pour pouvoir prendre de meilleures décisions concernant les aventures.")
			UI:WaitShowDialogue("Donc,[pause=10] je suis allé au Ledian Dojo pour tester des choses,[pause=10]et j'ai beaucoup appris sur le fonctionnement des changements de statistiques !")
			UI:WaitShowDialogue("Hmm.[pause=0]Les choses pourraient devenir un peu mathématiques ici,[pause=10] alors j'espère que tout cela aura du sens !")
			UI:WaitShowDialogue("Pour toutes les statistiques pouvant être temporairement modifiées,[pause=10] elles peuvent être modifiées par degrés appelés étapes.")
			UI:WaitShowDialogue("Ces étapes peuvent être négatives ou positives,[pause=10]mais une statistique ne peut aller que dans une seule direction jusqu'à 6 fois.")
			UI:WaitShowDialogue("Donc si une statistique était abaissée au minimum,[pause=10]elle serait à\n\"-6\" et je ne pourrais pas descendre plus bas que ça !")
			UI:WaitShowDialogue("A l'inverse,[pause=10]au maximum absolu, une statistique serait à \"+6\" et ne pourrait pas aller plus haut !")
			UI:WaitShowDialogue("Lorsqu'une statistique est modifiée,[pause=10] elle est généralement modifiée de 1,[pause=10]2,[pause=10]ou 3 étapes à la fois.")
			UI:WaitShowDialogue("S'il change légèrement,[pause=10]il monte ou descend d'un étage.")
			UI:WaitShowDialogue("S'il change brusquement ou durement,[pause=10]il monte ou descend de 2 étapes.")
			UI:WaitShowDialogue("Si cela change radicalement,[pause=10] cela monte ou descend de 3 étapes.")
			UI:WaitShowDialogue("Certains mouvements comme " .. belly_drum:GetColoredName() .. " peuvent modifier les statistiques de plus de 3 étapes,[pause=10] mais ce sont des exceptions.")
			UI:WaitShowDialogue("Une fois que vous savez combien d'étapes une statistique a été modifiée,[pause=10] vous devez déterminer le montant de la modification de la statistique !")
			UI:WaitShowDialogue("Pour faire ça...[pause=0]Euh,[pause=10]c'est un peu compliqué,[pause=10]alors soyez indulgents avec moi...")
			UI:WaitShowDialogue("Commencez par la fraction 4/4.[pause=0]Ensuite,[pause=10]si votre étape statistique est positive,[pause=10]ajoutez le nombre d'étapes au nombre supérieur.")
			UI:WaitShowDialogue("Donc, si vous êtes à l'attaque \"+6\",[pause=10] ce rapport serait (4+6)/4, soit 10/4.")
			UI:WaitShowDialogue("Si l'étape statistique est négative,[pause=10] vous ajoutez le nombre d'étapes au nombre en bas.")
			UI:WaitShowDialogue("Donc si je suis à \"-3\" Défense,[pause=10]alors mon ratio serait de 4/(4+3), soit 4/7.")
			UI:WaitShowDialogue("Bien sûr,[pause=10] si vous n'avez aucun changement de statistique dans une statistique,[pause=10] ce ratio devrait simplement rester à 4/4.")
			UI:WaitShowDialogue("Quoi qu'il en soit,[pause=10]une fois que vous obtenez ce ratio,[pause=10]vous multipliez votre statistique avec ce ratio pour obtenir votre nouvelle statistique efficace !")
			UI:WaitShowDialogue("Ainsi, un Pokémon à +6 en Attaque frappe deux fois et demie plus fort !")
			UI:WaitShowDialogue("Et un Pokémon à -6 en Défense serait blessé deux fois et demie plus durement !")
			UI:WaitShowDialogue("Tout cela s'applique à l'attaque, à la défense[pause=10], à l'attaque spéciale[pause=10], à la défense spéciale[pause=10].")
			UI:WaitShowDialogue("La précision et l'évasion sont un peu différentes.[pause=0]Commencez avec 2/2 comme ratio de base,[pause=10]mais sinon faites le reste de la même manière.")
			UI:WaitShowDialogue("Ainsi, un Pokémon avec +6 Évasion aurait le ratio (2+6)/2,[pause=10] soit 8/2.")
			UI:WaitShowDialogue("Avec ce ratio,[pause=10] ils ne seraient touchés qu'un quart du temps qu'ils le feraient normalement !")
		    UI:WaitShowDialogue("De l'autre côté,[pause=10]un Pokémon avec -3 Précision aurait le ratio 2/(2+3) qui est de 2/5.")
			UI:WaitShowDialogue("Avec un ratio de 2/5,[pause=10] ils n'atteindraient que 40 % du taux normal !")
			UI:WaitShowDialogue("Cependant,[pause=10] je ne pense pas avoir jamais vu un Pokémon rater deux attaques d'affilée,[pause=10] alors gardez cela à l'esprit.")
			UI:WaitShowDialogue("Enfin, la vitesse[pause=10]ne change pas comme le font les autres statistiques,[pause=10] donc je pense que je vais laisser cela pour une entrée différente.")
			UI:WaitShowDialogue("Je pense que " .. zone:GetColoredName() .. " de Ledian Dojo a de toute façon des informations sur la façon dont cela fonctionne...")
			UI:WaitShowDialogue("...Et je pense que cela couvre tout.[pause=0]Ma patte et mon cerveau me font un peu mal après avoir écrit tout ça...")
			UI:WaitShowDialogue("Pourtant,[pause=10] c'est bien que j'écrive tout cela,[pause=10]surtout après avoir fait tout ce travail pour tout comprendre !")
			UI:WaitShowDialogue("Après tout,[pause=10] qui sait quand ce genre d’informations pourrait s’avérer utile !")
		  end


		GROUND:ObjectSetDefaultAnim(obj, 'Diary_Blue_Closing', 0, 0, 0, Direction.Left)
		GROUND:ObjectSetAnim(obj, 6, 0, 3, Direction.Left, 1)
		GROUND:ObjectSetDefaultAnim(obj, 'Diary_Blue_Closing', 0, 3, 3, Direction.Left)
    end
	UI:SetCenter(false)
	partner.IsInteracting = false
	GROUND:CharEndAnim(partner)
	GROUND:CharEndAnim(hero)

end


---------------------------
-- Map Transitions
---------------------------
function guild_bottom_right_bedroom.Bedroom_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_bedroom_hallway", "Guild_Bedroom_Hallway_Bottom_Right_Marker")
  SV.partner.Spawn = 'Guild_Bedroom_Hallway_Bottom_Right_Marker_Partner'
end

return guild_bottom_right_bedroom

