--- Scene: b01p01a
local b01p01a = {}
function b01p01a.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_002"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_005"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_006"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_008"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_011"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_012"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_013"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_014"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_015"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_016"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_017"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_018"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_019"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_020"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_021"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_022"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_023"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_024"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_025"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_026"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_027"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_028"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_029"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_030"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_031"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_032"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_033"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_034"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_035"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_036"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_037"))
  -- GROUND:CharSetAction(ent, 22)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_038"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_039"))
  -- GROUND:CharSetAction(ent, 1)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_040"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_041"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_042"))
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_043"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  GAME:FadeOutBGM(120)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_044"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_045"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_046"))
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_047"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_048"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_049"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_050"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_051"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_052"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_053"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_054"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_055"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_056"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_057"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_058"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_059"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_060"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_061"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_062"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_063"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_064"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:FadeOutBGM(5)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_065"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_066"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_067"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_068"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_069"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_070"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_071"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_072"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_073"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_074"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_075"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_076"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_077"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_078"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_079"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_080"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_081"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_082"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_083"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_084"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_085"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_086"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_087"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_088"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_089"))
  -- GROUND:CharSetAction(ent, 6)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 22)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_090"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_091"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_092"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_093"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_094"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_095"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_096"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_097"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_098"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_099"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_100"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_101"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_102"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_103"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_104"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_105"))
  GAME:PlayBGM('Rescue Team Base', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_106"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_107"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 3)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_108"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_109"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_110"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_111"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_112"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_113"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_114"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_115"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_116"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_117"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_118"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_119"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_120"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_121"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_122"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_123"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_124"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_125"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_126"))
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_127"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_128"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_129"))
  GAME:FadeOutBGM(150)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_130"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_131"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_132"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_133"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_134"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_135"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_136"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_137"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_138"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('A Successful Rescue', true)
  GAME:FadeOutBGM(90)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_139"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_140"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_141"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_142"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_143"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_144"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_145"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_146"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_147"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_148"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_149"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_150"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_151"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_152"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_153"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_154"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_155"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_156"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_157"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_158"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_159"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_160"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_161"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_162"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_163"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_164"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_165"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_166"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_167"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_168"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_169"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_170"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_171"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_172"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_173"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_174"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_175"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_176"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_177"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_178"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_179"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_180"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_181"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_182"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_183"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_184"))
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_185"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_186"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_187"))
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_188"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_189"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_190"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_191"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_192"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_193"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_194"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_195"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_196"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_197"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_198"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_199"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_200"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_201"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_202"))
  GAME:FadeOutBGM(120)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_203"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_204"))
  GAME:FadeOutBGM(60)
  GAME:PlayBGM('Theres Trouble', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_205"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_206"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_207"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_208"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_209"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_210"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_211"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_212"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_213"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_214"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_215"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_216"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_217"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_218"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_219"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_220"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_221"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_222"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_223"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_224"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_225"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_226"))
  GAME:FadeOutBGM(60)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_227"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_228"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_229"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_230"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_231"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_232"))
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_233"))
  -- GROUND:CharSetAction(ent, 22)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_234"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_235"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_236"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_237"))
  GAME:FadeOutBGM(60)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_238"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_239"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_240"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_241"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_242"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_243"))
  GAME:PlayBGM('Theres Trouble', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_244"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_245"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_246"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_247"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_248"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_249"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_250"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_251"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_252"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_253"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_254"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_255"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_256"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_257"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_258"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_259"))
  GAME:FadeOutBGM(60)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_260"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_261"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_262"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_263"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_264"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_265"))
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_266"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('A Successful Rescue', true)
  GAME:FadeOutBGM(90)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_267"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_268"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_269"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_270"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_271"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_272"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_273"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_274"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_275"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_276"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_277"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_278"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_279"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_280"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_281"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_282"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_283"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_284"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_285"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_286"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_287"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_288"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_289"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_290"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_291"))
  GAME:FadeOutBGM(120)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_292"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_293"))
  -- GROUND:CharSetAction(ent, 2)
  -- CAMERA_PAN(204, 44),
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_294"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_295"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_296"))
  GAME:PlayBGM('Rising Fear', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_297"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_298"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_299"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_300"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_301"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_302"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_303"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_304"))
  GAME:FadeOutBGM(120)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_305"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_306"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_307"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_308"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_309"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_310"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_311"))
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_312"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  GAME:FadeOutBGM(60)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_313"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_314"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_315"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_316"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_317"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_318"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_319"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_320"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_321"))
  GAME:FadeOutBGM(30)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_322"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_323"))
  GAME:PlayBGM('In The Depths Of The Pit', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_324"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_325"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_326"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_327"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_328"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_329"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_330"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_331"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_332"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_333"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_334"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_335"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_336"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_337"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_338"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_339"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_340"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_341"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_342"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_343"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_344"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_345"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_346"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_347"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_348"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_349"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_350"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_351"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_352"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_353"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_354"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_355"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_356"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_357"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_358"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_359"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_360"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_361"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_362"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_363"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_364"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_365"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_366"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_367"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_368"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_369"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_370"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_371"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_372"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_373"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_374"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_375"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_376"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_377"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_378"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_379"))
  -- GROUND:CharSetAction(ent, 41)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_380"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_381"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_382"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_383"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_384"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_385"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_386"))
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_387"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  GAME:FadeOutBGM(90)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_388"))
  GAME:FadeOutBGM(160)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_389"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_390"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_391"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_392"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 3)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_393"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_394"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_395"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_396"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_397"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_398"))
  -- GROUND:CharSetAction(ent, 2)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  GAME:FadeOutBGM(150)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_399"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_400"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_401"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_402"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_403"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_404"))
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_405"))
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_406"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_407"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_408"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_409"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_410"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_411"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_412"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_413"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_414"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_415"))
  GAME:PlayBGM('Rising Fear', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_416"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_417"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_418"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_419"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_420"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:FadeOutBGM(90)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_421"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_422"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_423"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_424"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_425"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_426"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_427"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_428"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_429"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_430"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_431"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_432"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_433"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_434"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_435"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_436"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_437"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_438"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_439"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_440"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_441"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_442"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_443"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_444"))
  GAME:PlayBGM('Pokemon Square', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_445"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_446"))
  GAME:FadeOutBGM(90)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_447"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_448"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_449"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_450"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_451"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_452"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_453"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_454"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_455"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_456"))
  GAME:PlayBGM('The Escape', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_457"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_458"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('The Escape', true)
  GAME:FadeIn(30)
  GAME:FadeOut(true, 30)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_459"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_460"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_461"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('The Escape', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_462"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_463"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_464"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_465"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_466"))
  -- CAMERA_PAN(256, 52),
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_467"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_468"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_469"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_470"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_471"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_472"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_473"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_474"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_475"))
  -- CAMERA_PAN(256, 57),
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_476"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_477"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_478"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_479"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_480"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_481"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_482"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_483"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_484"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_485"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_486"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_487"))
  -- GROUND:CharSetAction(ent, 2)
  -- CAMERA_PAN(256, 58),
  -- GROUND:CharSetAction(ent, 2)
  -- CAMERA_PAN(256, 53),
  -- CAMERA_PAN(256, 59),
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_488"))
  -- GROUND:CharSetAction(ent, 2)
  -- CAMERA_PAN(256, 54),
  -- CAMERA_PAN(256, 60),
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_489"))
  -- GROUND:CharSetAction(ent, 22)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_490"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- CAMERA_PAN(256, 55),
  -- CAMERA_PAN(256, 61),
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_491"))
  -- GROUND:CharSetAction(ent, 2)
  -- CAMERA_PAN(256, 56),
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_492"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_493"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_494"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_495"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_496"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 22)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_497"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_498"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_499"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_500"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_501"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_502"))
  GAME:FadeOutBGM(90)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_503"))
  -- CAMERA_PAN(256, 63),
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_504"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_505"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_506"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_507"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_508"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_509"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_510"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_511"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_512"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_513"))
  GAME:FadeOutBGM(90)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_514"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_515"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_516"))
  GAME:FadeOutBGM(150)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_517"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_518"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_519"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_520"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_521"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_522"))
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_523"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_524"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_525"))
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_526"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_527"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:FadeIn(30)
  GAME:FadeOut(true, 35)
  GAME:FadeOut(true, 120)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_528"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_529"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_530"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_531"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_532"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_533"))
  -- GROUND:CharSetAction(ent, 2)
  -- CAMERA_PAN(256, 74),
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_534"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_535"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_536"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_537"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_538"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_539"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_540"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_541"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_542"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_543"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_544"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_545"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_546"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_547"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_548"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_549"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_550"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_551"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_552"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_553"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_554"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_555"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_556"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_557"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_558"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_559"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_560"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_561"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_562"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_563"))
  GAME:FadeOutBGM(90)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_564"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_565"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_566"))
  GAME:PlayBGM('Theres Trouble', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_567"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_568"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_569"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_570"))
  -- GROUND:CharSetAction(ent, 41)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_571"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_572"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_573"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_574"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_575"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_576"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_577"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_578"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_579"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_580"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_581"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_582"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_583"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_584"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_585"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_586"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_587"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_588"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_589"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_590"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_591"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_592"))
  -- GROUND:CharSetAction(ent, 41)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 5)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_593"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_594"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_595"))
  GAME:PlayBGM('Theres Trouble', true)
  -- GROUND:CharSetAction(ent, 41)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_596"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_597"))
  GAME:FadeOutBGM(60)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_598"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_599"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_600"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_601"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_602"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_603"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_604"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_605"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_606"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_607"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_608"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_609"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_610"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_611"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_612"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_613"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_614"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_615"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_616"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_617"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_618"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_619"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_620"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_621"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_622"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_623"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_624"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_625"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_626"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 41)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 17)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 41)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 41)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:FadeOutBGM(60)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_627"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_628"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_629"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_630"))
  GAME:FadeOutBGM(60)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- CAMERA_PAN(512, 103),
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_631"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_632"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_633"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_634"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_635"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_636"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_637"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_638"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_639"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_640"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_641"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_642"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_643"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_644"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_645"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_646"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_647"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_648"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_649"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 6)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 6)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 6)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_650"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_651"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_652"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_653"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_654"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_655"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_656"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_657"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_658"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_659"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_660"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_661"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_662"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_663"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_664"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_665"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_666"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_667"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_668"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_669"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_670"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_671"))
  GAME:FadeOutBGM(60)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_672"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_673"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_674"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_675"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_676"))
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_677"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_678"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_679"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_680"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_681"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_682"))
  GAME:FadeOutBGM(60)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_683"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_684"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_685"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_686"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_687"))
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  GAME:PlayBGM('Rescue Team Base', true)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 8)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 8)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 8)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_688"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_689"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_690"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_691"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_692"))
  GAME:FadeOutBGM(60)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_693"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_694"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_695"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_696"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_697"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_698"))
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_699"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_700"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_701"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_702"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_703"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_704"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_705"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_706"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_707"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_708"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_709"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_710"))
  GAME:FadeOutBGM(120)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_711"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_712"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_713"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_714"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_715"))
  GAME:PlayBGM('Theres Trouble', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_716"))
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 40)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  GAME:FadeOutBGM(60)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_717"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_718"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_719"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_720"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_721"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_722"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_723"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_724"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_725"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_726"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_727"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_728"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_729"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_730"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_731"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_732"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_733"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_734"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_735"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_736"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_737"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_738"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_739"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_740"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_741"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_742"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_743"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_744"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_745"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_746"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_747"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_748"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_749"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_750"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_751"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_752"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_753"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_754"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_755"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_756"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_757"))
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_758"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_759"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_760"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_761"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_762"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_763"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_764"))
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_765"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_766"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_767"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_768"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_769"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_770"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_771"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_772"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_773"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_774"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_775"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_776"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_777"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_778"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_779"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_780"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_781"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_782"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_783"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_784"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_785"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_786"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_787"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_788"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_789"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_790"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_791"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_792"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_793"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_794"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_795"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_796"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_797"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_798"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_799"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_800"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_801"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_802"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_803"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_804"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_805"))
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_806"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_807"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_808"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_809"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_810"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_811"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_812"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_813"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_814"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_815"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_816"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_817"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_818"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_819"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_820"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_821"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_822"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_823"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_824"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_825"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_826"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_827"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_828"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_829"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_830"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_831"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_832"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_833"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_834"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_835"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_836"))
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_837"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_838"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_839"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_840"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_841"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_842"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_843"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_844"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_845"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_846"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_847"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_848"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_849"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_850"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_851"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_852"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_853"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_854"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_855"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_856"))
  GAME:PlayBGM('Rescue Team Base', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_857"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_858"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_859"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_860"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_861"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_862"))
  GAME:PlayBGM('Rescue Team Base', true)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_863"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_864"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_865"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_866"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_867"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_868"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_869"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_870"))
  GAME:PlayBGM('Rescue Team Base', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_871"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_872"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_873"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_874"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_875"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_876"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_877"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_878"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_879"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_880"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_881"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_882"))
  GAME:PlayBGM('Rescue Team Base', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_883"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_884"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_885"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_886"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_887"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_888"))
  GAME:PlayBGM('Benevolent Spirit', true)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_889"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_890"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_891"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_892"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_893"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_894"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_895"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_896"))
  GAME:FadeOutBGM(60)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_897"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_898"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_899"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_900"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_901"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_B01P01A_902"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:CutsceneMode(false)
end
return b01p01a
