--- Scene: t01p03
local t01p03 = {}
function t01p03.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('Pokemon Square', true)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_002"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_004"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_005"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_006"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_008"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_011"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_012"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_013"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_014"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_015"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_016"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_017"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_018"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_019"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_020"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_021"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_022"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_023"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_024"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_025"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_026"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_027"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_028"))
  -- GROUND:CharSetAction(ent, 2)
  -- CAMERA_PAN(256, 4),
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_029"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_030"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_031"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_032"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_033"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_034"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_035"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_036"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_037"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_038"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_039"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_040"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_041"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_042"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_043"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_044"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_045"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_046"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_047"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_048"))
  GAME:PlayBGM('Pokemon Square', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_049"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_050"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_051"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_052"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_053"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_054"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_055"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_056"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_057"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_058"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_059"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_060"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_061"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_062"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_063"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Pokemon Square', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_064"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_065"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_066"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_067"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_068"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_069"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_070"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_071"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_072"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_073"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_074"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 17)
  -- GROUND:CharSetAction(ent, 17)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_075"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_076"))
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Pokemon Square', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_077"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_078"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_079"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_080"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_081"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_082"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_083"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_084"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_085"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 17)
  -- GROUND:CharSetAction(ent, 17)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_086"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_087"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_088"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_089"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_090"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_091"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_092"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_093"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_094"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_095"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_096"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_097"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_098"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_099"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_100"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_101"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_102"))
  GAME:FadeOutBGM(60)
  GAME:PlayBGM('Pokemon Square', true)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Pokemon Square', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_103"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_104"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_105"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_106"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_107"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_108"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_109"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_110"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_111"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_112"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_113"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_114"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_115"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_116"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_117"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_118"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_119"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_120"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_121"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_122"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_123"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_124"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_125"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_126"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_127"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_128"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_129"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_130"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_131"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_132"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_133"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_134"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_135"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_136"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_137"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_138"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 1)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_139"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_140"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_141"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_142"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_143"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_144"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 4)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_145"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_146"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_147"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_148"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_149"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_150"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_151"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_152"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_153"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_154"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_155"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_156"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_157"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_158"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_159"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_160"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_161"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_162"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_163"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_164"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_165"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_166"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_167"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_168"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_169"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_170"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_171"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_172"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_173"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_174"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_175"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_176"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_177"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_178"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_179"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_180"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_181"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_182"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_183"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_184"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_185"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_186"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_187"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_188"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_189"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_190"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_191"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_192"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_193"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_194"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_195"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_196"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_197"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_198"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_199"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_200"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_201"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_202"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_203"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_204"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_205"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_206"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_207"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_208"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_209"))
  GAME:PlayBGM('Aftermath', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_210"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_211"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_212"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_213"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_214"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_215"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_216"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_217"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_218"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_219"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_220"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_221"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P03_222"))
  GAME:PlayBGM('Intro', true)
  -- GROUND:CharSetAction(ent, 5)
  GAME:CutsceneMode(false)
end
return t01p03
