--- Scene: t01p02a
local t01p02a = {}
function t01p02a.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('File Select', true)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_002"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_005"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_006"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_007"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_008"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_011"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_012"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_013"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_014"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_015"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_016"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_017"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_018"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_019"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_020"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_021"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_022"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_023"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_024"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_025"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_026"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_027"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_028"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_029"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_030"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_031"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_032"))
  GAME:PlayBGM('File Select', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_033"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_034"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_035"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_036"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_037"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_038"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_039"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_040"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_041"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_042"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_043"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_044"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_045"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_046"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_047"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_048"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_049"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_050"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_051"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_052"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_053"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_054"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_055"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_056"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_057"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_058"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_059"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_060"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_061"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_062"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_063"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_064"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_065"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_066"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_067"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_068"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_069"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_070"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_071"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_072"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_073"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_074"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_075"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_076"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_077"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_078"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_079"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_080"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_081"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_082"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_083"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_084"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_085"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_086"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_087"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_088"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_089"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_090"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_091"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_092"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_093"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_094"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_095"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_096"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_097"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_098"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_099"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_100"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_101"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_102"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_103"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_104"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_105"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_106"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_107"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_108"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_109"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_110"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_111"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_112"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_113"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_114"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_115"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_116"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_117"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_118"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_119"))
  GAME:FadeOutBGM(90)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_120"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_121"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_122"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_123"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_124"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_125"))
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Legend Of Ninetales', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_126"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_127"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_128"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_129"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_130"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_131"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_132"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_133"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_134"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_135"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_136"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_137"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_138"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_139"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_140"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_141"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_142"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_143"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_144"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_145"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_146"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_147"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_148"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_149"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_150"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_151"))
  GAME:FadeOutBGM(120)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_152"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_153"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_154"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_155"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_156"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_157"))
  GAME:PlayBGM('File Select', true)
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_158"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_159"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_160"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_161"))
  GAME:FadeIn(30)
  GAME:FadeOut(true, 30)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_162"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_163"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_164"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_165"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_166"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_167"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_168"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_169"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 6)
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_170"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_171"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_172"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_173"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_174"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_175"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_176"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_177"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_178"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_179"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_180"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_181"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_182"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_183"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_184"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_185"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_186"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_187"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_188"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_189"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_190"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_191"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_192"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_193"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_194"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_195"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_196"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_197"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_198"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_199"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_200"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_201"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_202"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_203"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_204"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_205"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_206"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_207"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_208"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_209"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_210"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_211"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_212"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_213"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_214"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_215"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_216"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_217"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_218"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_219"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_220"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_221"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_222"))
  GAME:PlayBGM('Aftermath', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- GROUND:CharSetAction(ent, 1)
  GAME:PlayBGM('File Select', true)
  -- GAME:MoveCamera(HeroX, HeroY, 1)
  -- CAMERA_PAN(256, 24),
  -- CAMERA_PAN(512, 25),
  -- CAMERA_PAN(512, 24),
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_223"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_224"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_225"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_226"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_227"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_228"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_229"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_230"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_231"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_232"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_233"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_234"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_235"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_236"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_237"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_238"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_239"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_240"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_241"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_242"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_243"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_244"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_245"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_246"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_247"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_248"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_249"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_250"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_251"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_252"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_253"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_254"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_255"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_256"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_257"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_258"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_259"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_260"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_261"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_262"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_263"))
  -- GROUND:CharSetAction(ent, 1)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_264"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_T01P02A_265"))
  GAME:CutsceneMode(false)
end
return t01p02a
