--[[
    init.lua
    Created: 06/19/2023 11:32:20
    Description: Autogenerated script file for the map apricorn_grove.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'halcyon.GeneralFunctions'
require 'halcyon.TownNight'

local apricorn_grove = {}
--------------------------------------------------
-- Map Callbacks
--------------------------------------------------
function apricorn_grove.Init(zone)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> Init_apricorn_grove")
  --Mark this as the last dungeon entered.
  SV.TemporaryFlags.LastDungeonEntered = 'apricorn_grove'
  
end

function apricorn_grove.EnterSegment(zone, rescuing, segmentID, mapID)
	GeneralFunctions.CheckAllowSetRescue(zone.ID)
	--without this check, entering the apricorn grove grounds (entrance/glade) after officially entering the dungeon
	--would call the EnterSegment callback and trigger the InDungeon flag to become true.
	if segmentID == 0 then
		SV.ApricornGrove.InDungeon = true
	end
	
	if rescuing ~= true then
		COMMON.BeginDungeon(zone.ID, segmentID, mapID)
	end
end

function apricorn_grove.Rescued(zone, name, mail)
	COMMON.Rescued(zone, name, mail)
end


function apricorn_grove.ExitSegment(zone, result, rescue, segmentID, mapID)
  GeneralFunctions.RestoreIdleAnim()
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_apricorn_grove (Apricorn Grove) result "..tostring(result).." segment "..tostring(segmentID))  
	--[[Different dungeon result typeS (cleared, died, etc)
	       public enum ResultType
        {
            Unknown = -1,
            Downed,
            Failed,
            Cleared,
            Escaped,
            TimedOut,
            GaveUp,
            Rescue
        }
		]]--
	local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)

	if exited == true then
		--do nothing
	elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then


		GAME:WaitFrames(20)

		--no longer in the dungeon.
		SV.ApricornGrove.InDungeon = false
		
		--set generic flags for generic end of day / start of next day.
		--CHOIX DE FIN DE JOURNEE, variante a epilogue : la sauvegarde reste
		--l'avant-dernier acte et la replique de defaite s'affiche APRES l'ecran
		--de resultats, comme le voulait le code d'origine.
		TownNight.EndDayWithEpilogue(result, function()
			if not SV.Chapter4.FinishedGrove and result ~= RogueEssence.Data.GameProgress.ResultType.Escaped then --team died before making it to the end for the first time. 
				UI:SetSpeaker(GAME:GetPlayerPartyMember(1))--set partner as speaker 
				GeneralFunctions.SetEmotion("Pain")
				GeneralFunctions.DeathFadeOutDialogue(GAME:GetPlayerPartyMember(1), "Argh ![pause=0] Ça ne s'est pas passé comme prévu...", "Pain")

				GAME:WaitFrames(20)
			end
		end)

	
	else 
		if SV.Chapter4.FinishedGrove then 
			--set generic flags for generic end of day / start of next day.
			SV.TemporaryFlags.Dinnertime = true 
			SV.TemporaryFlags.Bedtime = true
			SV.TemporaryFlags.MorningWakeup = true 
			SV.TemporaryFlags.MorningAddress = true 
		end
				
		
		--since you can choose to go back into the dungeon at the end or not, do all end of dungeon stuff in the ground.
		GAME:EnterGroundMap('apricorn_glade', 'Main_Entrance_Marker') --Go to Apricorn Glade, end dungeon run in the ground rather than here 
	end
end
	

return apricorn_grove