--- Scene: d02p01
local d02p01 = {}
function d02p01.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('Thunderwave Cave', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D02P01_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D02P01_002"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D02P01_003"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('Thunderwave Cave', true)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D02P01_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D02P01_005"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:PlayBGM('A Successful Rescue', true)
  GAME:FadeIn(60)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D02P01_006"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D02P01_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D02P01_008"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D02P01_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D02P01_010"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  GAME:CutsceneMode(false)
end
return d02p01
