--- Scene: d10p03
local d10p03 = {}
function d10p03.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('In The Depths Of The Pit', true)
  GAME:FadeOutBGM(60)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_002"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_005"))
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_006"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_008"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_011"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_012"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_013"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_014"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_015"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_016"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_017"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_018"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_019"))
  GAME:FadeOut(true, 2)
  GAME:FadeIn(2)
  GAME:FadeOut(true, 2)
  GAME:FadeIn(2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_020"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_021"))
  GAME:FadeOut(true, 2)
  GAME:FadeIn(2)
  GAME:FadeOut(true, 2)
  GAME:FadeIn(2)
  GAME:FadeOut(true, 2)
  GAME:FadeIn(2)
  GAME:FadeOut(true, 2)
  GAME:FadeIn(2)
  GAME:FadeOut(true, 2)
  GAME:FadeOutBGM(120)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_022"))
  GAME:FadeOutBGM(120)
  GAME:FadeIn(40)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_023"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_024"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_025"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_026"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_027"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_028"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_029"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_030"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_031"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_032"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_033"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_034"))
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_035"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_036"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_037"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_038"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_039"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_040"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_041"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_042"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_043"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_044"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_045"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_046"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_047"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_048"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_049"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_050"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_051"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_052"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_053"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D10P03_054"))
  -- GROUND:CharSetAction(ent, 2)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  SOUND:PlayBattleSE('EVT_Roar')
  GAME:WaitFrames(20)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 24)
  -- GROUND:CharSetAction(ent, 25)
  -- GROUND:CharSetAction(ent, 25)
  -- GROUND:CharSetAction(ent, 25)
  -- GROUND:CharSetAction(ent, 25)
  -- GROUND:CharSetAction(ent, 24)
  -- GROUND:CharSetAction(ent, 25)
  -- GROUND:CharSetAction(ent, 24)
  -- GROUND:CharSetAction(ent, 5)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 23)
  -- GROUND:CharSetAction(ent, 2)
  GAME:CutsceneMode(false)
end
return d10p03
