--- Scene: d16p01
local d16p01 = {}
function d16p01.Cutscene()
  GAME:CutsceneMode(true)
  GAME:PlayBGM('In The Depths Of The Pit', true)
  GAME:FadeOutBGM(60)
  -- GROUND:CharSetAction(ent, 2)
  GAME:FadeOut(true, 5)
  GAME:FadeIn(5)
  GAME:FadeOut(true, 5)
  GAME:FadeIn(5)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_001"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_002"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_003"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_004"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_005"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_006"))
  GAME:FadeOutBGM(30)
  GAME:FadeOut(true, 4)
  GAME:FadeIn(4)
  -- GROUND:CharSetAction(ent, 2)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_007"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_008"))
  GAME:FadeOut(true, 60)
  GAME:FadeIn(60)
  GAME:PlayBGM('In The Depths Of The Pit', true)
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_009"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_010"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_011"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_012"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_013"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_014"))
  UI:WaitShowDialogue(STRINGS:FormatKey("SCENE_D16P01_015"))
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 19)
  -- GROUND:CharSetAction(ent, 2)
  -- GROUND:CharSetAction(ent, 9)
  -- GROUND:CharSetAction(ent, 22)
  -- GROUND:CharSetAction(ent, 2)
  GAME:CutsceneMode(false)
end
return d16p01
