--[[
    Ground Controller: Starter Village (pixellab_metano_variant)
    Procedurally generated by PMDO Town Generator (Seed: 20260830)
]]

require 'origin.common'

local pixellab_metano_variant = {}

function pixellab_metano_variant.Init(map)
    DEBUG.EnableDbgCoro()
    PrintInfo("=>> Initializing ground pixellab_metano_variant")
end

function pixellab_metano_variant.Enter(map)
    GROUND:Hide('PLAYER')
    local player = CH('PLAYER')
    if player then
        GROUND:TeleportTo(player, 768, 979, Direction.Up)
    end
    GAME:FadeIn(20)
end

function pixellab_metano_variant.Exit(map)
    GAME:FadeOut(20)
end

return pixellab_metano_variant
