-- PMU Ground Controller for pmu_s1143 (Grassroot Town, Rustle's House)
-- Generated by PMU Pipeline (New Era)
local pmu_s1143 = {}

function pmu_s1143.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1143.Enter(map)
  local music = 'PMD3) So Come! Post Town.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1143.Update(map, time)
end

function pmu_s1143.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s737', 'Entrance', false)
end

function pmu_s1143.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s737', 'Entrance', false)
end

return pmu_s1143
