--[[
    init.lua
    Created: 08/30/2025 12:54:02
    Description: Autogenerated script file for the map haunted_bazar.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local haunted_bazar = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---haunted_bazar.Init(zone)
--Engine callback function
function haunted_bazar.Init(zone)


end

---haunted_bazar.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function haunted_bazar.EnterSegment(zone, rescuing, segmentID, mapID)


end

---haunted_bazar.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function haunted_bazar.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---haunted_bazar.Rescued(zone, name, mail)
--Engine callback function
function haunted_bazar.Rescued(zone, name, mail)


end

return haunted_bazar

