-- PMU Ground Controller for pmu_s1754 (Tanren Mines B14)
-- Generated by PMU Pipeline (New Era)
local pmu_s1754 = {}

function pmu_s1754.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1754.Enter(map)
  local music = ''
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1754.Update(map, time)
end

return pmu_s1754
