--[[
    Ground Controller: PixelLab Town (pixellab_test_town)
    Procedurally generated by PMDO Town Generator (Seed: 20260830)
]]

require 'origin.common'

local pixellab_test_town = {}

function pixellab_test_town.Init(map)
    DEBUG.EnableDbgCoro()
    PrintInfo("=>> Initializing ground pixellab_test_town")
end

function pixellab_test_town.Enter(map)
    GROUND:Hide('PLAYER')
    local player = CH('PLAYER')
    if player then
        GROUND:TeleportTo(player, 576, 979, Direction.Up)
    end
    GAME:FadeIn(20)
end

function pixellab_test_town.Exit(map)
    GAME:FadeOut(20)
end

return pixellab_test_town
