-- PMU Ground Controller for pmu_s915 (Moonlight Cliff)
-- Generated by PMU Pipeline (New Era)
local pmu_s915 = {}

function pmu_s915.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s915.Enter(map)
  local music = 'PMD2) Hidden Highland.mp3'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s915.Update(map, time)
end

return pmu_s915
