-- PMU Ground Controller for pmu_s1810 (Exbel, Grassroot Town)
-- Generated by PMU Pipeline (New Era)
local pmu_s1810 = {}

function pmu_s1810.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1810.Enter(map)
  local music = 'PMD2) Treasure Town.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1810.Update(map, time)
end

function pmu_s1810.Sign_1_Action(obj, activator)
  UI:WaitShowDialogue('Come here to cleanthe your thticky itemth!')
end

function pmu_s1810.Sign_2_Action(obj, activator)
  UI:WaitShowDialogue('Wigglytuff\'s Minigame Tent')
  UI:WaitShowDialogue('CTF has been redesigned!')
  UI:WaitShowDialogue('Come in and play!')
end

function pmu_s1810.Sign_3_Action(obj, activator)
  UI:WaitShowDialogue('Electivire\'s Moveset Services')
end

function pmu_s1810.Sign_4_Action(obj, activator)
  UI:WaitShowDialogue('Kangaskhan Storage')
  UI:WaitShowDialogue('Wild Plains Tavern')
  UI:WaitShowDialogue('Kecleon Shoppe')
end

function pmu_s1810.Sign_5_Action(obj, activator)
  UI:WaitShowDialogue('Kangaskhan Storage')
  UI:WaitShowDialogue('Wild Plains Tavern')
  UI:WaitShowDialogue('Kecleon Shoppe')
end

function pmu_s1810.Sign_6_Action(obj, activator)
  UI:WaitShowDialogue('Grassroot Housing Center')
  UI:WaitShowDialogue('Come here to visit houses or decorate your own!')
end

function pmu_s1810.Sign_7_Action(obj, activator)
  UI:WaitShowDialogue('Grassroot Housing Center')
  UI:WaitShowDialogue('Come here to visit houses or decorate your own!')
end

function pmu_s1810.Sign_8_Action(obj, activator)
  UI:WaitShowDialogue('Welcome to Grassroot Town!')
end

function pmu_s1810.Sign_9_Action(obj, activator)
  UI:WaitShowDialogue('Welcome to Grassroot Town!')
end

function pmu_s1810.Sign_10_Action(obj, activator)
  UI:WaitShowDialogue('Marowak Training Dojo')
  UI:WaitShowDialogue('Train your strenght, skill, speed and resistence in our training facilities!')
  UI:WaitShowDialogue('You can also fight your friends in the arena!')
end

function pmu_s1810.Sign_11_Action(obj, activator)
  UI:WaitShowDialogue('Marowak Training Dojo')
  UI:WaitShowDialogue('Train your strenght, skill, speed and resistence in our training facilities!')
  UI:WaitShowDialogue('You can also fight your friends in the arena!')
end

function pmu_s1810.Sign_12_Action(obj, activator)
  UI:WaitShowDialogue('To trade items with another Player use /trade')
  UI:WaitShowDialogue('if you drop items they may be stolen.')
end

function pmu_s1810.Sign_13_Action(obj, activator)
  UI:WaitShowDialogue('As of October 25th, 2010 the staff will not be selling guilds.')
  UI:WaitShowDialogue('This means that as of 10/25/2010 until present day, guilds will not be sold unless said otherwise.')
end

function pmu_s1810.Sign_14_Action(obj, activator)
  UI:WaitShowDialogue('As of October 25th, 2010 the staff will not be selling guilds.')
  UI:WaitShowDialogue('This means that as of 10/25/2010 until present day, guilds will not be sold unless said otherwise.')
end

function pmu_s1810.Sign_15_Action(obj, activator)
  UI:WaitShowDialogue('Welcome to Delite Plaza!')
  UI:WaitShowDialogue('Come on down and have a Deliteful Day!')
end

function pmu_s1810.Sign_16_Action(obj, activator)
  UI:WaitShowDialogue('Welcome to Delite Plaza!')
  UI:WaitShowDialogue('Come on down and have a Deliteful Day!')
end

function pmu_s1810.Sign_17_Action(obj, activator)
  UI:WaitShowDialogue('Welcome to Grassroot town, from early PMU7.')
  UI:WaitShowDialogue('A blast to the past, enjoy!')
end

function pmu_s1810.Sign_18_Action(obj, activator)
  UI:WaitShowDialogue('Welcome to Grassroot town, from early PMU7.')
  UI:WaitShowDialogue('A blast to the past, enjoy!')
end

return pmu_s1810
