-- PMU Ground Controller for pmu_s1785 (Boggy Wastes [Midway Point])
-- Generated by PMU Pipeline (New Era)
local pmu_s1785 = {}

function pmu_s1785.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1785.Enter(map)
  local music = 'HgSs) Ruins of Alph, Union Cave.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1785.Update(map, time)
end

return pmu_s1785
