-- PMU Ground Controller for pmu_s95 (Stone-Solid Dungeon B1F)
-- Generated by PMU Pipeline (New Era)
local pmu_s95 = {}

function pmu_s95.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s95.Enter(map)
  local music = 'PMD) Magma Cavern Pit.mp3'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s95.Update(map, time)
end

return pmu_s95
