-- PMU Ground Controller for pmu_s1954 (Char's Sandy Dungeon map.)
-- Generated by PMU Pipeline (New Era)
local pmu_s1954 = {}

function pmu_s1954.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s1954.Enter(map)
  local music = ''
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s1954.Update(map, time)
end

function pmu_s1954.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_2_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_3_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_4_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_5_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_6_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_7_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_8_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_9_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_10_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_11_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_12_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_13_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1987', 'Entrance', false)
end

function pmu_s1954.Warp_14_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_15_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_16_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_17_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_18_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_19_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

function pmu_s1954.Warp_20_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s1954', 'Entrance', false)
end

return pmu_s1954
