-- PMU Ground Controller for pmu_s100 (Sour Root Cave B1F)
-- Generated by PMU Pipeline (New Era)
local pmu_s100 = {}

function pmu_s100.Init(map)
  DEBUG.EnableDbgScript(true)
end

function pmu_s100.Enter(map)
  local music = 'PMDB) Tiny Woods.ogg'
  if music ~= '' then
    SOUND:PlayBGM(music, true)
  end
end

function pmu_s100.Update(map, time)
end

function pmu_s100.Warp_1_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap('pmu_s104', 'Entrance', false)
end

return pmu_s100
